// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: candles.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkCandleExists = `-- name: CheckCandleExists :one
SELECT EXISTS(
    SELECT 1 FROM candles
    WHERE symbol = $1
      AND timeframe = $2
      AND timestamp = $3
) AS exists
`

type CheckCandleExistsParams struct {
	Symbol    string `json:"symbol"`
	Timeframe string `json:"timeframe"`
	Timestamp int64  `json:"timestamp"`
}

func (q *Queries) CheckCandleExists(ctx context.Context, arg CheckCandleExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkCandleExists, arg.Symbol, arg.Timeframe, arg.Timestamp)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countCandles = `-- name: CountCandles :one

SELECT COUNT(*) FROM candles
WHERE symbol = $1
  AND timeframe = $2
`

type CountCandlesParams struct {
	Symbol    string `json:"symbol"`
	Timeframe string `json:"timeframe"`
}

// =============================================================================
// AGGREGATE Operations
// =============================================================================
func (q *Queries) CountCandles(ctx context.Context, arg CountCandlesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCandles, arg.Symbol, arg.Timeframe)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCandlesInRange = `-- name: CountCandlesInRange :one
SELECT COUNT(*) FROM candles
WHERE symbol = $1
  AND timeframe = $2
  AND timestamp >= $3
  AND timestamp <= $4
`

type CountCandlesInRangeParams struct {
	Symbol      string `json:"symbol"`
	Timeframe   string `json:"timeframe"`
	Timestamp   int64  `json:"timestamp"`
	Timestamp_2 int64  `json:"timestamp_2"`
}

func (q *Queries) CountCandlesInRange(ctx context.Context, arg CountCandlesInRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCandlesInRange,
		arg.Symbol,
		arg.Timeframe,
		arg.Timestamp,
		arg.Timestamp_2,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCandle = `-- name: CreateCandle :one


INSERT INTO candles (
    symbol,
    timeframe,
    timestamp,
    open,
    high,
    low,
    close,
    volume
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (symbol, timeframe, timestamp) DO NOTHING
RETURNING id, symbol, timeframe, timestamp, open, high, low, close, volume, created_at, updated_at
`

type CreateCandleParams struct {
	Symbol    string         `json:"symbol"`
	Timeframe string         `json:"timeframe"`
	Timestamp int64          `json:"timestamp"`
	Open      pgtype.Numeric `json:"open"`
	High      pgtype.Numeric `json:"high"`
	Low       pgtype.Numeric `json:"low"`
	Close     pgtype.Numeric `json:"close"`
	Volume    pgtype.Numeric `json:"volume"`
}

// Candles Queries
// CRUD operations and queries for OHLC candlestick data
// =============================================================================
// CREATE Operations
// =============================================================================
func (q *Queries) CreateCandle(ctx context.Context, arg CreateCandleParams) (Candle, error) {
	row := q.db.QueryRow(ctx, createCandle,
		arg.Symbol,
		arg.Timeframe,
		arg.Timestamp,
		arg.Open,
		arg.High,
		arg.Low,
		arg.Close,
		arg.Volume,
	)
	var i Candle
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Timeframe,
		&i.Timestamp,
		&i.Open,
		&i.High,
		&i.Low,
		&i.Close,
		&i.Volume,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

type CreateCandleBatchParams struct {
	Symbol    string         `json:"symbol"`
	Timeframe string         `json:"timeframe"`
	Timestamp int64          `json:"timestamp"`
	Open      pgtype.Numeric `json:"open"`
	High      pgtype.Numeric `json:"high"`
	Low       pgtype.Numeric `json:"low"`
	Close     pgtype.Numeric `json:"close"`
	Volume    pgtype.Numeric `json:"volume"`
}

const deleteCandle = `-- name: DeleteCandle :exec

DELETE FROM candles
WHERE id = $1
`

// =============================================================================
// DELETE Operations
// =============================================================================
func (q *Queries) DeleteCandle(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCandle, id)
	return err
}

const deleteCandlesBySymbol = `-- name: DeleteCandlesBySymbol :exec
DELETE FROM candles
WHERE symbol = $1
`

func (q *Queries) DeleteCandlesBySymbol(ctx context.Context, symbol string) error {
	_, err := q.db.Exec(ctx, deleteCandlesBySymbol, symbol)
	return err
}

const deleteCandlesByTimeframe = `-- name: DeleteCandlesByTimeframe :exec
DELETE FROM candles
WHERE symbol = $1
  AND timeframe = $2
`

type DeleteCandlesByTimeframeParams struct {
	Symbol    string `json:"symbol"`
	Timeframe string `json:"timeframe"`
}

func (q *Queries) DeleteCandlesByTimeframe(ctx context.Context, arg DeleteCandlesByTimeframeParams) error {
	_, err := q.db.Exec(ctx, deleteCandlesByTimeframe, arg.Symbol, arg.Timeframe)
	return err
}

const deleteCandlesInRange = `-- name: DeleteCandlesInRange :exec
DELETE FROM candles
WHERE symbol = $1
  AND timeframe = $2
  AND timestamp >= $3
  AND timestamp <= $4
`

type DeleteCandlesInRangeParams struct {
	Symbol      string `json:"symbol"`
	Timeframe   string `json:"timeframe"`
	Timestamp   int64  `json:"timestamp"`
	Timestamp_2 int64  `json:"timestamp_2"`
}

func (q *Queries) DeleteCandlesInRange(ctx context.Context, arg DeleteCandlesInRangeParams) error {
	_, err := q.db.Exec(ctx, deleteCandlesInRange,
		arg.Symbol,
		arg.Timeframe,
		arg.Timestamp,
		arg.Timestamp_2,
	)
	return err
}

const deleteOldCandles = `-- name: DeleteOldCandles :exec
DELETE FROM candles
WHERE timestamp < $1
`

func (q *Queries) DeleteOldCandles(ctx context.Context, timestamp int64) error {
	_, err := q.db.Exec(ctx, deleteOldCandles, timestamp)
	return err
}

const getCandle = `-- name: GetCandle :one
SELECT id, symbol, timeframe, timestamp, open, high, low, close, volume, created_at, updated_at FROM candles
WHERE symbol = $1
  AND timeframe = $2
  AND timestamp = $3
LIMIT 1
`

type GetCandleParams struct {
	Symbol    string `json:"symbol"`
	Timeframe string `json:"timeframe"`
	Timestamp int64  `json:"timestamp"`
}

func (q *Queries) GetCandle(ctx context.Context, arg GetCandleParams) (Candle, error) {
	row := q.db.QueryRow(ctx, getCandle, arg.Symbol, arg.Timeframe, arg.Timestamp)
	var i Candle
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Timeframe,
		&i.Timestamp,
		&i.Open,
		&i.High,
		&i.Low,
		&i.Close,
		&i.Volume,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCandleByID = `-- name: GetCandleByID :one

SELECT id, symbol, timeframe, timestamp, open, high, low, close, volume, created_at, updated_at FROM candles
WHERE id = $1
`

// =============================================================================
// READ Operations
// =============================================================================
func (q *Queries) GetCandleByID(ctx context.Context, id int64) (Candle, error) {
	row := q.db.QueryRow(ctx, getCandleByID, id)
	var i Candle
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Timeframe,
		&i.Timestamp,
		&i.Open,
		&i.High,
		&i.Low,
		&i.Close,
		&i.Volume,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCandleGaps = `-- name: GetCandleGaps :many
SELECT 
    symbol,
    timeframe,
    timestamp as gap_start,
    LEAD(timestamp) OVER (ORDER BY timestamp) as gap_end,
    LEAD(timestamp) OVER (ORDER BY timestamp) - timestamp as gap_seconds
FROM candles
WHERE symbol = $1
  AND timeframe = $2
  AND timestamp >= $3
  AND timestamp <= $4
ORDER BY timestamp
`

type GetCandleGapsParams struct {
	Symbol      string `json:"symbol"`
	Timeframe   string `json:"timeframe"`
	Timestamp   int64  `json:"timestamp"`
	Timestamp_2 int64  `json:"timestamp_2"`
}

type GetCandleGapsRow struct {
	Symbol     string      `json:"symbol"`
	Timeframe  string      `json:"timeframe"`
	GapStart   int64       `json:"gap_start"`
	GapEnd     interface{} `json:"gap_end"`
	GapSeconds int32       `json:"gap_seconds"`
}

func (q *Queries) GetCandleGaps(ctx context.Context, arg GetCandleGapsParams) ([]GetCandleGapsRow, error) {
	rows, err := q.db.Query(ctx, getCandleGaps,
		arg.Symbol,
		arg.Timeframe,
		arg.Timestamp,
		arg.Timestamp_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCandleGapsRow
	for rows.Next() {
		var i GetCandleGapsRow
		if err := rows.Scan(
			&i.Symbol,
			&i.Timeframe,
			&i.GapStart,
			&i.GapEnd,
			&i.GapSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCandleStats = `-- name: GetCandleStats :one
SELECT 
    COUNT(*) as total_candles,
    MIN(timestamp) as first_timestamp,
    MAX(timestamp) as last_timestamp,
    MIN(low) as lowest_price,
    MAX(high) as highest_price,
    AVG(volume) as avg_volume
FROM candles
WHERE symbol = $1
  AND timeframe = $2
`

type GetCandleStatsParams struct {
	Symbol    string `json:"symbol"`
	Timeframe string `json:"timeframe"`
}

type GetCandleStatsRow struct {
	TotalCandles   int64       `json:"total_candles"`
	FirstTimestamp interface{} `json:"first_timestamp"`
	LastTimestamp  interface{} `json:"last_timestamp"`
	LowestPrice    interface{} `json:"lowest_price"`
	HighestPrice   interface{} `json:"highest_price"`
	AvgVolume      float64     `json:"avg_volume"`
}

func (q *Queries) GetCandleStats(ctx context.Context, arg GetCandleStatsParams) (GetCandleStatsRow, error) {
	row := q.db.QueryRow(ctx, getCandleStats, arg.Symbol, arg.Timeframe)
	var i GetCandleStatsRow
	err := row.Scan(
		&i.TotalCandles,
		&i.FirstTimestamp,
		&i.LastTimestamp,
		&i.LowestPrice,
		&i.HighestPrice,
		&i.AvgVolume,
	)
	return i, err
}

const getCandleStatsInRange = `-- name: GetCandleStatsInRange :one
SELECT 
    COUNT(*) as total_candles,
    MIN(low) as lowest_price,
    MAX(high) as highest_price,
    AVG(close) as avg_close,
    SUM(volume) as total_volume,
    AVG(volume) as avg_volume
FROM candles
WHERE symbol = $1
  AND timeframe = $2
  AND timestamp >= $3
  AND timestamp <= $4
`

type GetCandleStatsInRangeParams struct {
	Symbol      string `json:"symbol"`
	Timeframe   string `json:"timeframe"`
	Timestamp   int64  `json:"timestamp"`
	Timestamp_2 int64  `json:"timestamp_2"`
}

type GetCandleStatsInRangeRow struct {
	TotalCandles int64       `json:"total_candles"`
	LowestPrice  interface{} `json:"lowest_price"`
	HighestPrice interface{} `json:"highest_price"`
	AvgClose     float64     `json:"avg_close"`
	TotalVolume  int64       `json:"total_volume"`
	AvgVolume    float64     `json:"avg_volume"`
}

func (q *Queries) GetCandleStatsInRange(ctx context.Context, arg GetCandleStatsInRangeParams) (GetCandleStatsInRangeRow, error) {
	row := q.db.QueryRow(ctx, getCandleStatsInRange,
		arg.Symbol,
		arg.Timeframe,
		arg.Timestamp,
		arg.Timestamp_2,
	)
	var i GetCandleStatsInRangeRow
	err := row.Scan(
		&i.TotalCandles,
		&i.LowestPrice,
		&i.HighestPrice,
		&i.AvgClose,
		&i.TotalVolume,
		&i.AvgVolume,
	)
	return i, err
}

const getCandlesAfterTimestamp = `-- name: GetCandlesAfterTimestamp :many
SELECT id, symbol, timeframe, timestamp, open, high, low, close, volume, created_at, updated_at FROM candles
WHERE symbol = $1
  AND timeframe = $2
  AND timestamp > $3
ORDER BY timestamp ASC
LIMIT $4
`

type GetCandlesAfterTimestampParams struct {
	Symbol    string `json:"symbol"`
	Timeframe string `json:"timeframe"`
	Timestamp int64  `json:"timestamp"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) GetCandlesAfterTimestamp(ctx context.Context, arg GetCandlesAfterTimestampParams) ([]Candle, error) {
	rows, err := q.db.Query(ctx, getCandlesAfterTimestamp,
		arg.Symbol,
		arg.Timeframe,
		arg.Timestamp,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Candle
	for rows.Next() {
		var i Candle
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Timeframe,
			&i.Timestamp,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCandlesBeforeTimestamp = `-- name: GetCandlesBeforeTimestamp :many
SELECT id, symbol, timeframe, timestamp, open, high, low, close, volume, created_at, updated_at FROM candles
WHERE symbol = $1
  AND timeframe = $2
  AND timestamp < $3
ORDER BY timestamp DESC
LIMIT $4
`

type GetCandlesBeforeTimestampParams struct {
	Symbol    string `json:"symbol"`
	Timeframe string `json:"timeframe"`
	Timestamp int64  `json:"timestamp"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) GetCandlesBeforeTimestamp(ctx context.Context, arg GetCandlesBeforeTimestampParams) ([]Candle, error) {
	rows, err := q.db.Query(ctx, getCandlesBeforeTimestamp,
		arg.Symbol,
		arg.Timeframe,
		arg.Timestamp,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Candle
	for rows.Next() {
		var i Candle
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Timeframe,
			&i.Timestamp,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCandlesBySymbols = `-- name: GetCandlesBySymbols :many
SELECT id, symbol, timeframe, timestamp, open, high, low, close, volume, created_at, updated_at FROM candles
WHERE symbol = ANY($1::varchar[])
  AND timeframe = $2
  AND timestamp >= $3
  AND timestamp <= $4
ORDER BY symbol, timestamp ASC
`

type GetCandlesBySymbolsParams struct {
	Column1     []string `json:"column_1"`
	Timeframe   string   `json:"timeframe"`
	Timestamp   int64    `json:"timestamp"`
	Timestamp_2 int64    `json:"timestamp_2"`
}

func (q *Queries) GetCandlesBySymbols(ctx context.Context, arg GetCandlesBySymbolsParams) ([]Candle, error) {
	rows, err := q.db.Query(ctx, getCandlesBySymbols,
		arg.Column1,
		arg.Timeframe,
		arg.Timestamp,
		arg.Timestamp_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Candle
	for rows.Next() {
		var i Candle
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Timeframe,
			&i.Timestamp,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCandlesInRange = `-- name: GetCandlesInRange :many
SELECT id, symbol, timeframe, timestamp, open, high, low, close, volume, created_at, updated_at FROM candles
WHERE symbol = $1
  AND timeframe = $2
  AND timestamp >= $3
  AND timestamp <= $4
ORDER BY timestamp ASC
`

type GetCandlesInRangeParams struct {
	Symbol      string `json:"symbol"`
	Timeframe   string `json:"timeframe"`
	Timestamp   int64  `json:"timestamp"`
	Timestamp_2 int64  `json:"timestamp_2"`
}

func (q *Queries) GetCandlesInRange(ctx context.Context, arg GetCandlesInRangeParams) ([]Candle, error) {
	rows, err := q.db.Query(ctx, getCandlesInRange,
		arg.Symbol,
		arg.Timeframe,
		arg.Timestamp,
		arg.Timestamp_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Candle
	for rows.Next() {
		var i Candle
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Timeframe,
			&i.Timestamp,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctSymbols = `-- name: GetDistinctSymbols :many

SELECT DISTINCT symbol
FROM candles
ORDER BY symbol
`

// =============================================================================
// UTILITY Operations
// =============================================================================
func (q *Queries) GetDistinctSymbols(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getDistinctSymbols)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var symbol string
		if err := rows.Scan(&symbol); err != nil {
			return nil, err
		}
		items = append(items, symbol)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctTimeframes = `-- name: GetDistinctTimeframes :many
SELECT DISTINCT timeframe
FROM candles
WHERE symbol = $1
ORDER BY timeframe
`

func (q *Queries) GetDistinctTimeframes(ctx context.Context, symbol string) ([]string, error) {
	rows, err := q.db.Query(ctx, getDistinctTimeframes, symbol)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var timeframe string
		if err := rows.Scan(&timeframe); err != nil {
			return nil, err
		}
		items = append(items, timeframe)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestCandle = `-- name: GetLatestCandle :one
SELECT id, symbol, timeframe, timestamp, open, high, low, close, volume, created_at, updated_at FROM candles
WHERE symbol = $1
  AND timeframe = $2
ORDER BY timestamp DESC
LIMIT 1
`

type GetLatestCandleParams struct {
	Symbol    string `json:"symbol"`
	Timeframe string `json:"timeframe"`
}

func (q *Queries) GetLatestCandle(ctx context.Context, arg GetLatestCandleParams) (Candle, error) {
	row := q.db.QueryRow(ctx, getLatestCandle, arg.Symbol, arg.Timeframe)
	var i Candle
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Timeframe,
		&i.Timestamp,
		&i.Open,
		&i.High,
		&i.Low,
		&i.Close,
		&i.Volume,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOldestCandle = `-- name: GetOldestCandle :one
SELECT id, symbol, timeframe, timestamp, open, high, low, close, volume, created_at, updated_at FROM candles
WHERE symbol = $1
  AND timeframe = $2
ORDER BY timestamp ASC
LIMIT 1
`

type GetOldestCandleParams struct {
	Symbol    string `json:"symbol"`
	Timeframe string `json:"timeframe"`
}

func (q *Queries) GetOldestCandle(ctx context.Context, arg GetOldestCandleParams) (Candle, error) {
	row := q.db.QueryRow(ctx, getOldestCandle, arg.Symbol, arg.Timeframe)
	var i Candle
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Timeframe,
		&i.Timestamp,
		&i.Open,
		&i.High,
		&i.Low,
		&i.Close,
		&i.Volume,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecentCandles = `-- name: GetRecentCandles :many
SELECT id, symbol, timeframe, timestamp, open, high, low, close, volume, created_at, updated_at FROM candles
WHERE symbol = $1
  AND timeframe = $2
ORDER BY timestamp DESC
LIMIT $3
`

type GetRecentCandlesParams struct {
	Symbol    string `json:"symbol"`
	Timeframe string `json:"timeframe"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) GetRecentCandles(ctx context.Context, arg GetRecentCandlesParams) ([]Candle, error) {
	rows, err := q.db.Query(ctx, getRecentCandles, arg.Symbol, arg.Timeframe, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Candle
	for rows.Next() {
		var i Candle
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Timeframe,
			&i.Timestamp,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSymbolTimeframePairs = `-- name: GetSymbolTimeframePairs :many
SELECT DISTINCT symbol, timeframe
FROM candles
ORDER BY symbol, timeframe
`

type GetSymbolTimeframePairsRow struct {
	Symbol    string `json:"symbol"`
	Timeframe string `json:"timeframe"`
}

func (q *Queries) GetSymbolTimeframePairs(ctx context.Context) ([]GetSymbolTimeframePairsRow, error) {
	rows, err := q.db.Query(ctx, getSymbolTimeframePairs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSymbolTimeframePairsRow
	for rows.Next() {
		var i GetSymbolTimeframePairsRow
		if err := rows.Scan(&i.Symbol, &i.Timeframe); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVolumeLeaders = `-- name: GetVolumeLeaders :many
SELECT 
    symbol,
    timeframe,
    SUM(volume) as total_volume,
    AVG(volume) as avg_volume,
    MAX(volume) as max_volume
FROM candles
WHERE timestamp >= $1
  AND timestamp <= $2
GROUP BY symbol, timeframe
ORDER BY total_volume DESC
LIMIT $3
`

type GetVolumeLeadersParams struct {
	Timestamp   int64 `json:"timestamp"`
	Timestamp_2 int64 `json:"timestamp_2"`
	Limit       int32 `json:"limit"`
}

type GetVolumeLeadersRow struct {
	Symbol      string      `json:"symbol"`
	Timeframe   string      `json:"timeframe"`
	TotalVolume int64       `json:"total_volume"`
	AvgVolume   float64     `json:"avg_volume"`
	MaxVolume   interface{} `json:"max_volume"`
}

func (q *Queries) GetVolumeLeaders(ctx context.Context, arg GetVolumeLeadersParams) ([]GetVolumeLeadersRow, error) {
	rows, err := q.db.Query(ctx, getVolumeLeaders, arg.Timestamp, arg.Timestamp_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVolumeLeadersRow
	for rows.Next() {
		var i GetVolumeLeadersRow
		if err := rows.Scan(
			&i.Symbol,
			&i.Timeframe,
			&i.TotalVolume,
			&i.AvgVolume,
			&i.MaxVolume,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCandlesPaginated = `-- name: ListCandlesPaginated :many
SELECT id, symbol, timeframe, timestamp, open, high, low, close, volume, created_at, updated_at FROM candles
WHERE symbol = $1
  AND timeframe = $2
ORDER BY timestamp DESC
LIMIT $3
OFFSET $4
`

type ListCandlesPaginatedParams struct {
	Symbol    string `json:"symbol"`
	Timeframe string `json:"timeframe"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListCandlesPaginated(ctx context.Context, arg ListCandlesPaginatedParams) ([]Candle, error) {
	rows, err := q.db.Query(ctx, listCandlesPaginated,
		arg.Symbol,
		arg.Timeframe,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Candle
	for rows.Next() {
		var i Candle
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Timeframe,
			&i.Timestamp,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCandle = `-- name: UpdateCandle :one

UPDATE candles
SET 
    open = $4,
    high = $5,
    low = $6,
    close = $7,
    volume = $8,
    updated_at = CURRENT_TIMESTAMP
WHERE symbol = $1
  AND timeframe = $2
  AND timestamp = $3
RETURNING id, symbol, timeframe, timestamp, open, high, low, close, volume, created_at, updated_at
`

type UpdateCandleParams struct {
	Symbol    string         `json:"symbol"`
	Timeframe string         `json:"timeframe"`
	Timestamp int64          `json:"timestamp"`
	Open      pgtype.Numeric `json:"open"`
	High      pgtype.Numeric `json:"high"`
	Low       pgtype.Numeric `json:"low"`
	Close     pgtype.Numeric `json:"close"`
	Volume    pgtype.Numeric `json:"volume"`
}

// =============================================================================
// UPDATE Operations
// =============================================================================
func (q *Queries) UpdateCandle(ctx context.Context, arg UpdateCandleParams) (Candle, error) {
	row := q.db.QueryRow(ctx, updateCandle,
		arg.Symbol,
		arg.Timeframe,
		arg.Timestamp,
		arg.Open,
		arg.High,
		arg.Low,
		arg.Close,
		arg.Volume,
	)
	var i Candle
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Timeframe,
		&i.Timestamp,
		&i.Open,
		&i.High,
		&i.Low,
		&i.Close,
		&i.Volume,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
