// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: configs.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addConfigTag = `-- name: AddConfigTag :exec
UPDATE configs
SET 
    tags = array_append(tags, $2),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND NOT ($2 = ANY(tags))
`

type AddConfigTagParams struct {
	ID          int64       `json:"id"`
	ArrayAppend interface{} `json:"array_append"`
}

func (q *Queries) AddConfigTag(ctx context.Context, arg AddConfigTagParams) error {
	_, err := q.db.Exec(ctx, addConfigTag, arg.ID, arg.ArrayAppend)
	return err
}

const checkConfigExists = `-- name: CheckConfigExists :one

SELECT EXISTS(
    SELECT 1 FROM configs WHERE id = $1
) AS exists
`

// =============================================================================
// UTILITY Operations
// =============================================================================
func (q *Queries) CheckConfigExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, checkConfigExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkConfigNameExists = `-- name: CheckConfigNameExists :one
SELECT EXISTS(
    SELECT 1 FROM configs WHERE name = $1
) AS exists
`

func (q *Queries) CheckConfigNameExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, checkConfigNameExists, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countConfigs = `-- name: CountConfigs :one

SELECT COUNT(*) FROM configs
`

// =============================================================================
// AGGREGATE Operations
// =============================================================================
func (q *Queries) CountConfigs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countConfigs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countConfigsByStrategy = `-- name: CountConfigsByStrategy :one
SELECT COUNT(*) FROM configs
WHERE strategy = $1
`

func (q *Queries) CountConfigsByStrategy(ctx context.Context, strategy string) (int64, error) {
	row := q.db.QueryRow(ctx, countConfigsByStrategy, strategy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConfig = `-- name: CreateConfig :one


INSERT INTO configs (
    name,
    description,
    strategy,
    volatility,
    drift,
    starting_price,
    candle_interval,
    symbol,
    market_behavior,
    trend_strength,
    mean_reversion_speed,
    advanced_params,
    tags
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, name, description, strategy, volatility, drift, starting_price, candle_interval, symbol, market_behavior, trend_strength, mean_reversion_speed, advanced_params, is_default, is_favorite, is_public, times_used, last_used_at, created_by, tags, created_at, updated_at
`

type CreateConfigParams struct {
	Name               string         `json:"name"`
	Description        pgtype.Text    `json:"description"`
	Strategy           string         `json:"strategy"`
	Volatility         pgtype.Numeric `json:"volatility"`
	Drift              pgtype.Numeric `json:"drift"`
	StartingPrice      pgtype.Numeric `json:"starting_price"`
	CandleInterval     string         `json:"candle_interval"`
	Symbol             string         `json:"symbol"`
	MarketBehavior     pgtype.Text    `json:"market_behavior"`
	TrendStrength      pgtype.Numeric `json:"trend_strength"`
	MeanReversionSpeed pgtype.Numeric `json:"mean_reversion_speed"`
	AdvancedParams     []byte         `json:"advanced_params"`
	Tags               []string       `json:"tags"`
}

// Configs Queries
// CRUD operations and queries for simulation configurations
// =============================================================================
// CREATE Operations
// =============================================================================
func (q *Queries) CreateConfig(ctx context.Context, arg CreateConfigParams) (Config, error) {
	row := q.db.QueryRow(ctx, createConfig,
		arg.Name,
		arg.Description,
		arg.Strategy,
		arg.Volatility,
		arg.Drift,
		arg.StartingPrice,
		arg.CandleInterval,
		arg.Symbol,
		arg.MarketBehavior,
		arg.TrendStrength,
		arg.MeanReversionSpeed,
		arg.AdvancedParams,
		arg.Tags,
	)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Strategy,
		&i.Volatility,
		&i.Drift,
		&i.StartingPrice,
		&i.CandleInterval,
		&i.Symbol,
		&i.MarketBehavior,
		&i.TrendStrength,
		&i.MeanReversionSpeed,
		&i.AdvancedParams,
		&i.IsDefault,
		&i.IsFavorite,
		&i.IsPublic,
		&i.TimesUsed,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConfig = `-- name: DeleteConfig :exec

DELETE FROM configs
WHERE id = $1
`

// =============================================================================
// DELETE Operations
// =============================================================================
func (q *Queries) DeleteConfig(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteConfig, id)
	return err
}

const deleteUnusedConfigs = `-- name: DeleteUnusedConfigs :exec
DELETE FROM configs
WHERE times_used = 0
  AND is_favorite = false
  AND is_default = false
  AND created_at < $1
`

func (q *Queries) DeleteUnusedConfigs(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteUnusedConfigs, createdAt)
	return err
}

const duplicateConfig = `-- name: DuplicateConfig :one
INSERT INTO configs (
    name,
    description,
    strategy,
    volatility,
    drift,
    starting_price,
    candle_interval,
    symbol,
    market_behavior,
    trend_strength,
    mean_reversion_speed,
    advanced_params,
    tags,
    created_by
)
SELECT 
    $2 as name,
    c.description,
    c.strategy,
    c.volatility,
    c.drift,
    c.starting_price,
    c.candle_interval,
    c.symbol,
    c.market_behavior,
    c.trend_strength,
    c.mean_reversion_speed,
    c.advanced_params,
    c.tags,
    c.created_by
FROM configs c
WHERE c.id = $1
RETURNING id, name, description, strategy, volatility, drift, starting_price, candle_interval, symbol, market_behavior, trend_strength, mean_reversion_speed, advanced_params, is_default, is_favorite, is_public, times_used, last_used_at, created_by, tags, created_at, updated_at
`

type DuplicateConfigParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) DuplicateConfig(ctx context.Context, arg DuplicateConfigParams) (Config, error) {
	row := q.db.QueryRow(ctx, duplicateConfig, arg.ID, arg.Name)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Strategy,
		&i.Volatility,
		&i.Drift,
		&i.StartingPrice,
		&i.CandleInterval,
		&i.Symbol,
		&i.MarketBehavior,
		&i.TrendStrength,
		&i.MeanReversionSpeed,
		&i.AdvancedParams,
		&i.IsDefault,
		&i.IsFavorite,
		&i.IsPublic,
		&i.TimesUsed,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConfigByID = `-- name: GetConfigByID :one

SELECT id, name, description, strategy, volatility, drift, starting_price, candle_interval, symbol, market_behavior, trend_strength, mean_reversion_speed, advanced_params, is_default, is_favorite, is_public, times_used, last_used_at, created_by, tags, created_at, updated_at FROM configs
WHERE id = $1
`

// =============================================================================
// READ Operations
// =============================================================================
func (q *Queries) GetConfigByID(ctx context.Context, id int64) (Config, error) {
	row := q.db.QueryRow(ctx, getConfigByID, id)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Strategy,
		&i.Volatility,
		&i.Drift,
		&i.StartingPrice,
		&i.CandleInterval,
		&i.Symbol,
		&i.MarketBehavior,
		&i.TrendStrength,
		&i.MeanReversionSpeed,
		&i.AdvancedParams,
		&i.IsDefault,
		&i.IsFavorite,
		&i.IsPublic,
		&i.TimesUsed,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConfigByName = `-- name: GetConfigByName :one
SELECT id, name, description, strategy, volatility, drift, starting_price, candle_interval, symbol, market_behavior, trend_strength, mean_reversion_speed, advanced_params, is_default, is_favorite, is_public, times_used, last_used_at, created_by, tags, created_at, updated_at FROM configs
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetConfigByName(ctx context.Context, name string) (Config, error) {
	row := q.db.QueryRow(ctx, getConfigByName, name)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Strategy,
		&i.Volatility,
		&i.Drift,
		&i.StartingPrice,
		&i.CandleInterval,
		&i.Symbol,
		&i.MarketBehavior,
		&i.TrendStrength,
		&i.MeanReversionSpeed,
		&i.AdvancedParams,
		&i.IsDefault,
		&i.IsFavorite,
		&i.IsPublic,
		&i.TimesUsed,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConfigByNameOrDefault = `-- name: GetConfigByNameOrDefault :one
SELECT id, name, description, strategy, volatility, drift, starting_price, candle_interval, symbol, market_behavior, trend_strength, mean_reversion_speed, advanced_params, is_default, is_favorite, is_public, times_used, last_used_at, created_by, tags, created_at, updated_at FROM configs
WHERE name = $1
   OR (is_default = true AND $1 = '')
ORDER BY (name = $1) DESC
LIMIT 1
`

func (q *Queries) GetConfigByNameOrDefault(ctx context.Context, name string) (Config, error) {
	row := q.db.QueryRow(ctx, getConfigByNameOrDefault, name)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Strategy,
		&i.Volatility,
		&i.Drift,
		&i.StartingPrice,
		&i.CandleInterval,
		&i.Symbol,
		&i.MarketBehavior,
		&i.TrendStrength,
		&i.MeanReversionSpeed,
		&i.AdvancedParams,
		&i.IsDefault,
		&i.IsFavorite,
		&i.IsPublic,
		&i.TimesUsed,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConfigStats = `-- name: GetConfigStats :one
SELECT 
    COUNT(*) as total_configs,
    COUNT(*) FILTER (WHERE is_favorite = true) as favorite_count,
    COUNT(*) FILTER (WHERE is_public = true) as public_count,
    COUNT(*) FILTER (WHERE is_default = true) as default_count,
    AVG(times_used) as avg_times_used,
    MAX(times_used) as max_times_used,
    AVG(volatility) as avg_volatility
FROM configs
`

type GetConfigStatsRow struct {
	TotalConfigs  int64       `json:"total_configs"`
	FavoriteCount int64       `json:"favorite_count"`
	PublicCount   int64       `json:"public_count"`
	DefaultCount  int64       `json:"default_count"`
	AvgTimesUsed  float64     `json:"avg_times_used"`
	MaxTimesUsed  interface{} `json:"max_times_used"`
	AvgVolatility float64     `json:"avg_volatility"`
}

func (q *Queries) GetConfigStats(ctx context.Context) (GetConfigStatsRow, error) {
	row := q.db.QueryRow(ctx, getConfigStats)
	var i GetConfigStatsRow
	err := row.Scan(
		&i.TotalConfigs,
		&i.FavoriteCount,
		&i.PublicCount,
		&i.DefaultCount,
		&i.AvgTimesUsed,
		&i.MaxTimesUsed,
		&i.AvgVolatility,
	)
	return i, err
}

const getConfigsByCreator = `-- name: GetConfigsByCreator :many
SELECT id, name, description, strategy, volatility, drift, starting_price, candle_interval, symbol, market_behavior, trend_strength, mean_reversion_speed, advanced_params, is_default, is_favorite, is_public, times_used, last_used_at, created_by, tags, created_at, updated_at FROM configs
WHERE created_by = $1
ORDER BY created_at DESC
`

func (q *Queries) GetConfigsByCreator(ctx context.Context, createdBy pgtype.Text) ([]Config, error) {
	rows, err := q.db.Query(ctx, getConfigsByCreator, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Config
	for rows.Next() {
		var i Config
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Strategy,
			&i.Volatility,
			&i.Drift,
			&i.StartingPrice,
			&i.CandleInterval,
			&i.Symbol,
			&i.MarketBehavior,
			&i.TrendStrength,
			&i.MeanReversionSpeed,
			&i.AdvancedParams,
			&i.IsDefault,
			&i.IsFavorite,
			&i.IsPublic,
			&i.TimesUsed,
			&i.LastUsedAt,
			&i.CreatedBy,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConfigsByMarketBehavior = `-- name: GetConfigsByMarketBehavior :many
SELECT id, name, description, strategy, volatility, drift, starting_price, candle_interval, symbol, market_behavior, trend_strength, mean_reversion_speed, advanced_params, is_default, is_favorite, is_public, times_used, last_used_at, created_by, tags, created_at, updated_at FROM configs
WHERE market_behavior = $1
ORDER BY created_at DESC
`

func (q *Queries) GetConfigsByMarketBehavior(ctx context.Context, marketBehavior pgtype.Text) ([]Config, error) {
	rows, err := q.db.Query(ctx, getConfigsByMarketBehavior, marketBehavior)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Config
	for rows.Next() {
		var i Config
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Strategy,
			&i.Volatility,
			&i.Drift,
			&i.StartingPrice,
			&i.CandleInterval,
			&i.Symbol,
			&i.MarketBehavior,
			&i.TrendStrength,
			&i.MeanReversionSpeed,
			&i.AdvancedParams,
			&i.IsDefault,
			&i.IsFavorite,
			&i.IsPublic,
			&i.TimesUsed,
			&i.LastUsedAt,
			&i.CreatedBy,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConfigsByStrategy = `-- name: GetConfigsByStrategy :many
SELECT id, name, description, strategy, volatility, drift, starting_price, candle_interval, symbol, market_behavior, trend_strength, mean_reversion_speed, advanced_params, is_default, is_favorite, is_public, times_used, last_used_at, created_by, tags, created_at, updated_at FROM configs
WHERE strategy = $1
ORDER BY created_at DESC
`

func (q *Queries) GetConfigsByStrategy(ctx context.Context, strategy string) ([]Config, error) {
	rows, err := q.db.Query(ctx, getConfigsByStrategy, strategy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Config
	for rows.Next() {
		var i Config
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Strategy,
			&i.Volatility,
			&i.Drift,
			&i.StartingPrice,
			&i.CandleInterval,
			&i.Symbol,
			&i.MarketBehavior,
			&i.TrendStrength,
			&i.MeanReversionSpeed,
			&i.AdvancedParams,
			&i.IsDefault,
			&i.IsFavorite,
			&i.IsPublic,
			&i.TimesUsed,
			&i.LastUsedAt,
			&i.CreatedBy,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConfigsWithTags = `-- name: GetConfigsWithTags :many
SELECT id, name, description, strategy, volatility, drift, starting_price, candle_interval, symbol, market_behavior, trend_strength, mean_reversion_speed, advanced_params, is_default, is_favorite, is_public, times_used, last_used_at, created_by, tags, created_at, updated_at FROM configs
WHERE tags && $1::varchar[]
ORDER BY times_used DESC
LIMIT $2
`

type GetConfigsWithTagsParams struct {
	Column1 []string `json:"column_1"`
	Limit   int32    `json:"limit"`
}

func (q *Queries) GetConfigsWithTags(ctx context.Context, arg GetConfigsWithTagsParams) ([]Config, error) {
	rows, err := q.db.Query(ctx, getConfigsWithTags, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Config
	for rows.Next() {
		var i Config
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Strategy,
			&i.Volatility,
			&i.Drift,
			&i.StartingPrice,
			&i.CandleInterval,
			&i.Symbol,
			&i.MarketBehavior,
			&i.TrendStrength,
			&i.MeanReversionSpeed,
			&i.AdvancedParams,
			&i.IsDefault,
			&i.IsFavorite,
			&i.IsPublic,
			&i.TimesUsed,
			&i.LastUsedAt,
			&i.CreatedBy,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDefaultConfig = `-- name: GetDefaultConfig :one
SELECT id, name, description, strategy, volatility, drift, starting_price, candle_interval, symbol, market_behavior, trend_strength, mean_reversion_speed, advanced_params, is_default, is_favorite, is_public, times_used, last_used_at, created_by, tags, created_at, updated_at FROM configs
WHERE is_default = true
LIMIT 1
`

func (q *Queries) GetDefaultConfig(ctx context.Context) (Config, error) {
	row := q.db.QueryRow(ctx, getDefaultConfig)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Strategy,
		&i.Volatility,
		&i.Drift,
		&i.StartingPrice,
		&i.CandleInterval,
		&i.Symbol,
		&i.MarketBehavior,
		&i.TrendStrength,
		&i.MeanReversionSpeed,
		&i.AdvancedParams,
		&i.IsDefault,
		&i.IsFavorite,
		&i.IsPublic,
		&i.TimesUsed,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFavoriteConfigs = `-- name: GetFavoriteConfigs :many
SELECT id, name, description, strategy, volatility, drift, starting_price, candle_interval, symbol, market_behavior, trend_strength, mean_reversion_speed, advanced_params, is_default, is_favorite, is_public, times_used, last_used_at, created_by, tags, created_at, updated_at FROM configs
WHERE is_favorite = true
ORDER BY times_used DESC
`

func (q *Queries) GetFavoriteConfigs(ctx context.Context) ([]Config, error) {
	rows, err := q.db.Query(ctx, getFavoriteConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Config
	for rows.Next() {
		var i Config
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Strategy,
			&i.Volatility,
			&i.Drift,
			&i.StartingPrice,
			&i.CandleInterval,
			&i.Symbol,
			&i.MarketBehavior,
			&i.TrendStrength,
			&i.MeanReversionSpeed,
			&i.AdvancedParams,
			&i.IsDefault,
			&i.IsFavorite,
			&i.IsPublic,
			&i.TimesUsed,
			&i.LastUsedAt,
			&i.CreatedBy,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMarketBehaviorDistribution = `-- name: GetMarketBehaviorDistribution :many
SELECT 
    market_behavior,
    COUNT(*) as config_count
FROM configs
GROUP BY market_behavior
ORDER BY config_count DESC
`

type GetMarketBehaviorDistributionRow struct {
	MarketBehavior pgtype.Text `json:"market_behavior"`
	ConfigCount    int64       `json:"config_count"`
}

func (q *Queries) GetMarketBehaviorDistribution(ctx context.Context) ([]GetMarketBehaviorDistributionRow, error) {
	rows, err := q.db.Query(ctx, getMarketBehaviorDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMarketBehaviorDistributionRow
	for rows.Next() {
		var i GetMarketBehaviorDistributionRow
		if err := rows.Scan(&i.MarketBehavior, &i.ConfigCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPopularConfigs = `-- name: GetPopularConfigs :many
SELECT id, name, description, strategy, volatility, drift, starting_price, candle_interval, symbol, market_behavior, trend_strength, mean_reversion_speed, advanced_params, is_default, is_favorite, is_public, times_used, last_used_at, created_by, tags, created_at, updated_at FROM configs
WHERE times_used > 0
ORDER BY times_used DESC
LIMIT $1
`

func (q *Queries) GetPopularConfigs(ctx context.Context, limit int32) ([]Config, error) {
	rows, err := q.db.Query(ctx, getPopularConfigs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Config
	for rows.Next() {
		var i Config
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Strategy,
			&i.Volatility,
			&i.Drift,
			&i.StartingPrice,
			&i.CandleInterval,
			&i.Symbol,
			&i.MarketBehavior,
			&i.TrendStrength,
			&i.MeanReversionSpeed,
			&i.AdvancedParams,
			&i.IsDefault,
			&i.IsFavorite,
			&i.IsPublic,
			&i.TimesUsed,
			&i.LastUsedAt,
			&i.CreatedBy,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicConfigs = `-- name: GetPublicConfigs :many
SELECT id, name, description, strategy, volatility, drift, starting_price, candle_interval, symbol, market_behavior, trend_strength, mean_reversion_speed, advanced_params, is_default, is_favorite, is_public, times_used, last_used_at, created_by, tags, created_at, updated_at FROM configs
WHERE is_public = true
ORDER BY times_used DESC
LIMIT $1
`

func (q *Queries) GetPublicConfigs(ctx context.Context, limit int32) ([]Config, error) {
	rows, err := q.db.Query(ctx, getPublicConfigs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Config
	for rows.Next() {
		var i Config
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Strategy,
			&i.Volatility,
			&i.Drift,
			&i.StartingPrice,
			&i.CandleInterval,
			&i.Symbol,
			&i.MarketBehavior,
			&i.TrendStrength,
			&i.MeanReversionSpeed,
			&i.AdvancedParams,
			&i.IsDefault,
			&i.IsFavorite,
			&i.IsPublic,
			&i.TimesUsed,
			&i.LastUsedAt,
			&i.CreatedBy,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentlyUsedConfigs = `-- name: GetRecentlyUsedConfigs :many
SELECT id, name, description, strategy, volatility, drift, starting_price, candle_interval, symbol, market_behavior, trend_strength, mean_reversion_speed, advanced_params, is_default, is_favorite, is_public, times_used, last_used_at, created_by, tags, created_at, updated_at FROM configs
WHERE last_used_at IS NOT NULL
ORDER BY last_used_at DESC
LIMIT $1
`

func (q *Queries) GetRecentlyUsedConfigs(ctx context.Context, limit int32) ([]Config, error) {
	rows, err := q.db.Query(ctx, getRecentlyUsedConfigs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Config
	for rows.Next() {
		var i Config
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Strategy,
			&i.Volatility,
			&i.Drift,
			&i.StartingPrice,
			&i.CandleInterval,
			&i.Symbol,
			&i.MarketBehavior,
			&i.TrendStrength,
			&i.MeanReversionSpeed,
			&i.AdvancedParams,
			&i.IsDefault,
			&i.IsFavorite,
			&i.IsPublic,
			&i.TimesUsed,
			&i.LastUsedAt,
			&i.CreatedBy,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStrategyDistribution = `-- name: GetStrategyDistribution :many
SELECT 
    strategy,
    COUNT(*) as config_count,
    AVG(volatility) as avg_volatility,
    AVG(drift) as avg_drift
FROM configs
GROUP BY strategy
ORDER BY config_count DESC
`

type GetStrategyDistributionRow struct {
	Strategy      string  `json:"strategy"`
	ConfigCount   int64   `json:"config_count"`
	AvgVolatility float64 `json:"avg_volatility"`
	AvgDrift      float64 `json:"avg_drift"`
}

func (q *Queries) GetStrategyDistribution(ctx context.Context) ([]GetStrategyDistributionRow, error) {
	rows, err := q.db.Query(ctx, getStrategyDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStrategyDistributionRow
	for rows.Next() {
		var i GetStrategyDistributionRow
		if err := rows.Scan(
			&i.Strategy,
			&i.ConfigCount,
			&i.AvgVolatility,
			&i.AvgDrift,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementConfigUsage = `-- name: IncrementConfigUsage :exec
UPDATE configs
SET 
    times_used = times_used + 1,
    last_used_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) IncrementConfigUsage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementConfigUsage, id)
	return err
}

const listConfigs = `-- name: ListConfigs :many
SELECT id, name, description, strategy, volatility, drift, starting_price, candle_interval, symbol, market_behavior, trend_strength, mean_reversion_speed, advanced_params, is_default, is_favorite, is_public, times_used, last_used_at, created_by, tags, created_at, updated_at FROM configs
ORDER BY times_used DESC, created_at DESC
`

func (q *Queries) ListConfigs(ctx context.Context) ([]Config, error) {
	rows, err := q.db.Query(ctx, listConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Config
	for rows.Next() {
		var i Config
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Strategy,
			&i.Volatility,
			&i.Drift,
			&i.StartingPrice,
			&i.CandleInterval,
			&i.Symbol,
			&i.MarketBehavior,
			&i.TrendStrength,
			&i.MeanReversionSpeed,
			&i.AdvancedParams,
			&i.IsDefault,
			&i.IsFavorite,
			&i.IsPublic,
			&i.TimesUsed,
			&i.LastUsedAt,
			&i.CreatedBy,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfigsPaginated = `-- name: ListConfigsPaginated :many
SELECT id, name, description, strategy, volatility, drift, starting_price, candle_interval, symbol, market_behavior, trend_strength, mean_reversion_speed, advanced_params, is_default, is_favorite, is_public, times_used, last_used_at, created_by, tags, created_at, updated_at FROM configs
ORDER BY times_used DESC, created_at DESC
LIMIT $1
OFFSET $2
`

type ListConfigsPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListConfigsPaginated(ctx context.Context, arg ListConfigsPaginatedParams) ([]Config, error) {
	rows, err := q.db.Query(ctx, listConfigsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Config
	for rows.Next() {
		var i Config
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Strategy,
			&i.Volatility,
			&i.Drift,
			&i.StartingPrice,
			&i.CandleInterval,
			&i.Symbol,
			&i.MarketBehavior,
			&i.TrendStrength,
			&i.MeanReversionSpeed,
			&i.AdvancedParams,
			&i.IsDefault,
			&i.IsFavorite,
			&i.IsPublic,
			&i.TimesUsed,
			&i.LastUsedAt,
			&i.CreatedBy,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeConfigTag = `-- name: RemoveConfigTag :exec
UPDATE configs
SET 
    tags = array_remove(tags, $2),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type RemoveConfigTagParams struct {
	ID          int64       `json:"id"`
	ArrayRemove interface{} `json:"array_remove"`
}

func (q *Queries) RemoveConfigTag(ctx context.Context, arg RemoveConfigTagParams) error {
	_, err := q.db.Exec(ctx, removeConfigTag, arg.ID, arg.ArrayRemove)
	return err
}

const searchConfigsByName = `-- name: SearchConfigsByName :many
SELECT id, name, description, strategy, volatility, drift, starting_price, candle_interval, symbol, market_behavior, trend_strength, mean_reversion_speed, advanced_params, is_default, is_favorite, is_public, times_used, last_used_at, created_by, tags, created_at, updated_at FROM configs
WHERE name ILIKE '%' || $1 || '%'
ORDER BY times_used DESC
LIMIT $2
`

type SearchConfigsByNameParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) SearchConfigsByName(ctx context.Context, arg SearchConfigsByNameParams) ([]Config, error) {
	rows, err := q.db.Query(ctx, searchConfigsByName, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Config
	for rows.Next() {
		var i Config
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Strategy,
			&i.Volatility,
			&i.Drift,
			&i.StartingPrice,
			&i.CandleInterval,
			&i.Symbol,
			&i.MarketBehavior,
			&i.TrendStrength,
			&i.MeanReversionSpeed,
			&i.AdvancedParams,
			&i.IsDefault,
			&i.IsFavorite,
			&i.IsPublic,
			&i.TimesUsed,
			&i.LastUsedAt,
			&i.CreatedBy,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultConfig = `-- name: SetDefaultConfig :exec
UPDATE configs
SET is_default = (id = $1),
    updated_at = CURRENT_TIMESTAMP
`

func (q *Queries) SetDefaultConfig(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, setDefaultConfig, id)
	return err
}

const toggleConfigFavorite = `-- name: ToggleConfigFavorite :one
UPDATE configs
SET 
    is_favorite = NOT is_favorite,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING is_favorite
`

func (q *Queries) ToggleConfigFavorite(ctx context.Context, id int64) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, toggleConfigFavorite, id)
	var is_favorite pgtype.Bool
	err := row.Scan(&is_favorite)
	return is_favorite, err
}

const toggleConfigPublic = `-- name: ToggleConfigPublic :one
UPDATE configs
SET 
    is_public = NOT is_public,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING is_public
`

func (q *Queries) ToggleConfigPublic(ctx context.Context, id int64) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, toggleConfigPublic, id)
	var is_public pgtype.Bool
	err := row.Scan(&is_public)
	return is_public, err
}

const updateConfig = `-- name: UpdateConfig :one

UPDATE configs
SET 
    name = $2,
    description = $3,
    strategy = $4,
    volatility = $5,
    drift = $6,
    starting_price = $7,
    candle_interval = $8,
    symbol = $9,
    market_behavior = $10,
    trend_strength = $11,
    mean_reversion_speed = $12,
    advanced_params = $13,
    tags = $14,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, description, strategy, volatility, drift, starting_price, candle_interval, symbol, market_behavior, trend_strength, mean_reversion_speed, advanced_params, is_default, is_favorite, is_public, times_used, last_used_at, created_by, tags, created_at, updated_at
`

type UpdateConfigParams struct {
	ID                 int64          `json:"id"`
	Name               string         `json:"name"`
	Description        pgtype.Text    `json:"description"`
	Strategy           string         `json:"strategy"`
	Volatility         pgtype.Numeric `json:"volatility"`
	Drift              pgtype.Numeric `json:"drift"`
	StartingPrice      pgtype.Numeric `json:"starting_price"`
	CandleInterval     string         `json:"candle_interval"`
	Symbol             string         `json:"symbol"`
	MarketBehavior     pgtype.Text    `json:"market_behavior"`
	TrendStrength      pgtype.Numeric `json:"trend_strength"`
	MeanReversionSpeed pgtype.Numeric `json:"mean_reversion_speed"`
	AdvancedParams     []byte         `json:"advanced_params"`
	Tags               []string       `json:"tags"`
}

// =============================================================================
// UPDATE Operations
// =============================================================================
func (q *Queries) UpdateConfig(ctx context.Context, arg UpdateConfigParams) (Config, error) {
	row := q.db.QueryRow(ctx, updateConfig,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Strategy,
		arg.Volatility,
		arg.Drift,
		arg.StartingPrice,
		arg.CandleInterval,
		arg.Symbol,
		arg.MarketBehavior,
		arg.TrendStrength,
		arg.MeanReversionSpeed,
		arg.AdvancedParams,
		arg.Tags,
	)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Strategy,
		&i.Volatility,
		&i.Drift,
		&i.StartingPrice,
		&i.CandleInterval,
		&i.Symbol,
		&i.MarketBehavior,
		&i.TrendStrength,
		&i.MeanReversionSpeed,
		&i.AdvancedParams,
		&i.IsDefault,
		&i.IsFavorite,
		&i.IsPublic,
		&i.TimesUsed,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateConfigPartial = `-- name: UpdateConfigPartial :one
UPDATE configs
SET 
    name = COALESCE($1, name),
    description = COALESCE($2, description),
    volatility = COALESCE($3, volatility),
    drift = COALESCE($4, drift),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $5
RETURNING id, name, description, strategy, volatility, drift, starting_price, candle_interval, symbol, market_behavior, trend_strength, mean_reversion_speed, advanced_params, is_default, is_favorite, is_public, times_used, last_used_at, created_by, tags, created_at, updated_at
`

type UpdateConfigPartialParams struct {
	Name        pgtype.Text    `json:"name"`
	Description pgtype.Text    `json:"description"`
	Volatility  pgtype.Numeric `json:"volatility"`
	Drift       pgtype.Numeric `json:"drift"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateConfigPartial(ctx context.Context, arg UpdateConfigPartialParams) (Config, error) {
	row := q.db.QueryRow(ctx, updateConfigPartial,
		arg.Name,
		arg.Description,
		arg.Volatility,
		arg.Drift,
		arg.ID,
	)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Strategy,
		&i.Volatility,
		&i.Drift,
		&i.StartingPrice,
		&i.CandleInterval,
		&i.Symbol,
		&i.MarketBehavior,
		&i.TrendStrength,
		&i.MeanReversionSpeed,
		&i.AdvancedParams,
		&i.IsDefault,
		&i.IsFavorite,
		&i.IsPublic,
		&i.TimesUsed,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
