// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package repo

import (
	"context"
)

// iteratorForCreateCandleBatch implements pgx.CopyFromSource.
type iteratorForCreateCandleBatch struct {
	rows                 []CreateCandleBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCandleBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCandleBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Symbol,
		r.rows[0].Timeframe,
		r.rows[0].Timestamp,
		r.rows[0].Open,
		r.rows[0].High,
		r.rows[0].Low,
		r.rows[0].Close,
		r.rows[0].Volume,
	}, nil
}

func (r iteratorForCreateCandleBatch) Err() error {
	return nil
}

func (q *Queries) CreateCandleBatch(ctx context.Context, arg []CreateCandleBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"candles"}, []string{"symbol", "timeframe", "timestamp", "open", "high", "low", "close", "volume"}, &iteratorForCreateCandleBatch{rows: arg})
}

// iteratorForCreateIndicatorBatch implements pgx.CopyFromSource.
type iteratorForCreateIndicatorBatch struct {
	rows                 []CreateIndicatorBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateIndicatorBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateIndicatorBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].CandleID,
		r.rows[0].IndicatorType,
		r.rows[0].Value,
		r.rows[0].Period,
		r.rows[0].Signal,
	}, nil
}

func (r iteratorForCreateIndicatorBatch) Err() error {
	return nil
}

func (q *Queries) CreateIndicatorBatch(ctx context.Context, arg []CreateIndicatorBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"indicators"}, []string{"candle_id", "indicator_type", "value", "period", "signal"}, &iteratorForCreateIndicatorBatch{rows: arg})
}

// iteratorForCreateMetricBatch implements pgx.CopyFromSource.
type iteratorForCreateMetricBatch struct {
	rows                 []CreateMetricBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateMetricBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateMetricBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SessionID,
		r.rows[0].Timestamp,
		r.rows[0].CurrentPrice,
		r.rows[0].Volume,
		r.rows[0].Rsi14,
		r.rows[0].Signal,
	}, nil
}

func (r iteratorForCreateMetricBatch) Err() error {
	return nil
}

func (q *Queries) CreateMetricBatch(ctx context.Context, arg []CreateMetricBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"metrics"}, []string{"session_id", "timestamp", "current_price", "volume", "rsi_14", "signal"}, &iteratorForCreateMetricBatch{rows: arg})
}
