// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acknowledgeAllEvents = `-- name: AcknowledgeAllEvents :exec
UPDATE events
SET 
    is_acknowledged = true,
    acknowledged_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE session_id = $1
  AND is_acknowledged = false
`

func (q *Queries) AcknowledgeAllEvents(ctx context.Context, sessionID int64) error {
	_, err := q.db.Exec(ctx, acknowledgeAllEvents, sessionID)
	return err
}

const acknowledgeEvent = `-- name: AcknowledgeEvent :exec
UPDATE events
SET 
    is_acknowledged = true,
    acknowledged_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) AcknowledgeEvent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, acknowledgeEvent, id)
	return err
}

const addEventTag = `-- name: AddEventTag :exec
UPDATE events
SET 
    tags = array_append(tags, $2),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND NOT ($2 = ANY(tags))
`

type AddEventTagParams struct {
	ID          int64       `json:"id"`
	ArrayAppend interface{} `json:"array_append"`
}

func (q *Queries) AddEventTag(ctx context.Context, arg AddEventTagParams) error {
	_, err := q.db.Exec(ctx, addEventTag, arg.ID, arg.ArrayAppend)
	return err
}

const archiveOldEvents = `-- name: ArchiveOldEvents :execrows
UPDATE events
SET 
    status = 'archived',
    is_acknowledged = true,
    acknowledged_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE created_at < $1
  AND severity NOT IN ('critical', 'high')
  AND is_acknowledged = false
`

func (q *Queries) ArchiveOldEvents(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, archiveOldEvents, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const checkEventExists = `-- name: CheckEventExists :one

SELECT EXISTS(
    SELECT 1 FROM events
    WHERE id = $1
) AS exists
`

// =============================================================================
// UTILITY Operations
// =============================================================================
func (q *Queries) CheckEventExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, checkEventExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countEvents = `-- name: CountEvents :one

SELECT COUNT(*) FROM events
WHERE session_id = $1
`

// =============================================================================
// AGGREGATE Operations
// =============================================================================
func (q *Queries) CountEvents(ctx context.Context, sessionID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countEvents, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEventsBySeverity = `-- name: CountEventsBySeverity :one
SELECT COUNT(*) FROM events
WHERE session_id = $1
  AND severity = $2
`

type CountEventsBySeverityParams struct {
	SessionID int64       `json:"session_id"`
	Severity  pgtype.Text `json:"severity"`
}

func (q *Queries) CountEventsBySeverity(ctx context.Context, arg CountEventsBySeverityParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEventsBySeverity, arg.SessionID, arg.Severity)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEventsByType = `-- name: CountEventsByType :one
SELECT COUNT(*) FROM events
WHERE session_id = $1
  AND event_type = $2
`

type CountEventsByTypeParams struct {
	SessionID int64  `json:"session_id"`
	EventType string `json:"event_type"`
}

func (q *Queries) CountEventsByType(ctx context.Context, arg CountEventsByTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEventsByType, arg.SessionID, arg.EventType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnacknowledgedEvents = `-- name: CountUnacknowledgedEvents :one
SELECT COUNT(*) FROM events
WHERE session_id = $1
  AND is_acknowledged = false
`

func (q *Queries) CountUnacknowledgedEvents(ctx context.Context, sessionID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUnacknowledgedEvents, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one


INSERT INTO events (
    session_id,
    candle_id,
    event_type,
    event_category,
    title,
    description,
    timestamp,
    duration_seconds,
    severity,
    impact_score,
    price_at_event,
    price_before,
    price_after,
    price_change_percent,
    volume_at_event,
    volume_spike_ratio,
    triggered_by,
    trigger_conditions,
    tags,
    indicators_at_event,
    additional_data,
    is_user_marked,
    user_notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
    $21, $22, $23
)
RETURNING id, session_id, candle_id, event_type, event_category, title, description, timestamp, duration_seconds, severity, impact_score, price_at_event, price_before, price_after, price_change_percent, volume_at_event, volume_spike_ratio, triggered_by, trigger_conditions, tags, indicators_at_event, additional_data, is_user_marked, user_notes, is_acknowledged, acknowledged_at, status, created_at, updated_at
`

type CreateEventParams struct {
	SessionID          int64          `json:"session_id"`
	CandleID           pgtype.Int8    `json:"candle_id"`
	EventType          string         `json:"event_type"`
	EventCategory      pgtype.Text    `json:"event_category"`
	Title              string         `json:"title"`
	Description        pgtype.Text    `json:"description"`
	Timestamp          int64          `json:"timestamp"`
	DurationSeconds    pgtype.Int4    `json:"duration_seconds"`
	Severity           pgtype.Text    `json:"severity"`
	ImpactScore        pgtype.Numeric `json:"impact_score"`
	PriceAtEvent       pgtype.Numeric `json:"price_at_event"`
	PriceBefore        pgtype.Numeric `json:"price_before"`
	PriceAfter         pgtype.Numeric `json:"price_after"`
	PriceChangePercent pgtype.Numeric `json:"price_change_percent"`
	VolumeAtEvent      pgtype.Numeric `json:"volume_at_event"`
	VolumeSpikeRatio   pgtype.Numeric `json:"volume_spike_ratio"`
	TriggeredBy        pgtype.Text    `json:"triggered_by"`
	TriggerConditions  []byte         `json:"trigger_conditions"`
	Tags               []string       `json:"tags"`
	IndicatorsAtEvent  []byte         `json:"indicators_at_event"`
	AdditionalData     []byte         `json:"additional_data"`
	IsUserMarked       pgtype.Bool    `json:"is_user_marked"`
	UserNotes          pgtype.Text    `json:"user_notes"`
}

// Events Queries
// CRUD operations and queries for market events and alerts
// =============================================================================
// CREATE Operations
// =============================================================================
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.SessionID,
		arg.CandleID,
		arg.EventType,
		arg.EventCategory,
		arg.Title,
		arg.Description,
		arg.Timestamp,
		arg.DurationSeconds,
		arg.Severity,
		arg.ImpactScore,
		arg.PriceAtEvent,
		arg.PriceBefore,
		arg.PriceAfter,
		arg.PriceChangePercent,
		arg.VolumeAtEvent,
		arg.VolumeSpikeRatio,
		arg.TriggeredBy,
		arg.TriggerConditions,
		arg.Tags,
		arg.IndicatorsAtEvent,
		arg.AdditionalData,
		arg.IsUserMarked,
		arg.UserNotes,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CandleID,
		&i.EventType,
		&i.EventCategory,
		&i.Title,
		&i.Description,
		&i.Timestamp,
		&i.DurationSeconds,
		&i.Severity,
		&i.ImpactScore,
		&i.PriceAtEvent,
		&i.PriceBefore,
		&i.PriceAfter,
		&i.PriceChangePercent,
		&i.VolumeAtEvent,
		&i.VolumeSpikeRatio,
		&i.TriggeredBy,
		&i.TriggerConditions,
		&i.Tags,
		&i.IndicatorsAtEvent,
		&i.AdditionalData,
		&i.IsUserMarked,
		&i.UserNotes,
		&i.IsAcknowledged,
		&i.AcknowledgedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEventSimple = `-- name: CreateEventSimple :one
INSERT INTO events (
    session_id,
    event_type,
    event_category,
    title,
    timestamp,
    severity,
    price_at_event
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, session_id, candle_id, event_type, event_category, title, description, timestamp, duration_seconds, severity, impact_score, price_at_event, price_before, price_after, price_change_percent, volume_at_event, volume_spike_ratio, triggered_by, trigger_conditions, tags, indicators_at_event, additional_data, is_user_marked, user_notes, is_acknowledged, acknowledged_at, status, created_at, updated_at
`

type CreateEventSimpleParams struct {
	SessionID     int64          `json:"session_id"`
	EventType     string         `json:"event_type"`
	EventCategory pgtype.Text    `json:"event_category"`
	Title         string         `json:"title"`
	Timestamp     int64          `json:"timestamp"`
	Severity      pgtype.Text    `json:"severity"`
	PriceAtEvent  pgtype.Numeric `json:"price_at_event"`
}

func (q *Queries) CreateEventSimple(ctx context.Context, arg CreateEventSimpleParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEventSimple,
		arg.SessionID,
		arg.EventType,
		arg.EventCategory,
		arg.Title,
		arg.Timestamp,
		arg.Severity,
		arg.PriceAtEvent,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CandleID,
		&i.EventType,
		&i.EventCategory,
		&i.Title,
		&i.Description,
		&i.Timestamp,
		&i.DurationSeconds,
		&i.Severity,
		&i.ImpactScore,
		&i.PriceAtEvent,
		&i.PriceBefore,
		&i.PriceAfter,
		&i.PriceChangePercent,
		&i.VolumeAtEvent,
		&i.VolumeSpikeRatio,
		&i.TriggeredBy,
		&i.TriggerConditions,
		&i.Tags,
		&i.IndicatorsAtEvent,
		&i.AdditionalData,
		&i.IsUserMarked,
		&i.UserNotes,
		&i.IsAcknowledged,
		&i.AcknowledgedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArchivedEvents = `-- name: DeleteArchivedEvents :exec
DELETE FROM events
WHERE status = 'archived'
  AND created_at < $1
`

func (q *Queries) DeleteArchivedEvents(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteArchivedEvents, createdAt)
	return err
}

const deleteDismissedEvents = `-- name: DeleteDismissedEvents :exec
DELETE FROM events
WHERE status = 'dismissed'
  AND created_at < $1
`

func (q *Queries) DeleteDismissedEvents(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteDismissedEvents, createdAt)
	return err
}

const deleteEvent = `-- name: DeleteEvent :exec

DELETE FROM events
WHERE id = $1
`

// =============================================================================
// DELETE Operations
// =============================================================================
func (q *Queries) DeleteEvent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const deleteEventsBySession = `-- name: DeleteEventsBySession :exec
DELETE FROM events
WHERE session_id = $1
`

func (q *Queries) DeleteEventsBySession(ctx context.Context, sessionID int64) error {
	_, err := q.db.Exec(ctx, deleteEventsBySession, sessionID)
	return err
}

const dismissEvent = `-- name: DismissEvent :exec
UPDATE events
SET 
    status = 'dismissed',
    is_acknowledged = true,
    acknowledged_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) DismissEvent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, dismissEvent, id)
	return err
}

const getActiveEvents = `-- name: GetActiveEvents :many
SELECT id, session_id, candle_id, event_type, event_category, title, description, timestamp, duration_seconds, severity, impact_score, price_at_event, price_before, price_after, price_change_percent, volume_at_event, volume_spike_ratio, triggered_by, trigger_conditions, tags, indicators_at_event, additional_data, is_user_marked, user_notes, is_acknowledged, acknowledged_at, status, created_at, updated_at FROM events
WHERE session_id = $1
  AND status = 'active'
ORDER BY timestamp DESC
`

func (q *Queries) GetActiveEvents(ctx context.Context, sessionID int64) ([]Event, error) {
	rows, err := q.db.Query(ctx, getActiveEvents, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CandleID,
			&i.EventType,
			&i.EventCategory,
			&i.Title,
			&i.Description,
			&i.Timestamp,
			&i.DurationSeconds,
			&i.Severity,
			&i.ImpactScore,
			&i.PriceAtEvent,
			&i.PriceBefore,
			&i.PriceAfter,
			&i.PriceChangePercent,
			&i.VolumeAtEvent,
			&i.VolumeSpikeRatio,
			&i.TriggeredBy,
			&i.TriggerConditions,
			&i.Tags,
			&i.IndicatorsAtEvent,
			&i.AdditionalData,
			&i.IsUserMarked,
			&i.UserNotes,
			&i.IsAcknowledged,
			&i.AcknowledgedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBreakoutEvents = `-- name: GetBreakoutEvents :many
SELECT id, session_id, candle_id, event_type, event_category, title, description, timestamp, duration_seconds, severity, impact_score, price_at_event, price_before, price_after, price_change_percent, volume_at_event, volume_spike_ratio, triggered_by, trigger_conditions, tags, indicators_at_event, additional_data, is_user_marked, user_notes, is_acknowledged, acknowledged_at, status, created_at, updated_at FROM events
WHERE session_id = $1
  AND event_type IN ('breakout', 'breakdown')
ORDER BY timestamp DESC
LIMIT $2
`

type GetBreakoutEventsParams struct {
	SessionID int64 `json:"session_id"`
	Limit     int32 `json:"limit"`
}

func (q *Queries) GetBreakoutEvents(ctx context.Context, arg GetBreakoutEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getBreakoutEvents, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CandleID,
			&i.EventType,
			&i.EventCategory,
			&i.Title,
			&i.Description,
			&i.Timestamp,
			&i.DurationSeconds,
			&i.Severity,
			&i.ImpactScore,
			&i.PriceAtEvent,
			&i.PriceBefore,
			&i.PriceAfter,
			&i.PriceChangePercent,
			&i.VolumeAtEvent,
			&i.VolumeSpikeRatio,
			&i.TriggeredBy,
			&i.TriggerConditions,
			&i.Tags,
			&i.IndicatorsAtEvent,
			&i.AdditionalData,
			&i.IsUserMarked,
			&i.UserNotes,
			&i.IsAcknowledged,
			&i.AcknowledgedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCriticalEvents = `-- name: GetCriticalEvents :many
SELECT id, session_id, candle_id, event_type, event_category, title, description, timestamp, duration_seconds, severity, impact_score, price_at_event, price_before, price_after, price_change_percent, volume_at_event, volume_spike_ratio, triggered_by, trigger_conditions, tags, indicators_at_event, additional_data, is_user_marked, user_notes, is_acknowledged, acknowledged_at, status, created_at, updated_at FROM events
WHERE session_id = $1
  AND severity IN ('critical', 'high')
  AND status = 'active'
ORDER BY severity DESC, timestamp DESC
`

func (q *Queries) GetCriticalEvents(ctx context.Context, sessionID int64) ([]Event, error) {
	rows, err := q.db.Query(ctx, getCriticalEvents, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CandleID,
			&i.EventType,
			&i.EventCategory,
			&i.Title,
			&i.Description,
			&i.Timestamp,
			&i.DurationSeconds,
			&i.Severity,
			&i.ImpactScore,
			&i.PriceAtEvent,
			&i.PriceBefore,
			&i.PriceAfter,
			&i.PriceChangePercent,
			&i.VolumeAtEvent,
			&i.VolumeSpikeRatio,
			&i.TriggeredBy,
			&i.TriggerConditions,
			&i.Tags,
			&i.IndicatorsAtEvent,
			&i.AdditionalData,
			&i.IsUserMarked,
			&i.UserNotes,
			&i.IsAcknowledged,
			&i.AcknowledgedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCriticalEventsNeedingAction = `-- name: GetCriticalEventsNeedingAction :many
SELECT id, session_id, candle_id, event_type, event_category, title, description, timestamp, duration_seconds, severity, impact_score, price_at_event, price_before, price_after, price_change_percent, volume_at_event, volume_spike_ratio, triggered_by, trigger_conditions, tags, indicators_at_event, additional_data, is_user_marked, user_notes, is_acknowledged, acknowledged_at, status, created_at, updated_at FROM events
WHERE session_id = $1
  AND severity = 'critical'
  AND status = 'active'
  AND is_acknowledged = false
ORDER BY timestamp DESC
`

func (q *Queries) GetCriticalEventsNeedingAction(ctx context.Context, sessionID int64) ([]Event, error) {
	rows, err := q.db.Query(ctx, getCriticalEventsNeedingAction, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CandleID,
			&i.EventType,
			&i.EventCategory,
			&i.Title,
			&i.Description,
			&i.Timestamp,
			&i.DurationSeconds,
			&i.Severity,
			&i.ImpactScore,
			&i.PriceAtEvent,
			&i.PriceBefore,
			&i.PriceAfter,
			&i.PriceChangePercent,
			&i.VolumeAtEvent,
			&i.VolumeSpikeRatio,
			&i.TriggeredBy,
			&i.TriggerConditions,
			&i.Tags,
			&i.IndicatorsAtEvent,
			&i.AdditionalData,
			&i.IsUserMarked,
			&i.UserNotes,
			&i.IsAcknowledged,
			&i.AcknowledgedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctEventCategories = `-- name: GetDistinctEventCategories :many
SELECT DISTINCT event_category
FROM events
ORDER BY event_category
`

func (q *Queries) GetDistinctEventCategories(ctx context.Context) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, getDistinctEventCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var event_category pgtype.Text
		if err := rows.Scan(&event_category); err != nil {
			return nil, err
		}
		items = append(items, event_category)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctEventTypes = `-- name: GetDistinctEventTypes :many
SELECT DISTINCT event_type
FROM events
WHERE session_id = $1
ORDER BY event_type
`

func (q *Queries) GetDistinctEventTypes(ctx context.Context, sessionID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, getDistinctEventTypes, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var event_type string
		if err := rows.Scan(&event_type); err != nil {
			return nil, err
		}
		items = append(items, event_type)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventByID = `-- name: GetEventByID :one

SELECT id, session_id, candle_id, event_type, event_category, title, description, timestamp, duration_seconds, severity, impact_score, price_at_event, price_before, price_after, price_change_percent, volume_at_event, volume_spike_ratio, triggered_by, trigger_conditions, tags, indicators_at_event, additional_data, is_user_marked, user_notes, is_acknowledged, acknowledged_at, status, created_at, updated_at FROM events
WHERE id = $1
`

// =============================================================================
// READ Operations
// =============================================================================
func (q *Queries) GetEventByID(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CandleID,
		&i.EventType,
		&i.EventCategory,
		&i.Title,
		&i.Description,
		&i.Timestamp,
		&i.DurationSeconds,
		&i.Severity,
		&i.ImpactScore,
		&i.PriceAtEvent,
		&i.PriceBefore,
		&i.PriceAfter,
		&i.PriceChangePercent,
		&i.VolumeAtEvent,
		&i.VolumeSpikeRatio,
		&i.TriggeredBy,
		&i.TriggerConditions,
		&i.Tags,
		&i.IndicatorsAtEvent,
		&i.AdditionalData,
		&i.IsUserMarked,
		&i.UserNotes,
		&i.IsAcknowledged,
		&i.AcknowledgedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventCategoryDistribution = `-- name: GetEventCategoryDistribution :many
SELECT 
    event_category,
    COUNT(*) as event_count,
    COUNT(*) FILTER (WHERE severity IN ('critical', 'high')) as high_severity_count
FROM events
WHERE session_id = $1
GROUP BY event_category
ORDER BY event_count DESC
`

type GetEventCategoryDistributionRow struct {
	EventCategory     pgtype.Text `json:"event_category"`
	EventCount        int64       `json:"event_count"`
	HighSeverityCount int64       `json:"high_severity_count"`
}

func (q *Queries) GetEventCategoryDistribution(ctx context.Context, sessionID int64) ([]GetEventCategoryDistributionRow, error) {
	rows, err := q.db.Query(ctx, getEventCategoryDistribution, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventCategoryDistributionRow
	for rows.Next() {
		var i GetEventCategoryDistributionRow
		if err := rows.Scan(&i.EventCategory, &i.EventCount, &i.HighSeverityCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventCorrelations = `-- name: GetEventCorrelations :many
SELECT 
    e1.event_type as event_type_1,
    e2.event_type as event_type_2,
    COUNT(*) as correlation_count,
    AVG(e2.timestamp - e1.timestamp) as avg_time_diff
FROM events e1
JOIN events e2 ON e2.session_id = e1.session_id
    AND e2.timestamp > e1.timestamp
    AND e2.timestamp <= e1.timestamp + $2
WHERE e1.session_id = $1
  AND e1.event_type != e2.event_type
GROUP BY e1.event_type, e2.event_type
HAVING COUNT(*) >= $3
ORDER BY correlation_count DESC
`

type GetEventCorrelationsParams struct {
	SessionID int64       `json:"session_id"`
	Timestamp int64       `json:"timestamp"`
	Column3   interface{} `json:"column_3"`
}

type GetEventCorrelationsRow struct {
	EventType1       string  `json:"event_type_1"`
	EventType2       string  `json:"event_type_2"`
	CorrelationCount int64   `json:"correlation_count"`
	AvgTimeDiff      float64 `json:"avg_time_diff"`
}

func (q *Queries) GetEventCorrelations(ctx context.Context, arg GetEventCorrelationsParams) ([]GetEventCorrelationsRow, error) {
	rows, err := q.db.Query(ctx, getEventCorrelations, arg.SessionID, arg.Timestamp, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventCorrelationsRow
	for rows.Next() {
		var i GetEventCorrelationsRow
		if err := rows.Scan(
			&i.EventType1,
			&i.EventType2,
			&i.CorrelationCount,
			&i.AvgTimeDiff,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventDensity = `-- name: GetEventDensity :many
SELECT 
    (timestamp / $2) * $2 as time_bucket,
    COUNT(*) as event_count
FROM events
WHERE session_id = $1
GROUP BY time_bucket
ORDER BY time_bucket ASC
`

type GetEventDensityParams struct {
	SessionID int64 `json:"session_id"`
	Timestamp int64 `json:"timestamp"`
}

type GetEventDensityRow struct {
	TimeBucket int32 `json:"time_bucket"`
	EventCount int64 `json:"event_count"`
}

func (q *Queries) GetEventDensity(ctx context.Context, arg GetEventDensityParams) ([]GetEventDensityRow, error) {
	rows, err := q.db.Query(ctx, getEventDensity, arg.SessionID, arg.Timestamp)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventDensityRow
	for rows.Next() {
		var i GetEventDensityRow
		if err := rows.Scan(&i.TimeBucket, &i.EventCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventFrequencyByHour = `-- name: GetEventFrequencyByHour :many
SELECT 
    EXTRACT(HOUR FROM TO_TIMESTAMP(timestamp)) as hour,
    COUNT(*) as event_count
FROM events
WHERE session_id = $1
GROUP BY hour
ORDER BY hour
`

type GetEventFrequencyByHourRow struct {
	Hour       pgtype.Numeric `json:"hour"`
	EventCount int64          `json:"event_count"`
}

func (q *Queries) GetEventFrequencyByHour(ctx context.Context, sessionID int64) ([]GetEventFrequencyByHourRow, error) {
	rows, err := q.db.Query(ctx, getEventFrequencyByHour, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventFrequencyByHourRow
	for rows.Next() {
		var i GetEventFrequencyByHourRow
		if err := rows.Scan(&i.Hour, &i.EventCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventTimeline = `-- name: GetEventTimeline :many

SELECT 
    timestamp,
    event_type,
    severity,
    title,
    price_at_event
FROM events
WHERE session_id = $1
  AND timestamp >= $2
  AND timestamp <= $3
ORDER BY timestamp ASC
`

type GetEventTimelineParams struct {
	SessionID   int64 `json:"session_id"`
	Timestamp   int64 `json:"timestamp"`
	Timestamp_2 int64 `json:"timestamp_2"`
}

type GetEventTimelineRow struct {
	Timestamp    int64          `json:"timestamp"`
	EventType    string         `json:"event_type"`
	Severity     pgtype.Text    `json:"severity"`
	Title        string         `json:"title"`
	PriceAtEvent pgtype.Numeric `json:"price_at_event"`
}

// =============================================================================
// TIME SERIES Operations
// =============================================================================
func (q *Queries) GetEventTimeline(ctx context.Context, arg GetEventTimelineParams) ([]GetEventTimelineRow, error) {
	rows, err := q.db.Query(ctx, getEventTimeline, arg.SessionID, arg.Timestamp, arg.Timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventTimelineRow
	for rows.Next() {
		var i GetEventTimelineRow
		if err := rows.Scan(
			&i.Timestamp,
			&i.EventType,
			&i.Severity,
			&i.Title,
			&i.PriceAtEvent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventTypeDistribution = `-- name: GetEventTypeDistribution :many
SELECT 
    event_type,
    COUNT(*) as event_count,
    AVG(impact_score) as avg_impact
FROM events
WHERE session_id = $1
GROUP BY event_type
ORDER BY event_count DESC
`

type GetEventTypeDistributionRow struct {
	EventType  string  `json:"event_type"`
	EventCount int64   `json:"event_count"`
	AvgImpact  float64 `json:"avg_impact"`
}

func (q *Queries) GetEventTypeDistribution(ctx context.Context, sessionID int64) ([]GetEventTypeDistributionRow, error) {
	rows, err := q.db.Query(ctx, getEventTypeDistribution, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventTypeDistributionRow
	for rows.Next() {
		var i GetEventTypeDistributionRow
		if err := rows.Scan(&i.EventType, &i.EventCount, &i.AvgImpact); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsByCandle = `-- name: GetEventsByCandle :many
SELECT id, session_id, candle_id, event_type, event_category, title, description, timestamp, duration_seconds, severity, impact_score, price_at_event, price_before, price_after, price_change_percent, volume_at_event, volume_spike_ratio, triggered_by, trigger_conditions, tags, indicators_at_event, additional_data, is_user_marked, user_notes, is_acknowledged, acknowledged_at, status, created_at, updated_at FROM events
WHERE candle_id = $1
ORDER BY timestamp DESC
`

func (q *Queries) GetEventsByCandle(ctx context.Context, candleID pgtype.Int8) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsByCandle, candleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CandleID,
			&i.EventType,
			&i.EventCategory,
			&i.Title,
			&i.Description,
			&i.Timestamp,
			&i.DurationSeconds,
			&i.Severity,
			&i.ImpactScore,
			&i.PriceAtEvent,
			&i.PriceBefore,
			&i.PriceAfter,
			&i.PriceChangePercent,
			&i.VolumeAtEvent,
			&i.VolumeSpikeRatio,
			&i.TriggeredBy,
			&i.TriggerConditions,
			&i.Tags,
			&i.IndicatorsAtEvent,
			&i.AdditionalData,
			&i.IsUserMarked,
			&i.UserNotes,
			&i.IsAcknowledged,
			&i.AcknowledgedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsByCategory = `-- name: GetEventsByCategory :many
SELECT id, session_id, candle_id, event_type, event_category, title, description, timestamp, duration_seconds, severity, impact_score, price_at_event, price_before, price_after, price_change_percent, volume_at_event, volume_spike_ratio, triggered_by, trigger_conditions, tags, indicators_at_event, additional_data, is_user_marked, user_notes, is_acknowledged, acknowledged_at, status, created_at, updated_at FROM events
WHERE session_id = $1
  AND event_category = $2
ORDER BY timestamp DESC
LIMIT $3
`

type GetEventsByCategoryParams struct {
	SessionID     int64       `json:"session_id"`
	EventCategory pgtype.Text `json:"event_category"`
	Limit         int32       `json:"limit"`
}

func (q *Queries) GetEventsByCategory(ctx context.Context, arg GetEventsByCategoryParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsByCategory, arg.SessionID, arg.EventCategory, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CandleID,
			&i.EventType,
			&i.EventCategory,
			&i.Title,
			&i.Description,
			&i.Timestamp,
			&i.DurationSeconds,
			&i.Severity,
			&i.ImpactScore,
			&i.PriceAtEvent,
			&i.PriceBefore,
			&i.PriceAfter,
			&i.PriceChangePercent,
			&i.VolumeAtEvent,
			&i.VolumeSpikeRatio,
			&i.TriggeredBy,
			&i.TriggerConditions,
			&i.Tags,
			&i.IndicatorsAtEvent,
			&i.AdditionalData,
			&i.IsUserMarked,
			&i.UserNotes,
			&i.IsAcknowledged,
			&i.AcknowledgedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsBySession = `-- name: GetEventsBySession :many
SELECT id, session_id, candle_id, event_type, event_category, title, description, timestamp, duration_seconds, severity, impact_score, price_at_event, price_before, price_after, price_change_percent, volume_at_event, volume_spike_ratio, triggered_by, trigger_conditions, tags, indicators_at_event, additional_data, is_user_marked, user_notes, is_acknowledged, acknowledged_at, status, created_at, updated_at FROM events
WHERE session_id = $1
ORDER BY timestamp DESC
`

func (q *Queries) GetEventsBySession(ctx context.Context, sessionID int64) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CandleID,
			&i.EventType,
			&i.EventCategory,
			&i.Title,
			&i.Description,
			&i.Timestamp,
			&i.DurationSeconds,
			&i.Severity,
			&i.ImpactScore,
			&i.PriceAtEvent,
			&i.PriceBefore,
			&i.PriceAfter,
			&i.PriceChangePercent,
			&i.VolumeAtEvent,
			&i.VolumeSpikeRatio,
			&i.TriggeredBy,
			&i.TriggerConditions,
			&i.Tags,
			&i.IndicatorsAtEvent,
			&i.AdditionalData,
			&i.IsUserMarked,
			&i.UserNotes,
			&i.IsAcknowledged,
			&i.AcknowledgedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsBySessionPaginated = `-- name: GetEventsBySessionPaginated :many
SELECT id, session_id, candle_id, event_type, event_category, title, description, timestamp, duration_seconds, severity, impact_score, price_at_event, price_before, price_after, price_change_percent, volume_at_event, volume_spike_ratio, triggered_by, trigger_conditions, tags, indicators_at_event, additional_data, is_user_marked, user_notes, is_acknowledged, acknowledged_at, status, created_at, updated_at FROM events
WHERE session_id = $1
ORDER BY timestamp DESC
LIMIT $2
OFFSET $3
`

type GetEventsBySessionPaginatedParams struct {
	SessionID int64 `json:"session_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) GetEventsBySessionPaginated(ctx context.Context, arg GetEventsBySessionPaginatedParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsBySessionPaginated, arg.SessionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CandleID,
			&i.EventType,
			&i.EventCategory,
			&i.Title,
			&i.Description,
			&i.Timestamp,
			&i.DurationSeconds,
			&i.Severity,
			&i.ImpactScore,
			&i.PriceAtEvent,
			&i.PriceBefore,
			&i.PriceAfter,
			&i.PriceChangePercent,
			&i.VolumeAtEvent,
			&i.VolumeSpikeRatio,
			&i.TriggeredBy,
			&i.TriggerConditions,
			&i.Tags,
			&i.IndicatorsAtEvent,
			&i.AdditionalData,
			&i.IsUserMarked,
			&i.UserNotes,
			&i.IsAcknowledged,
			&i.AcknowledgedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsBySeverity = `-- name: GetEventsBySeverity :many
SELECT id, session_id, candle_id, event_type, event_category, title, description, timestamp, duration_seconds, severity, impact_score, price_at_event, price_before, price_after, price_change_percent, volume_at_event, volume_spike_ratio, triggered_by, trigger_conditions, tags, indicators_at_event, additional_data, is_user_marked, user_notes, is_acknowledged, acknowledged_at, status, created_at, updated_at FROM events
WHERE session_id = $1
  AND severity = $2
ORDER BY timestamp DESC
LIMIT $3
`

type GetEventsBySeverityParams struct {
	SessionID int64       `json:"session_id"`
	Severity  pgtype.Text `json:"severity"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) GetEventsBySeverity(ctx context.Context, arg GetEventsBySeverityParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsBySeverity, arg.SessionID, arg.Severity, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CandleID,
			&i.EventType,
			&i.EventCategory,
			&i.Title,
			&i.Description,
			&i.Timestamp,
			&i.DurationSeconds,
			&i.Severity,
			&i.ImpactScore,
			&i.PriceAtEvent,
			&i.PriceBefore,
			&i.PriceAfter,
			&i.PriceChangePercent,
			&i.VolumeAtEvent,
			&i.VolumeSpikeRatio,
			&i.TriggeredBy,
			&i.TriggerConditions,
			&i.Tags,
			&i.IndicatorsAtEvent,
			&i.AdditionalData,
			&i.IsUserMarked,
			&i.UserNotes,
			&i.IsAcknowledged,
			&i.AcknowledgedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsByType = `-- name: GetEventsByType :many
SELECT id, session_id, candle_id, event_type, event_category, title, description, timestamp, duration_seconds, severity, impact_score, price_at_event, price_before, price_after, price_change_percent, volume_at_event, volume_spike_ratio, triggered_by, trigger_conditions, tags, indicators_at_event, additional_data, is_user_marked, user_notes, is_acknowledged, acknowledged_at, status, created_at, updated_at FROM events
WHERE session_id = $1
  AND event_type = $2
ORDER BY timestamp DESC
LIMIT $3
`

type GetEventsByTypeParams struct {
	SessionID int64  `json:"session_id"`
	EventType string `json:"event_type"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) GetEventsByType(ctx context.Context, arg GetEventsByTypeParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsByType, arg.SessionID, arg.EventType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CandleID,
			&i.EventType,
			&i.EventCategory,
			&i.Title,
			&i.Description,
			&i.Timestamp,
			&i.DurationSeconds,
			&i.Severity,
			&i.ImpactScore,
			&i.PriceAtEvent,
			&i.PriceBefore,
			&i.PriceAfter,
			&i.PriceChangePercent,
			&i.VolumeAtEvent,
			&i.VolumeSpikeRatio,
			&i.TriggeredBy,
			&i.TriggerConditions,
			&i.Tags,
			&i.IndicatorsAtEvent,
			&i.AdditionalData,
			&i.IsUserMarked,
			&i.UserNotes,
			&i.IsAcknowledged,
			&i.AcknowledgedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsCausingDrawdown = `-- name: GetEventsCausingDrawdown :many
SELECT id, session_id, candle_id, event_type, event_category, title, description, timestamp, duration_seconds, severity, impact_score, price_at_event, price_before, price_after, price_change_percent, volume_at_event, volume_spike_ratio, triggered_by, trigger_conditions, tags, indicators_at_event, additional_data, is_user_marked, user_notes, is_acknowledged, acknowledged_at, status, created_at, updated_at FROM events
WHERE session_id = $1
  AND price_change_percent < 0
  AND ABS(price_change_percent) >= $2
ORDER BY price_change_percent ASC
LIMIT $3
`

type GetEventsCausingDrawdownParams struct {
	SessionID          int64          `json:"session_id"`
	PriceChangePercent pgtype.Numeric `json:"price_change_percent"`
	Limit              int32          `json:"limit"`
}

func (q *Queries) GetEventsCausingDrawdown(ctx context.Context, arg GetEventsCausingDrawdownParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsCausingDrawdown, arg.SessionID, arg.PriceChangePercent, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CandleID,
			&i.EventType,
			&i.EventCategory,
			&i.Title,
			&i.Description,
			&i.Timestamp,
			&i.DurationSeconds,
			&i.Severity,
			&i.ImpactScore,
			&i.PriceAtEvent,
			&i.PriceBefore,
			&i.PriceAfter,
			&i.PriceChangePercent,
			&i.VolumeAtEvent,
			&i.VolumeSpikeRatio,
			&i.TriggeredBy,
			&i.TriggerConditions,
			&i.Tags,
			&i.IndicatorsAtEvent,
			&i.AdditionalData,
			&i.IsUserMarked,
			&i.UserNotes,
			&i.IsAcknowledged,
			&i.AcknowledgedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsInRange = `-- name: GetEventsInRange :many
SELECT id, session_id, candle_id, event_type, event_category, title, description, timestamp, duration_seconds, severity, impact_score, price_at_event, price_before, price_after, price_change_percent, volume_at_event, volume_spike_ratio, triggered_by, trigger_conditions, tags, indicators_at_event, additional_data, is_user_marked, user_notes, is_acknowledged, acknowledged_at, status, created_at, updated_at FROM events
WHERE session_id = $1
  AND timestamp >= $2
  AND timestamp <= $3
ORDER BY timestamp ASC
`

type GetEventsInRangeParams struct {
	SessionID   int64 `json:"session_id"`
	Timestamp   int64 `json:"timestamp"`
	Timestamp_2 int64 `json:"timestamp_2"`
}

func (q *Queries) GetEventsInRange(ctx context.Context, arg GetEventsInRangeParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsInRange, arg.SessionID, arg.Timestamp, arg.Timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CandleID,
			&i.EventType,
			&i.EventCategory,
			&i.Title,
			&i.Description,
			&i.Timestamp,
			&i.DurationSeconds,
			&i.Severity,
			&i.ImpactScore,
			&i.PriceAtEvent,
			&i.PriceBefore,
			&i.PriceAfter,
			&i.PriceChangePercent,
			&i.VolumeAtEvent,
			&i.VolumeSpikeRatio,
			&i.TriggeredBy,
			&i.TriggerConditions,
			&i.Tags,
			&i.IndicatorsAtEvent,
			&i.AdditionalData,
			&i.IsUserMarked,
			&i.UserNotes,
			&i.IsAcknowledged,
			&i.AcknowledgedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsNearTimestamp = `-- name: GetEventsNearTimestamp :many
SELECT id, session_id, candle_id, event_type, event_category, title, description, timestamp, duration_seconds, severity, impact_score, price_at_event, price_before, price_after, price_change_percent, volume_at_event, volume_spike_ratio, triggered_by, trigger_conditions, tags, indicators_at_event, additional_data, is_user_marked, user_notes, is_acknowledged, acknowledged_at, status, created_at, updated_at FROM events
WHERE session_id = $1
  AND timestamp BETWEEN $2 - $3 AND $2 + $3
ORDER BY ABS(timestamp - $2) ASC
LIMIT $4
`

type GetEventsNearTimestampParams struct {
	SessionID int64       `json:"session_id"`
	Column2   interface{} `json:"column_2"`
	Column3   interface{} `json:"column_3"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) GetEventsNearTimestamp(ctx context.Context, arg GetEventsNearTimestampParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsNearTimestamp,
		arg.SessionID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CandleID,
			&i.EventType,
			&i.EventCategory,
			&i.Title,
			&i.Description,
			&i.Timestamp,
			&i.DurationSeconds,
			&i.Severity,
			&i.ImpactScore,
			&i.PriceAtEvent,
			&i.PriceBefore,
			&i.PriceAfter,
			&i.PriceChangePercent,
			&i.VolumeAtEvent,
			&i.VolumeSpikeRatio,
			&i.TriggeredBy,
			&i.TriggerConditions,
			&i.Tags,
			&i.IndicatorsAtEvent,
			&i.AdditionalData,
			&i.IsUserMarked,
			&i.UserNotes,
			&i.IsAcknowledged,
			&i.AcknowledgedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsSummary = `-- name: GetEventsSummary :one
SELECT 
    COUNT(*) as total_events,
    COUNT(*) FILTER (WHERE severity = 'critical') as critical_count,
    COUNT(*) FILTER (WHERE severity = 'high') as high_count,
    COUNT(*) FILTER (WHERE severity = 'medium') as medium_count,
    COUNT(*) FILTER (WHERE severity = 'low') as low_count,
    COUNT(*) FILTER (WHERE is_acknowledged = false) as unacknowledged_count,
    COUNT(*) FILTER (WHERE is_user_marked = true) as user_marked_count,
    AVG(impact_score) as avg_impact_score,
    MAX(impact_score) as max_impact_score
FROM events
WHERE session_id = $1
`

type GetEventsSummaryRow struct {
	TotalEvents         int64       `json:"total_events"`
	CriticalCount       int64       `json:"critical_count"`
	HighCount           int64       `json:"high_count"`
	MediumCount         int64       `json:"medium_count"`
	LowCount            int64       `json:"low_count"`
	UnacknowledgedCount int64       `json:"unacknowledged_count"`
	UserMarkedCount     int64       `json:"user_marked_count"`
	AvgImpactScore      float64     `json:"avg_impact_score"`
	MaxImpactScore      interface{} `json:"max_impact_score"`
}

func (q *Queries) GetEventsSummary(ctx context.Context, sessionID int64) (GetEventsSummaryRow, error) {
	row := q.db.QueryRow(ctx, getEventsSummary, sessionID)
	var i GetEventsSummaryRow
	err := row.Scan(
		&i.TotalEvents,
		&i.CriticalCount,
		&i.HighCount,
		&i.MediumCount,
		&i.LowCount,
		&i.UnacknowledgedCount,
		&i.UserMarkedCount,
		&i.AvgImpactScore,
		&i.MaxImpactScore,
	)
	return i, err
}

const getEventsWithTags = `-- name: GetEventsWithTags :many
SELECT id, session_id, candle_id, event_type, event_category, title, description, timestamp, duration_seconds, severity, impact_score, price_at_event, price_before, price_after, price_change_percent, volume_at_event, volume_spike_ratio, triggered_by, trigger_conditions, tags, indicators_at_event, additional_data, is_user_marked, user_notes, is_acknowledged, acknowledged_at, status, created_at, updated_at FROM events
WHERE session_id = $1
  AND tags && $2::varchar[]
ORDER BY timestamp DESC
LIMIT $3
`

type GetEventsWithTagsParams struct {
	SessionID int64    `json:"session_id"`
	Column2   []string `json:"column_2"`
	Limit     int32    `json:"limit"`
}

func (q *Queries) GetEventsWithTags(ctx context.Context, arg GetEventsWithTagsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsWithTags, arg.SessionID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CandleID,
			&i.EventType,
			&i.EventCategory,
			&i.Title,
			&i.Description,
			&i.Timestamp,
			&i.DurationSeconds,
			&i.Severity,
			&i.ImpactScore,
			&i.PriceAtEvent,
			&i.PriceBefore,
			&i.PriceAfter,
			&i.PriceChangePercent,
			&i.VolumeAtEvent,
			&i.VolumeSpikeRatio,
			&i.TriggeredBy,
			&i.TriggerConditions,
			&i.Tags,
			&i.IndicatorsAtEvent,
			&i.AdditionalData,
			&i.IsUserMarked,
			&i.UserNotes,
			&i.IsAcknowledged,
			&i.AcknowledgedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFirstEvent = `-- name: GetFirstEvent :one
SELECT id, session_id, candle_id, event_type, event_category, title, description, timestamp, duration_seconds, severity, impact_score, price_at_event, price_before, price_after, price_change_percent, volume_at_event, volume_spike_ratio, triggered_by, trigger_conditions, tags, indicators_at_event, additional_data, is_user_marked, user_notes, is_acknowledged, acknowledged_at, status, created_at, updated_at FROM events
WHERE session_id = $1
ORDER BY timestamp ASC
LIMIT 1
`

func (q *Queries) GetFirstEvent(ctx context.Context, sessionID int64) (Event, error) {
	row := q.db.QueryRow(ctx, getFirstEvent, sessionID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CandleID,
		&i.EventType,
		&i.EventCategory,
		&i.Title,
		&i.Description,
		&i.Timestamp,
		&i.DurationSeconds,
		&i.Severity,
		&i.ImpactScore,
		&i.PriceAtEvent,
		&i.PriceBefore,
		&i.PriceAfter,
		&i.PriceChangePercent,
		&i.VolumeAtEvent,
		&i.VolumeSpikeRatio,
		&i.TriggeredBy,
		&i.TriggerConditions,
		&i.Tags,
		&i.IndicatorsAtEvent,
		&i.AdditionalData,
		&i.IsUserMarked,
		&i.UserNotes,
		&i.IsAcknowledged,
		&i.AcknowledgedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHighImpactEvents = `-- name: GetHighImpactEvents :many

SELECT id, session_id, candle_id, event_type, event_category, title, description, timestamp, duration_seconds, severity, impact_score, price_at_event, price_before, price_after, price_change_percent, volume_at_event, volume_spike_ratio, triggered_by, trigger_conditions, tags, indicators_at_event, additional_data, is_user_marked, user_notes, is_acknowledged, acknowledged_at, status, created_at, updated_at FROM events
WHERE session_id = $1
  AND impact_score >= $2
ORDER BY impact_score DESC, timestamp DESC
LIMIT $3
`

type GetHighImpactEventsParams struct {
	SessionID   int64          `json:"session_id"`
	ImpactScore pgtype.Numeric `json:"impact_score"`
	Limit       int32          `json:"limit"`
}

// =============================================================================
// ANALYSIS Operations
// =============================================================================
func (q *Queries) GetHighImpactEvents(ctx context.Context, arg GetHighImpactEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getHighImpactEvents, arg.SessionID, arg.ImpactScore, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CandleID,
			&i.EventType,
			&i.EventCategory,
			&i.Title,
			&i.Description,
			&i.Timestamp,
			&i.DurationSeconds,
			&i.Severity,
			&i.ImpactScore,
			&i.PriceAtEvent,
			&i.PriceBefore,
			&i.PriceAfter,
			&i.PriceChangePercent,
			&i.VolumeAtEvent,
			&i.VolumeSpikeRatio,
			&i.TriggeredBy,
			&i.TriggerConditions,
			&i.Tags,
			&i.IndicatorsAtEvent,
			&i.AdditionalData,
			&i.IsUserMarked,
			&i.UserNotes,
			&i.IsAcknowledged,
			&i.AcknowledgedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestEvent = `-- name: GetLatestEvent :one
SELECT id, session_id, candle_id, event_type, event_category, title, description, timestamp, duration_seconds, severity, impact_score, price_at_event, price_before, price_after, price_change_percent, volume_at_event, volume_spike_ratio, triggered_by, trigger_conditions, tags, indicators_at_event, additional_data, is_user_marked, user_notes, is_acknowledged, acknowledged_at, status, created_at, updated_at FROM events
WHERE session_id = $1
ORDER BY timestamp DESC
LIMIT 1
`

func (q *Queries) GetLatestEvent(ctx context.Context, sessionID int64) (Event, error) {
	row := q.db.QueryRow(ctx, getLatestEvent, sessionID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CandleID,
		&i.EventType,
		&i.EventCategory,
		&i.Title,
		&i.Description,
		&i.Timestamp,
		&i.DurationSeconds,
		&i.Severity,
		&i.ImpactScore,
		&i.PriceAtEvent,
		&i.PriceBefore,
		&i.PriceAfter,
		&i.PriceChangePercent,
		&i.VolumeAtEvent,
		&i.VolumeSpikeRatio,
		&i.TriggeredBy,
		&i.TriggerConditions,
		&i.Tags,
		&i.IndicatorsAtEvent,
		&i.AdditionalData,
		&i.IsUserMarked,
		&i.UserNotes,
		&i.IsAcknowledged,
		&i.AcknowledgedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPriceSpikes = `-- name: GetPriceSpikes :many
SELECT id, session_id, candle_id, event_type, event_category, title, description, timestamp, duration_seconds, severity, impact_score, price_at_event, price_before, price_after, price_change_percent, volume_at_event, volume_spike_ratio, triggered_by, trigger_conditions, tags, indicators_at_event, additional_data, is_user_marked, user_notes, is_acknowledged, acknowledged_at, status, created_at, updated_at FROM events
WHERE session_id = $1
  AND event_type IN ('price_spike', 'price_crash')
  AND ABS(price_change_percent) >= $2
ORDER BY ABS(price_change_percent) DESC
LIMIT $3
`

type GetPriceSpikesParams struct {
	SessionID          int64          `json:"session_id"`
	PriceChangePercent pgtype.Numeric `json:"price_change_percent"`
	Limit              int32          `json:"limit"`
}

func (q *Queries) GetPriceSpikes(ctx context.Context, arg GetPriceSpikesParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getPriceSpikes, arg.SessionID, arg.PriceChangePercent, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CandleID,
			&i.EventType,
			&i.EventCategory,
			&i.Title,
			&i.Description,
			&i.Timestamp,
			&i.DurationSeconds,
			&i.Severity,
			&i.ImpactScore,
			&i.PriceAtEvent,
			&i.PriceBefore,
			&i.PriceAfter,
			&i.PriceChangePercent,
			&i.VolumeAtEvent,
			&i.VolumeSpikeRatio,
			&i.TriggeredBy,
			&i.TriggerConditions,
			&i.Tags,
			&i.IndicatorsAtEvent,
			&i.AdditionalData,
			&i.IsUserMarked,
			&i.UserNotes,
			&i.IsAcknowledged,
			&i.AcknowledgedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentEvents = `-- name: GetRecentEvents :many
SELECT id, session_id, candle_id, event_type, event_category, title, description, timestamp, duration_seconds, severity, impact_score, price_at_event, price_before, price_after, price_change_percent, volume_at_event, volume_spike_ratio, triggered_by, trigger_conditions, tags, indicators_at_event, additional_data, is_user_marked, user_notes, is_acknowledged, acknowledged_at, status, created_at, updated_at FROM events
WHERE session_id = $1
ORDER BY timestamp DESC
LIMIT $2
`

type GetRecentEventsParams struct {
	SessionID int64 `json:"session_id"`
	Limit     int32 `json:"limit"`
}

func (q *Queries) GetRecentEvents(ctx context.Context, arg GetRecentEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getRecentEvents, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CandleID,
			&i.EventType,
			&i.EventCategory,
			&i.Title,
			&i.Description,
			&i.Timestamp,
			&i.DurationSeconds,
			&i.Severity,
			&i.ImpactScore,
			&i.PriceAtEvent,
			&i.PriceBefore,
			&i.PriceAfter,
			&i.PriceChangePercent,
			&i.VolumeAtEvent,
			&i.VolumeSpikeRatio,
			&i.TriggeredBy,
			&i.TriggerConditions,
			&i.Tags,
			&i.IndicatorsAtEvent,
			&i.AdditionalData,
			&i.IsUserMarked,
			&i.UserNotes,
			&i.IsAcknowledged,
			&i.AcknowledgedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeverityDistribution = `-- name: GetSeverityDistribution :many
SELECT 
    severity,
    COUNT(*) as event_count,
    AVG(impact_score) as avg_impact
FROM events
WHERE session_id = $1
GROUP BY severity
ORDER BY 
    CASE severity
        WHEN 'critical' THEN 1
        WHEN 'high' THEN 2
        WHEN 'medium' THEN 3
        WHEN 'low' THEN 4
        WHEN 'info' THEN 5
    END
`

type GetSeverityDistributionRow struct {
	Severity   pgtype.Text `json:"severity"`
	EventCount int64       `json:"event_count"`
	AvgImpact  float64     `json:"avg_impact"`
}

func (q *Queries) GetSeverityDistribution(ctx context.Context, sessionID int64) ([]GetSeverityDistributionRow, error) {
	rows, err := q.db.Query(ctx, getSeverityDistribution, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSeverityDistributionRow
	for rows.Next() {
		var i GetSeverityDistributionRow
		if err := rows.Scan(&i.Severity, &i.EventCount, &i.AvgImpact); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopEventTriggers = `-- name: GetTopEventTriggers :many
SELECT 
    triggered_by,
    COUNT(*) as trigger_count,
    AVG(impact_score) as avg_impact
FROM events
WHERE session_id = $1
  AND triggered_by IS NOT NULL
GROUP BY triggered_by
ORDER BY trigger_count DESC
LIMIT $2
`

type GetTopEventTriggersParams struct {
	SessionID int64 `json:"session_id"`
	Limit     int32 `json:"limit"`
}

type GetTopEventTriggersRow struct {
	TriggeredBy  pgtype.Text `json:"triggered_by"`
	TriggerCount int64       `json:"trigger_count"`
	AvgImpact    float64     `json:"avg_impact"`
}

func (q *Queries) GetTopEventTriggers(ctx context.Context, arg GetTopEventTriggersParams) ([]GetTopEventTriggersRow, error) {
	rows, err := q.db.Query(ctx, getTopEventTriggers, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopEventTriggersRow
	for rows.Next() {
		var i GetTopEventTriggersRow
		if err := rows.Scan(&i.TriggeredBy, &i.TriggerCount, &i.AvgImpact); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnacknowledgedEvents = `-- name: GetUnacknowledgedEvents :many
SELECT id, session_id, candle_id, event_type, event_category, title, description, timestamp, duration_seconds, severity, impact_score, price_at_event, price_before, price_after, price_change_percent, volume_at_event, volume_spike_ratio, triggered_by, trigger_conditions, tags, indicators_at_event, additional_data, is_user_marked, user_notes, is_acknowledged, acknowledged_at, status, created_at, updated_at FROM events
WHERE session_id = $1
  AND is_acknowledged = false
ORDER BY severity DESC, timestamp DESC
`

func (q *Queries) GetUnacknowledgedEvents(ctx context.Context, sessionID int64) ([]Event, error) {
	rows, err := q.db.Query(ctx, getUnacknowledgedEvents, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CandleID,
			&i.EventType,
			&i.EventCategory,
			&i.Title,
			&i.Description,
			&i.Timestamp,
			&i.DurationSeconds,
			&i.Severity,
			&i.ImpactScore,
			&i.PriceAtEvent,
			&i.PriceBefore,
			&i.PriceAfter,
			&i.PriceChangePercent,
			&i.VolumeAtEvent,
			&i.VolumeSpikeRatio,
			&i.TriggeredBy,
			&i.TriggerConditions,
			&i.Tags,
			&i.IndicatorsAtEvent,
			&i.AdditionalData,
			&i.IsUserMarked,
			&i.UserNotes,
			&i.IsAcknowledged,
			&i.AcknowledgedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserMarkedEvents = `-- name: GetUserMarkedEvents :many
SELECT id, session_id, candle_id, event_type, event_category, title, description, timestamp, duration_seconds, severity, impact_score, price_at_event, price_before, price_after, price_change_percent, volume_at_event, volume_spike_ratio, triggered_by, trigger_conditions, tags, indicators_at_event, additional_data, is_user_marked, user_notes, is_acknowledged, acknowledged_at, status, created_at, updated_at FROM events
WHERE session_id = $1
  AND is_user_marked = true
ORDER BY timestamp DESC
`

func (q *Queries) GetUserMarkedEvents(ctx context.Context, sessionID int64) ([]Event, error) {
	rows, err := q.db.Query(ctx, getUserMarkedEvents, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CandleID,
			&i.EventType,
			&i.EventCategory,
			&i.Title,
			&i.Description,
			&i.Timestamp,
			&i.DurationSeconds,
			&i.Severity,
			&i.ImpactScore,
			&i.PriceAtEvent,
			&i.PriceBefore,
			&i.PriceAfter,
			&i.PriceChangePercent,
			&i.VolumeAtEvent,
			&i.VolumeSpikeRatio,
			&i.TriggeredBy,
			&i.TriggerConditions,
			&i.Tags,
			&i.IndicatorsAtEvent,
			&i.AdditionalData,
			&i.IsUserMarked,
			&i.UserNotes,
			&i.IsAcknowledged,
			&i.AcknowledgedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVolumeSpikes = `-- name: GetVolumeSpikes :many
SELECT id, session_id, candle_id, event_type, event_category, title, description, timestamp, duration_seconds, severity, impact_score, price_at_event, price_before, price_after, price_change_percent, volume_at_event, volume_spike_ratio, triggered_by, trigger_conditions, tags, indicators_at_event, additional_data, is_user_marked, user_notes, is_acknowledged, acknowledged_at, status, created_at, updated_at FROM events
WHERE session_id = $1
  AND event_type = 'volume_spike'
  AND volume_spike_ratio >= $2
ORDER BY volume_spike_ratio DESC
LIMIT $3
`

type GetVolumeSpikesParams struct {
	SessionID        int64          `json:"session_id"`
	VolumeSpikeRatio pgtype.Numeric `json:"volume_spike_ratio"`
	Limit            int32          `json:"limit"`
}

func (q *Queries) GetVolumeSpikes(ctx context.Context, arg GetVolumeSpikesParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getVolumeSpikes, arg.SessionID, arg.VolumeSpikeRatio, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CandleID,
			&i.EventType,
			&i.EventCategory,
			&i.Title,
			&i.Description,
			&i.Timestamp,
			&i.DurationSeconds,
			&i.Severity,
			&i.ImpactScore,
			&i.PriceAtEvent,
			&i.PriceBefore,
			&i.PriceAfter,
			&i.PriceChangePercent,
			&i.VolumeAtEvent,
			&i.VolumeSpikeRatio,
			&i.TriggeredBy,
			&i.TriggerConditions,
			&i.Tags,
			&i.IndicatorsAtEvent,
			&i.AdditionalData,
			&i.IsUserMarked,
			&i.UserNotes,
			&i.IsAcknowledged,
			&i.AcknowledgedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeEventTag = `-- name: RemoveEventTag :exec
UPDATE events
SET 
    tags = array_remove(tags, $2),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type RemoveEventTagParams struct {
	ID          int64       `json:"id"`
	ArrayRemove interface{} `json:"array_remove"`
}

func (q *Queries) RemoveEventTag(ctx context.Context, arg RemoveEventTagParams) error {
	_, err := q.db.Exec(ctx, removeEventTag, arg.ID, arg.ArrayRemove)
	return err
}

const resolveEvent = `-- name: ResolveEvent :exec
UPDATE events
SET 
    status = 'resolved',
    is_acknowledged = true,
    acknowledged_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) ResolveEvent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, resolveEvent, id)
	return err
}

const searchEvents = `-- name: SearchEvents :many
SELECT id, session_id, candle_id, event_type, event_category, title, description, timestamp, duration_seconds, severity, impact_score, price_at_event, price_before, price_after, price_change_percent, volume_at_event, volume_spike_ratio, triggered_by, trigger_conditions, tags, indicators_at_event, additional_data, is_user_marked, user_notes, is_acknowledged, acknowledged_at, status, created_at, updated_at FROM events
WHERE session_id = $1
  AND (
    title ILIKE '%' || $2 || '%' OR
    description ILIKE '%' || $2 || '%'
  )
ORDER BY timestamp DESC
LIMIT $3
`

type SearchEventsParams struct {
	SessionID int64       `json:"session_id"`
	Column2   pgtype.Text `json:"column_2"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) SearchEvents(ctx context.Context, arg SearchEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, searchEvents, arg.SessionID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CandleID,
			&i.EventType,
			&i.EventCategory,
			&i.Title,
			&i.Description,
			&i.Timestamp,
			&i.DurationSeconds,
			&i.Severity,
			&i.ImpactScore,
			&i.PriceAtEvent,
			&i.PriceBefore,
			&i.PriceAfter,
			&i.PriceChangePercent,
			&i.VolumeAtEvent,
			&i.VolumeSpikeRatio,
			&i.TriggeredBy,
			&i.TriggerConditions,
			&i.Tags,
			&i.IndicatorsAtEvent,
			&i.AdditionalData,
			&i.IsUserMarked,
			&i.UserNotes,
			&i.IsAcknowledged,
			&i.AcknowledgedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleUserMark = `-- name: ToggleUserMark :one
UPDATE events
SET 
    is_user_marked = NOT is_user_marked,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING is_user_marked
`

func (q *Queries) ToggleUserMark(ctx context.Context, id int64) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, toggleUserMark, id)
	var is_user_marked pgtype.Bool
	err := row.Scan(&is_user_marked)
	return is_user_marked, err
}

const updateEvent = `-- name: UpdateEvent :one

UPDATE events
SET 
    title = $2,
    description = $3,
    severity = $4,
    user_notes = $5,
    tags = $6,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, session_id, candle_id, event_type, event_category, title, description, timestamp, duration_seconds, severity, impact_score, price_at_event, price_before, price_after, price_change_percent, volume_at_event, volume_spike_ratio, triggered_by, trigger_conditions, tags, indicators_at_event, additional_data, is_user_marked, user_notes, is_acknowledged, acknowledged_at, status, created_at, updated_at
`

type UpdateEventParams struct {
	ID          int64       `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Severity    pgtype.Text `json:"severity"`
	UserNotes   pgtype.Text `json:"user_notes"`
	Tags        []string    `json:"tags"`
}

// =============================================================================
// UPDATE Operations
// =============================================================================
func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Severity,
		arg.UserNotes,
		arg.Tags,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CandleID,
		&i.EventType,
		&i.EventCategory,
		&i.Title,
		&i.Description,
		&i.Timestamp,
		&i.DurationSeconds,
		&i.Severity,
		&i.ImpactScore,
		&i.PriceAtEvent,
		&i.PriceBefore,
		&i.PriceAfter,
		&i.PriceChangePercent,
		&i.VolumeAtEvent,
		&i.VolumeSpikeRatio,
		&i.TriggeredBy,
		&i.TriggerConditions,
		&i.Tags,
		&i.IndicatorsAtEvent,
		&i.AdditionalData,
		&i.IsUserMarked,
		&i.UserNotes,
		&i.IsAcknowledged,
		&i.AcknowledgedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEventNotes = `-- name: UpdateEventNotes :exec
UPDATE events
SET 
    user_notes = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateEventNotesParams struct {
	ID        int64       `json:"id"`
	UserNotes pgtype.Text `json:"user_notes"`
}

func (q *Queries) UpdateEventNotes(ctx context.Context, arg UpdateEventNotesParams) error {
	_, err := q.db.Exec(ctx, updateEventNotes, arg.ID, arg.UserNotes)
	return err
}

const updateEventStatus = `-- name: UpdateEventStatus :exec
UPDATE events
SET 
    status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateEventStatusParams struct {
	ID     int64       `json:"id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateEventStatus(ctx context.Context, arg UpdateEventStatusParams) error {
	_, err := q.db.Exec(ctx, updateEventStatus, arg.ID, arg.Status)
	return err
}
