// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: indicators.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkIndicatorExists = `-- name: CheckIndicatorExists :one
SELECT EXISTS(
    SELECT 1 FROM indicators
    WHERE candle_id = $1
      AND indicator_type = $2
      AND period = $3
) AS exists
`

type CheckIndicatorExistsParams struct {
	CandleID      int64       `json:"candle_id"`
	IndicatorType string      `json:"indicator_type"`
	Period        pgtype.Int4 `json:"period"`
}

func (q *Queries) CheckIndicatorExists(ctx context.Context, arg CheckIndicatorExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkIndicatorExists, arg.CandleID, arg.IndicatorType, arg.Period)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countIndicators = `-- name: CountIndicators :one

SELECT COUNT(*) FROM indicators
WHERE candle_id = $1
`

// =============================================================================
// AGGREGATE Operations
// =============================================================================
func (q *Queries) CountIndicators(ctx context.Context, candleID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countIndicators, candleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIndicatorsByType = `-- name: CountIndicatorsByType :one
SELECT COUNT(*) FROM indicators
WHERE indicator_type = $1
`

func (q *Queries) CountIndicatorsByType(ctx context.Context, indicatorType string) (int64, error) {
	row := q.db.QueryRow(ctx, countIndicatorsByType, indicatorType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIndicator = `-- name: CreateIndicator :one


INSERT INTO indicators (
    candle_id,
    indicator_type,
    value,
    value_upper,
    value_lower,
    value_middle,
    signal_line,
    histogram,
    period,
    period_fast,
    period_slow,
    period_signal,
    standard_deviations,
    signal,
    signal_strength,
    is_crossover,
    crossover_type,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18
)
RETURNING id, candle_id, indicator_type, value, value_upper, value_lower, value_middle, signal_line, histogram, period, period_fast, period_slow, period_signal, standard_deviations, signal, signal_strength, is_crossover, crossover_type, metadata, calculated_at
`

type CreateIndicatorParams struct {
	CandleID           int64          `json:"candle_id"`
	IndicatorType      string         `json:"indicator_type"`
	Value              pgtype.Numeric `json:"value"`
	ValueUpper         pgtype.Numeric `json:"value_upper"`
	ValueLower         pgtype.Numeric `json:"value_lower"`
	ValueMiddle        pgtype.Numeric `json:"value_middle"`
	SignalLine         pgtype.Numeric `json:"signal_line"`
	Histogram          pgtype.Numeric `json:"histogram"`
	Period             pgtype.Int4    `json:"period"`
	PeriodFast         pgtype.Int4    `json:"period_fast"`
	PeriodSlow         pgtype.Int4    `json:"period_slow"`
	PeriodSignal       pgtype.Int4    `json:"period_signal"`
	StandardDeviations pgtype.Numeric `json:"standard_deviations"`
	Signal             pgtype.Text    `json:"signal"`
	SignalStrength     pgtype.Numeric `json:"signal_strength"`
	IsCrossover        pgtype.Bool    `json:"is_crossover"`
	CrossoverType      pgtype.Text    `json:"crossover_type"`
	Metadata           []byte         `json:"metadata"`
}

// Indicators Queries
// CRUD operations and queries for technical indicators
// =============================================================================
// CREATE Operations
// =============================================================================
func (q *Queries) CreateIndicator(ctx context.Context, arg CreateIndicatorParams) (Indicator, error) {
	row := q.db.QueryRow(ctx, createIndicator,
		arg.CandleID,
		arg.IndicatorType,
		arg.Value,
		arg.ValueUpper,
		arg.ValueLower,
		arg.ValueMiddle,
		arg.SignalLine,
		arg.Histogram,
		arg.Period,
		arg.PeriodFast,
		arg.PeriodSlow,
		arg.PeriodSignal,
		arg.StandardDeviations,
		arg.Signal,
		arg.SignalStrength,
		arg.IsCrossover,
		arg.CrossoverType,
		arg.Metadata,
	)
	var i Indicator
	err := row.Scan(
		&i.ID,
		&i.CandleID,
		&i.IndicatorType,
		&i.Value,
		&i.ValueUpper,
		&i.ValueLower,
		&i.ValueMiddle,
		&i.SignalLine,
		&i.Histogram,
		&i.Period,
		&i.PeriodFast,
		&i.PeriodSlow,
		&i.PeriodSignal,
		&i.StandardDeviations,
		&i.Signal,
		&i.SignalStrength,
		&i.IsCrossover,
		&i.CrossoverType,
		&i.Metadata,
		&i.CalculatedAt,
	)
	return i, err
}

type CreateIndicatorBatchParams struct {
	CandleID      int64          `json:"candle_id"`
	IndicatorType string         `json:"indicator_type"`
	Value         pgtype.Numeric `json:"value"`
	Period        pgtype.Int4    `json:"period"`
	Signal        pgtype.Text    `json:"signal"`
}

const deleteIndicator = `-- name: DeleteIndicator :exec

DELETE FROM indicators
WHERE id = $1
`

// =============================================================================
// DELETE Operations
// =============================================================================
func (q *Queries) DeleteIndicator(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteIndicator, id)
	return err
}

const deleteIndicatorsByCandle = `-- name: DeleteIndicatorsByCandle :exec
DELETE FROM indicators
WHERE candle_id = $1
`

func (q *Queries) DeleteIndicatorsByCandle(ctx context.Context, candleID int64) error {
	_, err := q.db.Exec(ctx, deleteIndicatorsByCandle, candleID)
	return err
}

const deleteIndicatorsByType = `-- name: DeleteIndicatorsByType :exec
DELETE FROM indicators
WHERE indicator_type = $1
`

func (q *Queries) DeleteIndicatorsByType(ctx context.Context, indicatorType string) error {
	_, err := q.db.Exec(ctx, deleteIndicatorsByType, indicatorType)
	return err
}

const deleteOldIndicators = `-- name: DeleteOldIndicators :exec
DELETE FROM indicators
WHERE calculated_at < $1
`

func (q *Queries) DeleteOldIndicators(ctx context.Context, calculatedAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldIndicators, calculatedAt)
	return err
}

const getBollingerBands = `-- name: GetBollingerBands :many
SELECT 
    i.id, i.candle_id, i.indicator_type, i.value, i.value_upper, i.value_lower, i.value_middle, i.signal_line, i.histogram, i.period, i.period_fast, i.period_slow, i.period_signal, i.standard_deviations, i.signal, i.signal_strength, i.is_crossover, i.crossover_type, i.metadata, i.calculated_at,
    c.timestamp,
    c.close
FROM indicators i
JOIN candles c ON c.id = i.candle_id
WHERE c.symbol = $1
  AND c.timeframe = $2
  AND i.indicator_type = 'BB'
  AND i.period = $3
  AND c.timestamp >= $4
  AND c.timestamp <= $5
ORDER BY c.timestamp ASC
`

type GetBollingerBandsParams struct {
	Symbol      string      `json:"symbol"`
	Timeframe   string      `json:"timeframe"`
	Period      pgtype.Int4 `json:"period"`
	Timestamp   int64       `json:"timestamp"`
	Timestamp_2 int64       `json:"timestamp_2"`
}

type GetBollingerBandsRow struct {
	ID                 int64              `json:"id"`
	CandleID           int64              `json:"candle_id"`
	IndicatorType      string             `json:"indicator_type"`
	Value              pgtype.Numeric     `json:"value"`
	ValueUpper         pgtype.Numeric     `json:"value_upper"`
	ValueLower         pgtype.Numeric     `json:"value_lower"`
	ValueMiddle        pgtype.Numeric     `json:"value_middle"`
	SignalLine         pgtype.Numeric     `json:"signal_line"`
	Histogram          pgtype.Numeric     `json:"histogram"`
	Period             pgtype.Int4        `json:"period"`
	PeriodFast         pgtype.Int4        `json:"period_fast"`
	PeriodSlow         pgtype.Int4        `json:"period_slow"`
	PeriodSignal       pgtype.Int4        `json:"period_signal"`
	StandardDeviations pgtype.Numeric     `json:"standard_deviations"`
	Signal             pgtype.Text        `json:"signal"`
	SignalStrength     pgtype.Numeric     `json:"signal_strength"`
	IsCrossover        pgtype.Bool        `json:"is_crossover"`
	CrossoverType      pgtype.Text        `json:"crossover_type"`
	Metadata           []byte             `json:"metadata"`
	CalculatedAt       pgtype.Timestamptz `json:"calculated_at"`
	Timestamp          int64              `json:"timestamp"`
	Close              pgtype.Numeric     `json:"close"`
}

func (q *Queries) GetBollingerBands(ctx context.Context, arg GetBollingerBandsParams) ([]GetBollingerBandsRow, error) {
	rows, err := q.db.Query(ctx, getBollingerBands,
		arg.Symbol,
		arg.Timeframe,
		arg.Period,
		arg.Timestamp,
		arg.Timestamp_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBollingerBandsRow
	for rows.Next() {
		var i GetBollingerBandsRow
		if err := rows.Scan(
			&i.ID,
			&i.CandleID,
			&i.IndicatorType,
			&i.Value,
			&i.ValueUpper,
			&i.ValueLower,
			&i.ValueMiddle,
			&i.SignalLine,
			&i.Histogram,
			&i.Period,
			&i.PeriodFast,
			&i.PeriodSlow,
			&i.PeriodSignal,
			&i.StandardDeviations,
			&i.Signal,
			&i.SignalStrength,
			&i.IsCrossover,
			&i.CrossoverType,
			&i.Metadata,
			&i.CalculatedAt,
			&i.Timestamp,
			&i.Close,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBollingerBreakouts = `-- name: GetBollingerBreakouts :many
SELECT 
    i.id, i.candle_id, i.indicator_type, i.value, i.value_upper, i.value_lower, i.value_middle, i.signal_line, i.histogram, i.period, i.period_fast, i.period_slow, i.period_signal, i.standard_deviations, i.signal, i.signal_strength, i.is_crossover, i.crossover_type, i.metadata, i.calculated_at,
    c.symbol,
    c.timeframe,
    c.timestamp,
    c.close
FROM indicators i
JOIN candles c ON c.id = i.candle_id
WHERE c.symbol = $1
  AND c.timeframe = $2
  AND i.indicator_type = 'BB'
  AND (c.close > i.value_upper OR c.close < i.value_lower)
  AND c.timestamp >= $3
ORDER BY c.timestamp DESC
LIMIT $4
`

type GetBollingerBreakoutsParams struct {
	Symbol    string `json:"symbol"`
	Timeframe string `json:"timeframe"`
	Timestamp int64  `json:"timestamp"`
	Limit     int32  `json:"limit"`
}

type GetBollingerBreakoutsRow struct {
	ID                 int64              `json:"id"`
	CandleID           int64              `json:"candle_id"`
	IndicatorType      string             `json:"indicator_type"`
	Value              pgtype.Numeric     `json:"value"`
	ValueUpper         pgtype.Numeric     `json:"value_upper"`
	ValueLower         pgtype.Numeric     `json:"value_lower"`
	ValueMiddle        pgtype.Numeric     `json:"value_middle"`
	SignalLine         pgtype.Numeric     `json:"signal_line"`
	Histogram          pgtype.Numeric     `json:"histogram"`
	Period             pgtype.Int4        `json:"period"`
	PeriodFast         pgtype.Int4        `json:"period_fast"`
	PeriodSlow         pgtype.Int4        `json:"period_slow"`
	PeriodSignal       pgtype.Int4        `json:"period_signal"`
	StandardDeviations pgtype.Numeric     `json:"standard_deviations"`
	Signal             pgtype.Text        `json:"signal"`
	SignalStrength     pgtype.Numeric     `json:"signal_strength"`
	IsCrossover        pgtype.Bool        `json:"is_crossover"`
	CrossoverType      pgtype.Text        `json:"crossover_type"`
	Metadata           []byte             `json:"metadata"`
	CalculatedAt       pgtype.Timestamptz `json:"calculated_at"`
	Symbol             string             `json:"symbol"`
	Timeframe          string             `json:"timeframe"`
	Timestamp          int64              `json:"timestamp"`
	Close              pgtype.Numeric     `json:"close"`
}

func (q *Queries) GetBollingerBreakouts(ctx context.Context, arg GetBollingerBreakoutsParams) ([]GetBollingerBreakoutsRow, error) {
	rows, err := q.db.Query(ctx, getBollingerBreakouts,
		arg.Symbol,
		arg.Timeframe,
		arg.Timestamp,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBollingerBreakoutsRow
	for rows.Next() {
		var i GetBollingerBreakoutsRow
		if err := rows.Scan(
			&i.ID,
			&i.CandleID,
			&i.IndicatorType,
			&i.Value,
			&i.ValueUpper,
			&i.ValueLower,
			&i.ValueMiddle,
			&i.SignalLine,
			&i.Histogram,
			&i.Period,
			&i.PeriodFast,
			&i.PeriodSlow,
			&i.PeriodSignal,
			&i.StandardDeviations,
			&i.Signal,
			&i.SignalStrength,
			&i.IsCrossover,
			&i.CrossoverType,
			&i.Metadata,
			&i.CalculatedAt,
			&i.Symbol,
			&i.Timeframe,
			&i.Timestamp,
			&i.Close,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBuySignals = `-- name: GetBuySignals :many

SELECT 
    i.id, i.candle_id, i.indicator_type, i.value, i.value_upper, i.value_lower, i.value_middle, i.signal_line, i.histogram, i.period, i.period_fast, i.period_slow, i.period_signal, i.standard_deviations, i.signal, i.signal_strength, i.is_crossover, i.crossover_type, i.metadata, i.calculated_at,
    c.symbol,
    c.timeframe,
    c.timestamp,
    c.close
FROM indicators i
JOIN candles c ON c.id = i.candle_id
WHERE c.symbol = $1
  AND c.timeframe = $2
  AND i.signal = 'buy'
  AND c.timestamp >= $3
ORDER BY c.timestamp DESC
LIMIT $4
`

type GetBuySignalsParams struct {
	Symbol    string `json:"symbol"`
	Timeframe string `json:"timeframe"`
	Timestamp int64  `json:"timestamp"`
	Limit     int32  `json:"limit"`
}

type GetBuySignalsRow struct {
	ID                 int64              `json:"id"`
	CandleID           int64              `json:"candle_id"`
	IndicatorType      string             `json:"indicator_type"`
	Value              pgtype.Numeric     `json:"value"`
	ValueUpper         pgtype.Numeric     `json:"value_upper"`
	ValueLower         pgtype.Numeric     `json:"value_lower"`
	ValueMiddle        pgtype.Numeric     `json:"value_middle"`
	SignalLine         pgtype.Numeric     `json:"signal_line"`
	Histogram          pgtype.Numeric     `json:"histogram"`
	Period             pgtype.Int4        `json:"period"`
	PeriodFast         pgtype.Int4        `json:"period_fast"`
	PeriodSlow         pgtype.Int4        `json:"period_slow"`
	PeriodSignal       pgtype.Int4        `json:"period_signal"`
	StandardDeviations pgtype.Numeric     `json:"standard_deviations"`
	Signal             pgtype.Text        `json:"signal"`
	SignalStrength     pgtype.Numeric     `json:"signal_strength"`
	IsCrossover        pgtype.Bool        `json:"is_crossover"`
	CrossoverType      pgtype.Text        `json:"crossover_type"`
	Metadata           []byte             `json:"metadata"`
	CalculatedAt       pgtype.Timestamptz `json:"calculated_at"`
	Symbol             string             `json:"symbol"`
	Timeframe          string             `json:"timeframe"`
	Timestamp          int64              `json:"timestamp"`
	Close              pgtype.Numeric     `json:"close"`
}

// =============================================================================
// SIGNAL Operations
// =============================================================================
func (q *Queries) GetBuySignals(ctx context.Context, arg GetBuySignalsParams) ([]GetBuySignalsRow, error) {
	rows, err := q.db.Query(ctx, getBuySignals,
		arg.Symbol,
		arg.Timeframe,
		arg.Timestamp,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBuySignalsRow
	for rows.Next() {
		var i GetBuySignalsRow
		if err := rows.Scan(
			&i.ID,
			&i.CandleID,
			&i.IndicatorType,
			&i.Value,
			&i.ValueUpper,
			&i.ValueLower,
			&i.ValueMiddle,
			&i.SignalLine,
			&i.Histogram,
			&i.Period,
			&i.PeriodFast,
			&i.PeriodSlow,
			&i.PeriodSignal,
			&i.StandardDeviations,
			&i.Signal,
			&i.SignalStrength,
			&i.IsCrossover,
			&i.CrossoverType,
			&i.Metadata,
			&i.CalculatedAt,
			&i.Symbol,
			&i.Timeframe,
			&i.Timestamp,
			&i.Close,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCrossoverFrequency = `-- name: GetCrossoverFrequency :many
SELECT 
    indicator_type,
    crossover_type,
    COUNT(*) as crossover_count
FROM indicators
WHERE is_crossover = true
  AND crossover_type IS NOT NULL
GROUP BY indicator_type, crossover_type
ORDER BY crossover_count DESC
`

type GetCrossoverFrequencyRow struct {
	IndicatorType  string      `json:"indicator_type"`
	CrossoverType  pgtype.Text `json:"crossover_type"`
	CrossoverCount int64       `json:"crossover_count"`
}

func (q *Queries) GetCrossoverFrequency(ctx context.Context) ([]GetCrossoverFrequencyRow, error) {
	rows, err := q.db.Query(ctx, getCrossoverFrequency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCrossoverFrequencyRow
	for rows.Next() {
		var i GetCrossoverFrequencyRow
		if err := rows.Scan(&i.IndicatorType, &i.CrossoverType, &i.CrossoverCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCrossovers = `-- name: GetCrossovers :many

SELECT 
    i.id, i.candle_id, i.indicator_type, i.value, i.value_upper, i.value_lower, i.value_middle, i.signal_line, i.histogram, i.period, i.period_fast, i.period_slow, i.period_signal, i.standard_deviations, i.signal, i.signal_strength, i.is_crossover, i.crossover_type, i.metadata, i.calculated_at,
    c.symbol,
    c.timeframe,
    c.timestamp,
    c.close
FROM indicators i
JOIN candles c ON c.id = i.candle_id
WHERE c.symbol = $1
  AND c.timeframe = $2
  AND i.is_crossover = true
  AND c.timestamp >= $3
ORDER BY c.timestamp DESC
`

type GetCrossoversParams struct {
	Symbol    string `json:"symbol"`
	Timeframe string `json:"timeframe"`
	Timestamp int64  `json:"timestamp"`
}

type GetCrossoversRow struct {
	ID                 int64              `json:"id"`
	CandleID           int64              `json:"candle_id"`
	IndicatorType      string             `json:"indicator_type"`
	Value              pgtype.Numeric     `json:"value"`
	ValueUpper         pgtype.Numeric     `json:"value_upper"`
	ValueLower         pgtype.Numeric     `json:"value_lower"`
	ValueMiddle        pgtype.Numeric     `json:"value_middle"`
	SignalLine         pgtype.Numeric     `json:"signal_line"`
	Histogram          pgtype.Numeric     `json:"histogram"`
	Period             pgtype.Int4        `json:"period"`
	PeriodFast         pgtype.Int4        `json:"period_fast"`
	PeriodSlow         pgtype.Int4        `json:"period_slow"`
	PeriodSignal       pgtype.Int4        `json:"period_signal"`
	StandardDeviations pgtype.Numeric     `json:"standard_deviations"`
	Signal             pgtype.Text        `json:"signal"`
	SignalStrength     pgtype.Numeric     `json:"signal_strength"`
	IsCrossover        pgtype.Bool        `json:"is_crossover"`
	CrossoverType      pgtype.Text        `json:"crossover_type"`
	Metadata           []byte             `json:"metadata"`
	CalculatedAt       pgtype.Timestamptz `json:"calculated_at"`
	Symbol             string             `json:"symbol"`
	Timeframe          string             `json:"timeframe"`
	Timestamp          int64              `json:"timestamp"`
	Close              pgtype.Numeric     `json:"close"`
}

// =============================================================================
// CROSSOVER Operations
// =============================================================================
func (q *Queries) GetCrossovers(ctx context.Context, arg GetCrossoversParams) ([]GetCrossoversRow, error) {
	rows, err := q.db.Query(ctx, getCrossovers, arg.Symbol, arg.Timeframe, arg.Timestamp)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCrossoversRow
	for rows.Next() {
		var i GetCrossoversRow
		if err := rows.Scan(
			&i.ID,
			&i.CandleID,
			&i.IndicatorType,
			&i.Value,
			&i.ValueUpper,
			&i.ValueLower,
			&i.ValueMiddle,
			&i.SignalLine,
			&i.Histogram,
			&i.Period,
			&i.PeriodFast,
			&i.PeriodSlow,
			&i.PeriodSignal,
			&i.StandardDeviations,
			&i.Signal,
			&i.SignalStrength,
			&i.IsCrossover,
			&i.CrossoverType,
			&i.Metadata,
			&i.CalculatedAt,
			&i.Symbol,
			&i.Timeframe,
			&i.Timestamp,
			&i.Close,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeathCrosses = `-- name: GetDeathCrosses :many
SELECT 
    i.id, i.candle_id, i.indicator_type, i.value, i.value_upper, i.value_lower, i.value_middle, i.signal_line, i.histogram, i.period, i.period_fast, i.period_slow, i.period_signal, i.standard_deviations, i.signal, i.signal_strength, i.is_crossover, i.crossover_type, i.metadata, i.calculated_at,
    c.symbol,
    c.timeframe,
    c.timestamp,
    c.close
FROM indicators i
JOIN candles c ON c.id = i.candle_id
WHERE c.symbol = $1
  AND c.timeframe = $2
  AND i.crossover_type = 'death'
  AND c.timestamp >= $3
ORDER BY c.timestamp DESC
LIMIT $4
`

type GetDeathCrossesParams struct {
	Symbol    string `json:"symbol"`
	Timeframe string `json:"timeframe"`
	Timestamp int64  `json:"timestamp"`
	Limit     int32  `json:"limit"`
}

type GetDeathCrossesRow struct {
	ID                 int64              `json:"id"`
	CandleID           int64              `json:"candle_id"`
	IndicatorType      string             `json:"indicator_type"`
	Value              pgtype.Numeric     `json:"value"`
	ValueUpper         pgtype.Numeric     `json:"value_upper"`
	ValueLower         pgtype.Numeric     `json:"value_lower"`
	ValueMiddle        pgtype.Numeric     `json:"value_middle"`
	SignalLine         pgtype.Numeric     `json:"signal_line"`
	Histogram          pgtype.Numeric     `json:"histogram"`
	Period             pgtype.Int4        `json:"period"`
	PeriodFast         pgtype.Int4        `json:"period_fast"`
	PeriodSlow         pgtype.Int4        `json:"period_slow"`
	PeriodSignal       pgtype.Int4        `json:"period_signal"`
	StandardDeviations pgtype.Numeric     `json:"standard_deviations"`
	Signal             pgtype.Text        `json:"signal"`
	SignalStrength     pgtype.Numeric     `json:"signal_strength"`
	IsCrossover        pgtype.Bool        `json:"is_crossover"`
	CrossoverType      pgtype.Text        `json:"crossover_type"`
	Metadata           []byte             `json:"metadata"`
	CalculatedAt       pgtype.Timestamptz `json:"calculated_at"`
	Symbol             string             `json:"symbol"`
	Timeframe          string             `json:"timeframe"`
	Timestamp          int64              `json:"timestamp"`
	Close              pgtype.Numeric     `json:"close"`
}

func (q *Queries) GetDeathCrosses(ctx context.Context, arg GetDeathCrossesParams) ([]GetDeathCrossesRow, error) {
	rows, err := q.db.Query(ctx, getDeathCrosses,
		arg.Symbol,
		arg.Timeframe,
		arg.Timestamp,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeathCrossesRow
	for rows.Next() {
		var i GetDeathCrossesRow
		if err := rows.Scan(
			&i.ID,
			&i.CandleID,
			&i.IndicatorType,
			&i.Value,
			&i.ValueUpper,
			&i.ValueLower,
			&i.ValueMiddle,
			&i.SignalLine,
			&i.Histogram,
			&i.Period,
			&i.PeriodFast,
			&i.PeriodSlow,
			&i.PeriodSignal,
			&i.StandardDeviations,
			&i.Signal,
			&i.SignalStrength,
			&i.IsCrossover,
			&i.CrossoverType,
			&i.Metadata,
			&i.CalculatedAt,
			&i.Symbol,
			&i.Timeframe,
			&i.Timestamp,
			&i.Close,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctIndicatorTypes = `-- name: GetDistinctIndicatorTypes :many

SELECT DISTINCT indicator_type
FROM indicators
ORDER BY indicator_type
`

// =============================================================================
// UTILITY Operations
// =============================================================================
func (q *Queries) GetDistinctIndicatorTypes(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getDistinctIndicatorTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var indicator_type string
		if err := rows.Scan(&indicator_type); err != nil {
			return nil, err
		}
		items = append(items, indicator_type)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEMAIndicators = `-- name: GetEMAIndicators :many
SELECT 
    i.id, i.candle_id, i.indicator_type, i.value, i.value_upper, i.value_lower, i.value_middle, i.signal_line, i.histogram, i.period, i.period_fast, i.period_slow, i.period_signal, i.standard_deviations, i.signal, i.signal_strength, i.is_crossover, i.crossover_type, i.metadata, i.calculated_at,
    c.timestamp,
    c.close
FROM indicators i
JOIN candles c ON c.id = i.candle_id
WHERE c.symbol = $1
  AND c.timeframe = $2
  AND i.indicator_type = 'EMA'
  AND i.period = $3
  AND c.timestamp >= $4
  AND c.timestamp <= $5
ORDER BY c.timestamp ASC
`

type GetEMAIndicatorsParams struct {
	Symbol      string      `json:"symbol"`
	Timeframe   string      `json:"timeframe"`
	Period      pgtype.Int4 `json:"period"`
	Timestamp   int64       `json:"timestamp"`
	Timestamp_2 int64       `json:"timestamp_2"`
}

type GetEMAIndicatorsRow struct {
	ID                 int64              `json:"id"`
	CandleID           int64              `json:"candle_id"`
	IndicatorType      string             `json:"indicator_type"`
	Value              pgtype.Numeric     `json:"value"`
	ValueUpper         pgtype.Numeric     `json:"value_upper"`
	ValueLower         pgtype.Numeric     `json:"value_lower"`
	ValueMiddle        pgtype.Numeric     `json:"value_middle"`
	SignalLine         pgtype.Numeric     `json:"signal_line"`
	Histogram          pgtype.Numeric     `json:"histogram"`
	Period             pgtype.Int4        `json:"period"`
	PeriodFast         pgtype.Int4        `json:"period_fast"`
	PeriodSlow         pgtype.Int4        `json:"period_slow"`
	PeriodSignal       pgtype.Int4        `json:"period_signal"`
	StandardDeviations pgtype.Numeric     `json:"standard_deviations"`
	Signal             pgtype.Text        `json:"signal"`
	SignalStrength     pgtype.Numeric     `json:"signal_strength"`
	IsCrossover        pgtype.Bool        `json:"is_crossover"`
	CrossoverType      pgtype.Text        `json:"crossover_type"`
	Metadata           []byte             `json:"metadata"`
	CalculatedAt       pgtype.Timestamptz `json:"calculated_at"`
	Timestamp          int64              `json:"timestamp"`
	Close              pgtype.Numeric     `json:"close"`
}

func (q *Queries) GetEMAIndicators(ctx context.Context, arg GetEMAIndicatorsParams) ([]GetEMAIndicatorsRow, error) {
	rows, err := q.db.Query(ctx, getEMAIndicators,
		arg.Symbol,
		arg.Timeframe,
		arg.Period,
		arg.Timestamp,
		arg.Timestamp_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEMAIndicatorsRow
	for rows.Next() {
		var i GetEMAIndicatorsRow
		if err := rows.Scan(
			&i.ID,
			&i.CandleID,
			&i.IndicatorType,
			&i.Value,
			&i.ValueUpper,
			&i.ValueLower,
			&i.ValueMiddle,
			&i.SignalLine,
			&i.Histogram,
			&i.Period,
			&i.PeriodFast,
			&i.PeriodSlow,
			&i.PeriodSignal,
			&i.StandardDeviations,
			&i.Signal,
			&i.SignalStrength,
			&i.IsCrossover,
			&i.CrossoverType,
			&i.Metadata,
			&i.CalculatedAt,
			&i.Timestamp,
			&i.Close,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGoldenCrosses = `-- name: GetGoldenCrosses :many
SELECT 
    i.id, i.candle_id, i.indicator_type, i.value, i.value_upper, i.value_lower, i.value_middle, i.signal_line, i.histogram, i.period, i.period_fast, i.period_slow, i.period_signal, i.standard_deviations, i.signal, i.signal_strength, i.is_crossover, i.crossover_type, i.metadata, i.calculated_at,
    c.symbol,
    c.timeframe,
    c.timestamp,
    c.close
FROM indicators i
JOIN candles c ON c.id = i.candle_id
WHERE c.symbol = $1
  AND c.timeframe = $2
  AND i.crossover_type = 'golden'
  AND c.timestamp >= $3
ORDER BY c.timestamp DESC
LIMIT $4
`

type GetGoldenCrossesParams struct {
	Symbol    string `json:"symbol"`
	Timeframe string `json:"timeframe"`
	Timestamp int64  `json:"timestamp"`
	Limit     int32  `json:"limit"`
}

type GetGoldenCrossesRow struct {
	ID                 int64              `json:"id"`
	CandleID           int64              `json:"candle_id"`
	IndicatorType      string             `json:"indicator_type"`
	Value              pgtype.Numeric     `json:"value"`
	ValueUpper         pgtype.Numeric     `json:"value_upper"`
	ValueLower         pgtype.Numeric     `json:"value_lower"`
	ValueMiddle        pgtype.Numeric     `json:"value_middle"`
	SignalLine         pgtype.Numeric     `json:"signal_line"`
	Histogram          pgtype.Numeric     `json:"histogram"`
	Period             pgtype.Int4        `json:"period"`
	PeriodFast         pgtype.Int4        `json:"period_fast"`
	PeriodSlow         pgtype.Int4        `json:"period_slow"`
	PeriodSignal       pgtype.Int4        `json:"period_signal"`
	StandardDeviations pgtype.Numeric     `json:"standard_deviations"`
	Signal             pgtype.Text        `json:"signal"`
	SignalStrength     pgtype.Numeric     `json:"signal_strength"`
	IsCrossover        pgtype.Bool        `json:"is_crossover"`
	CrossoverType      pgtype.Text        `json:"crossover_type"`
	Metadata           []byte             `json:"metadata"`
	CalculatedAt       pgtype.Timestamptz `json:"calculated_at"`
	Symbol             string             `json:"symbol"`
	Timeframe          string             `json:"timeframe"`
	Timestamp          int64              `json:"timestamp"`
	Close              pgtype.Numeric     `json:"close"`
}

func (q *Queries) GetGoldenCrosses(ctx context.Context, arg GetGoldenCrossesParams) ([]GetGoldenCrossesRow, error) {
	rows, err := q.db.Query(ctx, getGoldenCrosses,
		arg.Symbol,
		arg.Timeframe,
		arg.Timestamp,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGoldenCrossesRow
	for rows.Next() {
		var i GetGoldenCrossesRow
		if err := rows.Scan(
			&i.ID,
			&i.CandleID,
			&i.IndicatorType,
			&i.Value,
			&i.ValueUpper,
			&i.ValueLower,
			&i.ValueMiddle,
			&i.SignalLine,
			&i.Histogram,
			&i.Period,
			&i.PeriodFast,
			&i.PeriodSlow,
			&i.PeriodSignal,
			&i.StandardDeviations,
			&i.Signal,
			&i.SignalStrength,
			&i.IsCrossover,
			&i.CrossoverType,
			&i.Metadata,
			&i.CalculatedAt,
			&i.Symbol,
			&i.Timeframe,
			&i.Timestamp,
			&i.Close,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIndicatorByID = `-- name: GetIndicatorByID :one

SELECT id, candle_id, indicator_type, value, value_upper, value_lower, value_middle, signal_line, histogram, period, period_fast, period_slow, period_signal, standard_deviations, signal, signal_strength, is_crossover, crossover_type, metadata, calculated_at FROM indicators
WHERE id = $1
`

// =============================================================================
// READ Operations
// =============================================================================
func (q *Queries) GetIndicatorByID(ctx context.Context, id int64) (Indicator, error) {
	row := q.db.QueryRow(ctx, getIndicatorByID, id)
	var i Indicator
	err := row.Scan(
		&i.ID,
		&i.CandleID,
		&i.IndicatorType,
		&i.Value,
		&i.ValueUpper,
		&i.ValueLower,
		&i.ValueMiddle,
		&i.SignalLine,
		&i.Histogram,
		&i.Period,
		&i.PeriodFast,
		&i.PeriodSlow,
		&i.PeriodSignal,
		&i.StandardDeviations,
		&i.Signal,
		&i.SignalStrength,
		&i.IsCrossover,
		&i.CrossoverType,
		&i.Metadata,
		&i.CalculatedAt,
	)
	return i, err
}

const getIndicatorByType = `-- name: GetIndicatorByType :one
SELECT id, candle_id, indicator_type, value, value_upper, value_lower, value_middle, signal_line, histogram, period, period_fast, period_slow, period_signal, standard_deviations, signal, signal_strength, is_crossover, crossover_type, metadata, calculated_at FROM indicators
WHERE candle_id = $1
  AND indicator_type = $2
  AND period = COALESCE($3, period)
LIMIT 1
`

type GetIndicatorByTypeParams struct {
	CandleID      int64       `json:"candle_id"`
	IndicatorType string      `json:"indicator_type"`
	Period        pgtype.Int4 `json:"period"`
}

func (q *Queries) GetIndicatorByType(ctx context.Context, arg GetIndicatorByTypeParams) (Indicator, error) {
	row := q.db.QueryRow(ctx, getIndicatorByType, arg.CandleID, arg.IndicatorType, arg.Period)
	var i Indicator
	err := row.Scan(
		&i.ID,
		&i.CandleID,
		&i.IndicatorType,
		&i.Value,
		&i.ValueUpper,
		&i.ValueLower,
		&i.ValueMiddle,
		&i.SignalLine,
		&i.Histogram,
		&i.Period,
		&i.PeriodFast,
		&i.PeriodSlow,
		&i.PeriodSignal,
		&i.StandardDeviations,
		&i.Signal,
		&i.SignalStrength,
		&i.IsCrossover,
		&i.CrossoverType,
		&i.Metadata,
		&i.CalculatedAt,
	)
	return i, err
}

const getIndicatorHistory = `-- name: GetIndicatorHistory :many
SELECT 
    i.id, i.candle_id, i.indicator_type, i.value, i.value_upper, i.value_lower, i.value_middle, i.signal_line, i.histogram, i.period, i.period_fast, i.period_slow, i.period_signal, i.standard_deviations, i.signal, i.signal_strength, i.is_crossover, i.crossover_type, i.metadata, i.calculated_at,
    c.timestamp,
    c.close
FROM indicators i
JOIN candles c ON c.id = i.candle_id
WHERE c.symbol = $1
  AND c.timeframe = $2
  AND i.indicator_type = $3
ORDER BY c.timestamp DESC
LIMIT $4
`

type GetIndicatorHistoryParams struct {
	Symbol        string `json:"symbol"`
	Timeframe     string `json:"timeframe"`
	IndicatorType string `json:"indicator_type"`
	Limit         int32  `json:"limit"`
}

type GetIndicatorHistoryRow struct {
	ID                 int64              `json:"id"`
	CandleID           int64              `json:"candle_id"`
	IndicatorType      string             `json:"indicator_type"`
	Value              pgtype.Numeric     `json:"value"`
	ValueUpper         pgtype.Numeric     `json:"value_upper"`
	ValueLower         pgtype.Numeric     `json:"value_lower"`
	ValueMiddle        pgtype.Numeric     `json:"value_middle"`
	SignalLine         pgtype.Numeric     `json:"signal_line"`
	Histogram          pgtype.Numeric     `json:"histogram"`
	Period             pgtype.Int4        `json:"period"`
	PeriodFast         pgtype.Int4        `json:"period_fast"`
	PeriodSlow         pgtype.Int4        `json:"period_slow"`
	PeriodSignal       pgtype.Int4        `json:"period_signal"`
	StandardDeviations pgtype.Numeric     `json:"standard_deviations"`
	Signal             pgtype.Text        `json:"signal"`
	SignalStrength     pgtype.Numeric     `json:"signal_strength"`
	IsCrossover        pgtype.Bool        `json:"is_crossover"`
	CrossoverType      pgtype.Text        `json:"crossover_type"`
	Metadata           []byte             `json:"metadata"`
	CalculatedAt       pgtype.Timestamptz `json:"calculated_at"`
	Timestamp          int64              `json:"timestamp"`
	Close              pgtype.Numeric     `json:"close"`
}

func (q *Queries) GetIndicatorHistory(ctx context.Context, arg GetIndicatorHistoryParams) ([]GetIndicatorHistoryRow, error) {
	rows, err := q.db.Query(ctx, getIndicatorHistory,
		arg.Symbol,
		arg.Timeframe,
		arg.IndicatorType,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIndicatorHistoryRow
	for rows.Next() {
		var i GetIndicatorHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.CandleID,
			&i.IndicatorType,
			&i.Value,
			&i.ValueUpper,
			&i.ValueLower,
			&i.ValueMiddle,
			&i.SignalLine,
			&i.Histogram,
			&i.Period,
			&i.PeriodFast,
			&i.PeriodSlow,
			&i.PeriodSignal,
			&i.StandardDeviations,
			&i.Signal,
			&i.SignalStrength,
			&i.IsCrossover,
			&i.CrossoverType,
			&i.Metadata,
			&i.CalculatedAt,
			&i.Timestamp,
			&i.Close,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIndicatorPeriods = `-- name: GetIndicatorPeriods :many
SELECT DISTINCT period
FROM indicators
WHERE indicator_type = $1
  AND period IS NOT NULL
ORDER BY period
`

func (q *Queries) GetIndicatorPeriods(ctx context.Context, indicatorType string) ([]pgtype.Int4, error) {
	rows, err := q.db.Query(ctx, getIndicatorPeriods, indicatorType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Int4
	for rows.Next() {
		var period pgtype.Int4
		if err := rows.Scan(&period); err != nil {
			return nil, err
		}
		items = append(items, period)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIndicatorStats = `-- name: GetIndicatorStats :one
SELECT 
    indicator_type,
    COUNT(*) as total_count,
    AVG(value) as avg_value,
    MIN(value) as min_value,
    MAX(value) as max_value,
    COUNT(*) FILTER (WHERE signal = 'buy') as buy_signals,
    COUNT(*) FILTER (WHERE signal = 'sell') as sell_signals,
    COUNT(*) FILTER (WHERE is_crossover = true) as crossovers
FROM indicators
WHERE indicator_type = $1
GROUP BY indicator_type
`

type GetIndicatorStatsRow struct {
	IndicatorType string      `json:"indicator_type"`
	TotalCount    int64       `json:"total_count"`
	AvgValue      float64     `json:"avg_value"`
	MinValue      interface{} `json:"min_value"`
	MaxValue      interface{} `json:"max_value"`
	BuySignals    int64       `json:"buy_signals"`
	SellSignals   int64       `json:"sell_signals"`
	Crossovers    int64       `json:"crossovers"`
}

func (q *Queries) GetIndicatorStats(ctx context.Context, indicatorType string) (GetIndicatorStatsRow, error) {
	row := q.db.QueryRow(ctx, getIndicatorStats, indicatorType)
	var i GetIndicatorStatsRow
	err := row.Scan(
		&i.IndicatorType,
		&i.TotalCount,
		&i.AvgValue,
		&i.MinValue,
		&i.MaxValue,
		&i.BuySignals,
		&i.SellSignals,
		&i.Crossovers,
	)
	return i, err
}

const getIndicatorsByCandle = `-- name: GetIndicatorsByCandle :many
SELECT id, candle_id, indicator_type, value, value_upper, value_lower, value_middle, signal_line, histogram, period, period_fast, period_slow, period_signal, standard_deviations, signal, signal_strength, is_crossover, crossover_type, metadata, calculated_at FROM indicators
WHERE candle_id = $1
ORDER BY indicator_type, period
`

func (q *Queries) GetIndicatorsByCandle(ctx context.Context, candleID int64) ([]Indicator, error) {
	rows, err := q.db.Query(ctx, getIndicatorsByCandle, candleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Indicator
	for rows.Next() {
		var i Indicator
		if err := rows.Scan(
			&i.ID,
			&i.CandleID,
			&i.IndicatorType,
			&i.Value,
			&i.ValueUpper,
			&i.ValueLower,
			&i.ValueMiddle,
			&i.SignalLine,
			&i.Histogram,
			&i.Period,
			&i.PeriodFast,
			&i.PeriodSlow,
			&i.PeriodSignal,
			&i.StandardDeviations,
			&i.Signal,
			&i.SignalStrength,
			&i.IsCrossover,
			&i.CrossoverType,
			&i.Metadata,
			&i.CalculatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIndicatorsByType = `-- name: GetIndicatorsByType :many
SELECT id, candle_id, indicator_type, value, value_upper, value_lower, value_middle, signal_line, histogram, period, period_fast, period_slow, period_signal, standard_deviations, signal, signal_strength, is_crossover, crossover_type, metadata, calculated_at FROM indicators
WHERE indicator_type = $1
ORDER BY calculated_at DESC
LIMIT $2
`

type GetIndicatorsByTypeParams struct {
	IndicatorType string `json:"indicator_type"`
	Limit         int32  `json:"limit"`
}

func (q *Queries) GetIndicatorsByType(ctx context.Context, arg GetIndicatorsByTypeParams) ([]Indicator, error) {
	rows, err := q.db.Query(ctx, getIndicatorsByType, arg.IndicatorType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Indicator
	for rows.Next() {
		var i Indicator
		if err := rows.Scan(
			&i.ID,
			&i.CandleID,
			&i.IndicatorType,
			&i.Value,
			&i.ValueUpper,
			&i.ValueLower,
			&i.ValueMiddle,
			&i.SignalLine,
			&i.Histogram,
			&i.Period,
			&i.PeriodFast,
			&i.PeriodSlow,
			&i.PeriodSignal,
			&i.StandardDeviations,
			&i.Signal,
			&i.SignalStrength,
			&i.IsCrossover,
			&i.CrossoverType,
			&i.Metadata,
			&i.CalculatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIndicatorsForCandles = `-- name: GetIndicatorsForCandles :many
SELECT 
    i.id, i.candle_id, i.indicator_type, i.value, i.value_upper, i.value_lower, i.value_middle, i.signal_line, i.histogram, i.period, i.period_fast, i.period_slow, i.period_signal, i.standard_deviations, i.signal, i.signal_strength, i.is_crossover, i.crossover_type, i.metadata, i.calculated_at,
    c.symbol,
    c.timeframe,
    c.timestamp,
    c.close
FROM indicators i
JOIN candles c ON c.id = i.candle_id
WHERE c.symbol = $1
  AND c.timeframe = $2
  AND c.timestamp >= $3
  AND c.timestamp <= $4
ORDER BY c.timestamp ASC, i.indicator_type
`

type GetIndicatorsForCandlesParams struct {
	Symbol      string `json:"symbol"`
	Timeframe   string `json:"timeframe"`
	Timestamp   int64  `json:"timestamp"`
	Timestamp_2 int64  `json:"timestamp_2"`
}

type GetIndicatorsForCandlesRow struct {
	ID                 int64              `json:"id"`
	CandleID           int64              `json:"candle_id"`
	IndicatorType      string             `json:"indicator_type"`
	Value              pgtype.Numeric     `json:"value"`
	ValueUpper         pgtype.Numeric     `json:"value_upper"`
	ValueLower         pgtype.Numeric     `json:"value_lower"`
	ValueMiddle        pgtype.Numeric     `json:"value_middle"`
	SignalLine         pgtype.Numeric     `json:"signal_line"`
	Histogram          pgtype.Numeric     `json:"histogram"`
	Period             pgtype.Int4        `json:"period"`
	PeriodFast         pgtype.Int4        `json:"period_fast"`
	PeriodSlow         pgtype.Int4        `json:"period_slow"`
	PeriodSignal       pgtype.Int4        `json:"period_signal"`
	StandardDeviations pgtype.Numeric     `json:"standard_deviations"`
	Signal             pgtype.Text        `json:"signal"`
	SignalStrength     pgtype.Numeric     `json:"signal_strength"`
	IsCrossover        pgtype.Bool        `json:"is_crossover"`
	CrossoverType      pgtype.Text        `json:"crossover_type"`
	Metadata           []byte             `json:"metadata"`
	CalculatedAt       pgtype.Timestamptz `json:"calculated_at"`
	Symbol             string             `json:"symbol"`
	Timeframe          string             `json:"timeframe"`
	Timestamp          int64              `json:"timestamp"`
	Close              pgtype.Numeric     `json:"close"`
}

func (q *Queries) GetIndicatorsForCandles(ctx context.Context, arg GetIndicatorsForCandlesParams) ([]GetIndicatorsForCandlesRow, error) {
	rows, err := q.db.Query(ctx, getIndicatorsForCandles,
		arg.Symbol,
		arg.Timeframe,
		arg.Timestamp,
		arg.Timestamp_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIndicatorsForCandlesRow
	for rows.Next() {
		var i GetIndicatorsForCandlesRow
		if err := rows.Scan(
			&i.ID,
			&i.CandleID,
			&i.IndicatorType,
			&i.Value,
			&i.ValueUpper,
			&i.ValueLower,
			&i.ValueMiddle,
			&i.SignalLine,
			&i.Histogram,
			&i.Period,
			&i.PeriodFast,
			&i.PeriodSlow,
			&i.PeriodSignal,
			&i.StandardDeviations,
			&i.Signal,
			&i.SignalStrength,
			&i.IsCrossover,
			&i.CrossoverType,
			&i.Metadata,
			&i.CalculatedAt,
			&i.Symbol,
			&i.Timeframe,
			&i.Timestamp,
			&i.Close,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestIndicator = `-- name: GetLatestIndicator :one
SELECT 
    i.id, i.candle_id, i.indicator_type, i.value, i.value_upper, i.value_lower, i.value_middle, i.signal_line, i.histogram, i.period, i.period_fast, i.period_slow, i.period_signal, i.standard_deviations, i.signal, i.signal_strength, i.is_crossover, i.crossover_type, i.metadata, i.calculated_at,
    c.timestamp
FROM indicators i
JOIN candles c ON c.id = i.candle_id
WHERE c.symbol = $1
  AND c.timeframe = $2
  AND i.indicator_type = $3
  AND i.period = $4
ORDER BY c.timestamp DESC
LIMIT 1
`

type GetLatestIndicatorParams struct {
	Symbol        string      `json:"symbol"`
	Timeframe     string      `json:"timeframe"`
	IndicatorType string      `json:"indicator_type"`
	Period        pgtype.Int4 `json:"period"`
}

type GetLatestIndicatorRow struct {
	ID                 int64              `json:"id"`
	CandleID           int64              `json:"candle_id"`
	IndicatorType      string             `json:"indicator_type"`
	Value              pgtype.Numeric     `json:"value"`
	ValueUpper         pgtype.Numeric     `json:"value_upper"`
	ValueLower         pgtype.Numeric     `json:"value_lower"`
	ValueMiddle        pgtype.Numeric     `json:"value_middle"`
	SignalLine         pgtype.Numeric     `json:"signal_line"`
	Histogram          pgtype.Numeric     `json:"histogram"`
	Period             pgtype.Int4        `json:"period"`
	PeriodFast         pgtype.Int4        `json:"period_fast"`
	PeriodSlow         pgtype.Int4        `json:"period_slow"`
	PeriodSignal       pgtype.Int4        `json:"period_signal"`
	StandardDeviations pgtype.Numeric     `json:"standard_deviations"`
	Signal             pgtype.Text        `json:"signal"`
	SignalStrength     pgtype.Numeric     `json:"signal_strength"`
	IsCrossover        pgtype.Bool        `json:"is_crossover"`
	CrossoverType      pgtype.Text        `json:"crossover_type"`
	Metadata           []byte             `json:"metadata"`
	CalculatedAt       pgtype.Timestamptz `json:"calculated_at"`
	Timestamp          int64              `json:"timestamp"`
}

func (q *Queries) GetLatestIndicator(ctx context.Context, arg GetLatestIndicatorParams) (GetLatestIndicatorRow, error) {
	row := q.db.QueryRow(ctx, getLatestIndicator,
		arg.Symbol,
		arg.Timeframe,
		arg.IndicatorType,
		arg.Period,
	)
	var i GetLatestIndicatorRow
	err := row.Scan(
		&i.ID,
		&i.CandleID,
		&i.IndicatorType,
		&i.Value,
		&i.ValueUpper,
		&i.ValueLower,
		&i.ValueMiddle,
		&i.SignalLine,
		&i.Histogram,
		&i.Period,
		&i.PeriodFast,
		&i.PeriodSlow,
		&i.PeriodSignal,
		&i.StandardDeviations,
		&i.Signal,
		&i.SignalStrength,
		&i.IsCrossover,
		&i.CrossoverType,
		&i.Metadata,
		&i.CalculatedAt,
		&i.Timestamp,
	)
	return i, err
}

const getMACDIndicators = `-- name: GetMACDIndicators :many
SELECT 
    i.id, i.candle_id, i.indicator_type, i.value, i.value_upper, i.value_lower, i.value_middle, i.signal_line, i.histogram, i.period, i.period_fast, i.period_slow, i.period_signal, i.standard_deviations, i.signal, i.signal_strength, i.is_crossover, i.crossover_type, i.metadata, i.calculated_at,
    c.timestamp,
    c.close
FROM indicators i
JOIN candles c ON c.id = i.candle_id
WHERE c.symbol = $1
  AND c.timeframe = $2
  AND i.indicator_type = 'MACD'
  AND c.timestamp >= $3
  AND c.timestamp <= $4
ORDER BY c.timestamp ASC
`

type GetMACDIndicatorsParams struct {
	Symbol      string `json:"symbol"`
	Timeframe   string `json:"timeframe"`
	Timestamp   int64  `json:"timestamp"`
	Timestamp_2 int64  `json:"timestamp_2"`
}

type GetMACDIndicatorsRow struct {
	ID                 int64              `json:"id"`
	CandleID           int64              `json:"candle_id"`
	IndicatorType      string             `json:"indicator_type"`
	Value              pgtype.Numeric     `json:"value"`
	ValueUpper         pgtype.Numeric     `json:"value_upper"`
	ValueLower         pgtype.Numeric     `json:"value_lower"`
	ValueMiddle        pgtype.Numeric     `json:"value_middle"`
	SignalLine         pgtype.Numeric     `json:"signal_line"`
	Histogram          pgtype.Numeric     `json:"histogram"`
	Period             pgtype.Int4        `json:"period"`
	PeriodFast         pgtype.Int4        `json:"period_fast"`
	PeriodSlow         pgtype.Int4        `json:"period_slow"`
	PeriodSignal       pgtype.Int4        `json:"period_signal"`
	StandardDeviations pgtype.Numeric     `json:"standard_deviations"`
	Signal             pgtype.Text        `json:"signal"`
	SignalStrength     pgtype.Numeric     `json:"signal_strength"`
	IsCrossover        pgtype.Bool        `json:"is_crossover"`
	CrossoverType      pgtype.Text        `json:"crossover_type"`
	Metadata           []byte             `json:"metadata"`
	CalculatedAt       pgtype.Timestamptz `json:"calculated_at"`
	Timestamp          int64              `json:"timestamp"`
	Close              pgtype.Numeric     `json:"close"`
}

func (q *Queries) GetMACDIndicators(ctx context.Context, arg GetMACDIndicatorsParams) ([]GetMACDIndicatorsRow, error) {
	rows, err := q.db.Query(ctx, getMACDIndicators,
		arg.Symbol,
		arg.Timeframe,
		arg.Timestamp,
		arg.Timestamp_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMACDIndicatorsRow
	for rows.Next() {
		var i GetMACDIndicatorsRow
		if err := rows.Scan(
			&i.ID,
			&i.CandleID,
			&i.IndicatorType,
			&i.Value,
			&i.ValueUpper,
			&i.ValueLower,
			&i.ValueMiddle,
			&i.SignalLine,
			&i.Histogram,
			&i.Period,
			&i.PeriodFast,
			&i.PeriodSlow,
			&i.PeriodSignal,
			&i.StandardDeviations,
			&i.Signal,
			&i.SignalStrength,
			&i.IsCrossover,
			&i.CrossoverType,
			&i.Metadata,
			&i.CalculatedAt,
			&i.Timestamp,
			&i.Close,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMAConvergence = `-- name: GetMAConvergence :many
SELECT 
    i1.candle_id,
    i1.value as fast_ma,
    i2.value as slow_ma,
    ABS(i1.value - i2.value) as convergence,
    c.timestamp,
    c.close
FROM indicators i1
JOIN indicators i2 ON i2.candle_id = i1.candle_id
JOIN candles c ON c.id = i1.candle_id
WHERE c.symbol = $1
  AND c.timeframe = $2
  AND i1.indicator_type = 'SMA'
  AND i2.indicator_type = 'SMA'
  AND i1.period = $3
  AND i2.period = $4
  AND c.timestamp >= $5
  AND c.timestamp <= $6
ORDER BY c.timestamp ASC
`

type GetMAConvergenceParams struct {
	Symbol      string      `json:"symbol"`
	Timeframe   string      `json:"timeframe"`
	Period      pgtype.Int4 `json:"period"`
	Period_2    pgtype.Int4 `json:"period_2"`
	Timestamp   int64       `json:"timestamp"`
	Timestamp_2 int64       `json:"timestamp_2"`
}

type GetMAConvergenceRow struct {
	CandleID    int64          `json:"candle_id"`
	FastMa      pgtype.Numeric `json:"fast_ma"`
	SlowMa      pgtype.Numeric `json:"slow_ma"`
	Convergence int64          `json:"convergence"`
	Timestamp   int64          `json:"timestamp"`
	Close       pgtype.Numeric `json:"close"`
}

func (q *Queries) GetMAConvergence(ctx context.Context, arg GetMAConvergenceParams) ([]GetMAConvergenceRow, error) {
	rows, err := q.db.Query(ctx, getMAConvergence,
		arg.Symbol,
		arg.Timeframe,
		arg.Period,
		arg.Period_2,
		arg.Timestamp,
		arg.Timestamp_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMAConvergenceRow
	for rows.Next() {
		var i GetMAConvergenceRow
		if err := rows.Scan(
			&i.CandleID,
			&i.FastMa,
			&i.SlowMa,
			&i.Convergence,
			&i.Timestamp,
			&i.Close,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOverboughtIndicators = `-- name: GetOverboughtIndicators :many
SELECT 
    i.id, i.candle_id, i.indicator_type, i.value, i.value_upper, i.value_lower, i.value_middle, i.signal_line, i.histogram, i.period, i.period_fast, i.period_slow, i.period_signal, i.standard_deviations, i.signal, i.signal_strength, i.is_crossover, i.crossover_type, i.metadata, i.calculated_at,
    c.symbol,
    c.timeframe,
    c.timestamp,
    c.close
FROM indicators i
JOIN candles c ON c.id = i.candle_id
WHERE c.symbol = $1
  AND c.timeframe = $2
  AND i.signal = 'overbought'
  AND c.timestamp >= $3
ORDER BY c.timestamp DESC
LIMIT $4
`

type GetOverboughtIndicatorsParams struct {
	Symbol    string `json:"symbol"`
	Timeframe string `json:"timeframe"`
	Timestamp int64  `json:"timestamp"`
	Limit     int32  `json:"limit"`
}

type GetOverboughtIndicatorsRow struct {
	ID                 int64              `json:"id"`
	CandleID           int64              `json:"candle_id"`
	IndicatorType      string             `json:"indicator_type"`
	Value              pgtype.Numeric     `json:"value"`
	ValueUpper         pgtype.Numeric     `json:"value_upper"`
	ValueLower         pgtype.Numeric     `json:"value_lower"`
	ValueMiddle        pgtype.Numeric     `json:"value_middle"`
	SignalLine         pgtype.Numeric     `json:"signal_line"`
	Histogram          pgtype.Numeric     `json:"histogram"`
	Period             pgtype.Int4        `json:"period"`
	PeriodFast         pgtype.Int4        `json:"period_fast"`
	PeriodSlow         pgtype.Int4        `json:"period_slow"`
	PeriodSignal       pgtype.Int4        `json:"period_signal"`
	StandardDeviations pgtype.Numeric     `json:"standard_deviations"`
	Signal             pgtype.Text        `json:"signal"`
	SignalStrength     pgtype.Numeric     `json:"signal_strength"`
	IsCrossover        pgtype.Bool        `json:"is_crossover"`
	CrossoverType      pgtype.Text        `json:"crossover_type"`
	Metadata           []byte             `json:"metadata"`
	CalculatedAt       pgtype.Timestamptz `json:"calculated_at"`
	Symbol             string             `json:"symbol"`
	Timeframe          string             `json:"timeframe"`
	Timestamp          int64              `json:"timestamp"`
	Close              pgtype.Numeric     `json:"close"`
}

func (q *Queries) GetOverboughtIndicators(ctx context.Context, arg GetOverboughtIndicatorsParams) ([]GetOverboughtIndicatorsRow, error) {
	rows, err := q.db.Query(ctx, getOverboughtIndicators,
		arg.Symbol,
		arg.Timeframe,
		arg.Timestamp,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOverboughtIndicatorsRow
	for rows.Next() {
		var i GetOverboughtIndicatorsRow
		if err := rows.Scan(
			&i.ID,
			&i.CandleID,
			&i.IndicatorType,
			&i.Value,
			&i.ValueUpper,
			&i.ValueLower,
			&i.ValueMiddle,
			&i.SignalLine,
			&i.Histogram,
			&i.Period,
			&i.PeriodFast,
			&i.PeriodSlow,
			&i.PeriodSignal,
			&i.StandardDeviations,
			&i.Signal,
			&i.SignalStrength,
			&i.IsCrossover,
			&i.CrossoverType,
			&i.Metadata,
			&i.CalculatedAt,
			&i.Symbol,
			&i.Timeframe,
			&i.Timestamp,
			&i.Close,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOversoldIndicators = `-- name: GetOversoldIndicators :many
SELECT 
    i.id, i.candle_id, i.indicator_type, i.value, i.value_upper, i.value_lower, i.value_middle, i.signal_line, i.histogram, i.period, i.period_fast, i.period_slow, i.period_signal, i.standard_deviations, i.signal, i.signal_strength, i.is_crossover, i.crossover_type, i.metadata, i.calculated_at,
    c.symbol,
    c.timeframe,
    c.timestamp,
    c.close
FROM indicators i
JOIN candles c ON c.id = i.candle_id
WHERE c.symbol = $1
  AND c.timeframe = $2
  AND i.signal = 'oversold'
  AND c.timestamp >= $3
ORDER BY c.timestamp DESC
LIMIT $4
`

type GetOversoldIndicatorsParams struct {
	Symbol    string `json:"symbol"`
	Timeframe string `json:"timeframe"`
	Timestamp int64  `json:"timestamp"`
	Limit     int32  `json:"limit"`
}

type GetOversoldIndicatorsRow struct {
	ID                 int64              `json:"id"`
	CandleID           int64              `json:"candle_id"`
	IndicatorType      string             `json:"indicator_type"`
	Value              pgtype.Numeric     `json:"value"`
	ValueUpper         pgtype.Numeric     `json:"value_upper"`
	ValueLower         pgtype.Numeric     `json:"value_lower"`
	ValueMiddle        pgtype.Numeric     `json:"value_middle"`
	SignalLine         pgtype.Numeric     `json:"signal_line"`
	Histogram          pgtype.Numeric     `json:"histogram"`
	Period             pgtype.Int4        `json:"period"`
	PeriodFast         pgtype.Int4        `json:"period_fast"`
	PeriodSlow         pgtype.Int4        `json:"period_slow"`
	PeriodSignal       pgtype.Int4        `json:"period_signal"`
	StandardDeviations pgtype.Numeric     `json:"standard_deviations"`
	Signal             pgtype.Text        `json:"signal"`
	SignalStrength     pgtype.Numeric     `json:"signal_strength"`
	IsCrossover        pgtype.Bool        `json:"is_crossover"`
	CrossoverType      pgtype.Text        `json:"crossover_type"`
	Metadata           []byte             `json:"metadata"`
	CalculatedAt       pgtype.Timestamptz `json:"calculated_at"`
	Symbol             string             `json:"symbol"`
	Timeframe          string             `json:"timeframe"`
	Timestamp          int64              `json:"timestamp"`
	Close              pgtype.Numeric     `json:"close"`
}

func (q *Queries) GetOversoldIndicators(ctx context.Context, arg GetOversoldIndicatorsParams) ([]GetOversoldIndicatorsRow, error) {
	rows, err := q.db.Query(ctx, getOversoldIndicators,
		arg.Symbol,
		arg.Timeframe,
		arg.Timestamp,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOversoldIndicatorsRow
	for rows.Next() {
		var i GetOversoldIndicatorsRow
		if err := rows.Scan(
			&i.ID,
			&i.CandleID,
			&i.IndicatorType,
			&i.Value,
			&i.ValueUpper,
			&i.ValueLower,
			&i.ValueMiddle,
			&i.SignalLine,
			&i.Histogram,
			&i.Period,
			&i.PeriodFast,
			&i.PeriodSlow,
			&i.PeriodSignal,
			&i.StandardDeviations,
			&i.Signal,
			&i.SignalStrength,
			&i.IsCrossover,
			&i.CrossoverType,
			&i.Metadata,
			&i.CalculatedAt,
			&i.Symbol,
			&i.Timeframe,
			&i.Timestamp,
			&i.Close,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRSIExtremes = `-- name: GetRSIExtremes :many

SELECT 
    i.id, i.candle_id, i.indicator_type, i.value, i.value_upper, i.value_lower, i.value_middle, i.signal_line, i.histogram, i.period, i.period_fast, i.period_slow, i.period_signal, i.standard_deviations, i.signal, i.signal_strength, i.is_crossover, i.crossover_type, i.metadata, i.calculated_at,
    c.symbol,
    c.timeframe,
    c.timestamp,
    c.close
FROM indicators i
JOIN candles c ON c.id = i.candle_id
WHERE c.symbol = $1
  AND c.timeframe = $2
  AND i.indicator_type = 'RSI'
  AND (i.value > $3 OR i.value < $4)
  AND c.timestamp >= $5
ORDER BY c.timestamp DESC
`

type GetRSIExtremesParams struct {
	Symbol    string         `json:"symbol"`
	Timeframe string         `json:"timeframe"`
	Value     pgtype.Numeric `json:"value"`
	Value_2   pgtype.Numeric `json:"value_2"`
	Timestamp int64          `json:"timestamp"`
}

type GetRSIExtremesRow struct {
	ID                 int64              `json:"id"`
	CandleID           int64              `json:"candle_id"`
	IndicatorType      string             `json:"indicator_type"`
	Value              pgtype.Numeric     `json:"value"`
	ValueUpper         pgtype.Numeric     `json:"value_upper"`
	ValueLower         pgtype.Numeric     `json:"value_lower"`
	ValueMiddle        pgtype.Numeric     `json:"value_middle"`
	SignalLine         pgtype.Numeric     `json:"signal_line"`
	Histogram          pgtype.Numeric     `json:"histogram"`
	Period             pgtype.Int4        `json:"period"`
	PeriodFast         pgtype.Int4        `json:"period_fast"`
	PeriodSlow         pgtype.Int4        `json:"period_slow"`
	PeriodSignal       pgtype.Int4        `json:"period_signal"`
	StandardDeviations pgtype.Numeric     `json:"standard_deviations"`
	Signal             pgtype.Text        `json:"signal"`
	SignalStrength     pgtype.Numeric     `json:"signal_strength"`
	IsCrossover        pgtype.Bool        `json:"is_crossover"`
	CrossoverType      pgtype.Text        `json:"crossover_type"`
	Metadata           []byte             `json:"metadata"`
	CalculatedAt       pgtype.Timestamptz `json:"calculated_at"`
	Symbol             string             `json:"symbol"`
	Timeframe          string             `json:"timeframe"`
	Timestamp          int64              `json:"timestamp"`
	Close              pgtype.Numeric     `json:"close"`
}

// =============================================================================
// ANALYSIS Operations
// =============================================================================
func (q *Queries) GetRSIExtremes(ctx context.Context, arg GetRSIExtremesParams) ([]GetRSIExtremesRow, error) {
	rows, err := q.db.Query(ctx, getRSIExtremes,
		arg.Symbol,
		arg.Timeframe,
		arg.Value,
		arg.Value_2,
		arg.Timestamp,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRSIExtremesRow
	for rows.Next() {
		var i GetRSIExtremesRow
		if err := rows.Scan(
			&i.ID,
			&i.CandleID,
			&i.IndicatorType,
			&i.Value,
			&i.ValueUpper,
			&i.ValueLower,
			&i.ValueMiddle,
			&i.SignalLine,
			&i.Histogram,
			&i.Period,
			&i.PeriodFast,
			&i.PeriodSlow,
			&i.PeriodSignal,
			&i.StandardDeviations,
			&i.Signal,
			&i.SignalStrength,
			&i.IsCrossover,
			&i.CrossoverType,
			&i.Metadata,
			&i.CalculatedAt,
			&i.Symbol,
			&i.Timeframe,
			&i.Timestamp,
			&i.Close,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRSIIndicators = `-- name: GetRSIIndicators :many
SELECT 
    i.id, i.candle_id, i.indicator_type, i.value, i.value_upper, i.value_lower, i.value_middle, i.signal_line, i.histogram, i.period, i.period_fast, i.period_slow, i.period_signal, i.standard_deviations, i.signal, i.signal_strength, i.is_crossover, i.crossover_type, i.metadata, i.calculated_at,
    c.timestamp,
    c.close
FROM indicators i
JOIN candles c ON c.id = i.candle_id
WHERE c.symbol = $1
  AND c.timeframe = $2
  AND i.indicator_type = 'RSI'
  AND i.period = $3
  AND c.timestamp >= $4
  AND c.timestamp <= $5
ORDER BY c.timestamp ASC
`

type GetRSIIndicatorsParams struct {
	Symbol      string      `json:"symbol"`
	Timeframe   string      `json:"timeframe"`
	Period      pgtype.Int4 `json:"period"`
	Timestamp   int64       `json:"timestamp"`
	Timestamp_2 int64       `json:"timestamp_2"`
}

type GetRSIIndicatorsRow struct {
	ID                 int64              `json:"id"`
	CandleID           int64              `json:"candle_id"`
	IndicatorType      string             `json:"indicator_type"`
	Value              pgtype.Numeric     `json:"value"`
	ValueUpper         pgtype.Numeric     `json:"value_upper"`
	ValueLower         pgtype.Numeric     `json:"value_lower"`
	ValueMiddle        pgtype.Numeric     `json:"value_middle"`
	SignalLine         pgtype.Numeric     `json:"signal_line"`
	Histogram          pgtype.Numeric     `json:"histogram"`
	Period             pgtype.Int4        `json:"period"`
	PeriodFast         pgtype.Int4        `json:"period_fast"`
	PeriodSlow         pgtype.Int4        `json:"period_slow"`
	PeriodSignal       pgtype.Int4        `json:"period_signal"`
	StandardDeviations pgtype.Numeric     `json:"standard_deviations"`
	Signal             pgtype.Text        `json:"signal"`
	SignalStrength     pgtype.Numeric     `json:"signal_strength"`
	IsCrossover        pgtype.Bool        `json:"is_crossover"`
	CrossoverType      pgtype.Text        `json:"crossover_type"`
	Metadata           []byte             `json:"metadata"`
	CalculatedAt       pgtype.Timestamptz `json:"calculated_at"`
	Timestamp          int64              `json:"timestamp"`
	Close              pgtype.Numeric     `json:"close"`
}

func (q *Queries) GetRSIIndicators(ctx context.Context, arg GetRSIIndicatorsParams) ([]GetRSIIndicatorsRow, error) {
	rows, err := q.db.Query(ctx, getRSIIndicators,
		arg.Symbol,
		arg.Timeframe,
		arg.Period,
		arg.Timestamp,
		arg.Timestamp_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRSIIndicatorsRow
	for rows.Next() {
		var i GetRSIIndicatorsRow
		if err := rows.Scan(
			&i.ID,
			&i.CandleID,
			&i.IndicatorType,
			&i.Value,
			&i.ValueUpper,
			&i.ValueLower,
			&i.ValueMiddle,
			&i.SignalLine,
			&i.Histogram,
			&i.Period,
			&i.PeriodFast,
			&i.PeriodSlow,
			&i.PeriodSignal,
			&i.StandardDeviations,
			&i.Signal,
			&i.SignalStrength,
			&i.IsCrossover,
			&i.CrossoverType,
			&i.Metadata,
			&i.CalculatedAt,
			&i.Timestamp,
			&i.Close,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentCrossovers = `-- name: GetRecentCrossovers :many
SELECT 
    i.id, i.candle_id, i.indicator_type, i.value, i.value_upper, i.value_lower, i.value_middle, i.signal_line, i.histogram, i.period, i.period_fast, i.period_slow, i.period_signal, i.standard_deviations, i.signal, i.signal_strength, i.is_crossover, i.crossover_type, i.metadata, i.calculated_at,
    c.timestamp,
    c.close
FROM indicators i
JOIN candles c ON c.id = i.candle_id
WHERE c.symbol = $1
  AND c.timeframe = $2
  AND i.is_crossover = true
ORDER BY c.timestamp DESC
LIMIT $3
`

type GetRecentCrossoversParams struct {
	Symbol    string `json:"symbol"`
	Timeframe string `json:"timeframe"`
	Limit     int32  `json:"limit"`
}

type GetRecentCrossoversRow struct {
	ID                 int64              `json:"id"`
	CandleID           int64              `json:"candle_id"`
	IndicatorType      string             `json:"indicator_type"`
	Value              pgtype.Numeric     `json:"value"`
	ValueUpper         pgtype.Numeric     `json:"value_upper"`
	ValueLower         pgtype.Numeric     `json:"value_lower"`
	ValueMiddle        pgtype.Numeric     `json:"value_middle"`
	SignalLine         pgtype.Numeric     `json:"signal_line"`
	Histogram          pgtype.Numeric     `json:"histogram"`
	Period             pgtype.Int4        `json:"period"`
	PeriodFast         pgtype.Int4        `json:"period_fast"`
	PeriodSlow         pgtype.Int4        `json:"period_slow"`
	PeriodSignal       pgtype.Int4        `json:"period_signal"`
	StandardDeviations pgtype.Numeric     `json:"standard_deviations"`
	Signal             pgtype.Text        `json:"signal"`
	SignalStrength     pgtype.Numeric     `json:"signal_strength"`
	IsCrossover        pgtype.Bool        `json:"is_crossover"`
	CrossoverType      pgtype.Text        `json:"crossover_type"`
	Metadata           []byte             `json:"metadata"`
	CalculatedAt       pgtype.Timestamptz `json:"calculated_at"`
	Timestamp          int64              `json:"timestamp"`
	Close              pgtype.Numeric     `json:"close"`
}

func (q *Queries) GetRecentCrossovers(ctx context.Context, arg GetRecentCrossoversParams) ([]GetRecentCrossoversRow, error) {
	rows, err := q.db.Query(ctx, getRecentCrossovers, arg.Symbol, arg.Timeframe, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentCrossoversRow
	for rows.Next() {
		var i GetRecentCrossoversRow
		if err := rows.Scan(
			&i.ID,
			&i.CandleID,
			&i.IndicatorType,
			&i.Value,
			&i.ValueUpper,
			&i.ValueLower,
			&i.ValueMiddle,
			&i.SignalLine,
			&i.Histogram,
			&i.Period,
			&i.PeriodFast,
			&i.PeriodSlow,
			&i.PeriodSignal,
			&i.StandardDeviations,
			&i.Signal,
			&i.SignalStrength,
			&i.IsCrossover,
			&i.CrossoverType,
			&i.Metadata,
			&i.CalculatedAt,
			&i.Timestamp,
			&i.Close,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSMAIndicators = `-- name: GetSMAIndicators :many
SELECT 
    i.id, i.candle_id, i.indicator_type, i.value, i.value_upper, i.value_lower, i.value_middle, i.signal_line, i.histogram, i.period, i.period_fast, i.period_slow, i.period_signal, i.standard_deviations, i.signal, i.signal_strength, i.is_crossover, i.crossover_type, i.metadata, i.calculated_at,
    c.timestamp,
    c.close
FROM indicators i
JOIN candles c ON c.id = i.candle_id
WHERE c.symbol = $1
  AND c.timeframe = $2
  AND i.indicator_type = 'SMA'
  AND i.period = $3
  AND c.timestamp >= $4
  AND c.timestamp <= $5
ORDER BY c.timestamp ASC
`

type GetSMAIndicatorsParams struct {
	Symbol      string      `json:"symbol"`
	Timeframe   string      `json:"timeframe"`
	Period      pgtype.Int4 `json:"period"`
	Timestamp   int64       `json:"timestamp"`
	Timestamp_2 int64       `json:"timestamp_2"`
}

type GetSMAIndicatorsRow struct {
	ID                 int64              `json:"id"`
	CandleID           int64              `json:"candle_id"`
	IndicatorType      string             `json:"indicator_type"`
	Value              pgtype.Numeric     `json:"value"`
	ValueUpper         pgtype.Numeric     `json:"value_upper"`
	ValueLower         pgtype.Numeric     `json:"value_lower"`
	ValueMiddle        pgtype.Numeric     `json:"value_middle"`
	SignalLine         pgtype.Numeric     `json:"signal_line"`
	Histogram          pgtype.Numeric     `json:"histogram"`
	Period             pgtype.Int4        `json:"period"`
	PeriodFast         pgtype.Int4        `json:"period_fast"`
	PeriodSlow         pgtype.Int4        `json:"period_slow"`
	PeriodSignal       pgtype.Int4        `json:"period_signal"`
	StandardDeviations pgtype.Numeric     `json:"standard_deviations"`
	Signal             pgtype.Text        `json:"signal"`
	SignalStrength     pgtype.Numeric     `json:"signal_strength"`
	IsCrossover        pgtype.Bool        `json:"is_crossover"`
	CrossoverType      pgtype.Text        `json:"crossover_type"`
	Metadata           []byte             `json:"metadata"`
	CalculatedAt       pgtype.Timestamptz `json:"calculated_at"`
	Timestamp          int64              `json:"timestamp"`
	Close              pgtype.Numeric     `json:"close"`
}

func (q *Queries) GetSMAIndicators(ctx context.Context, arg GetSMAIndicatorsParams) ([]GetSMAIndicatorsRow, error) {
	rows, err := q.db.Query(ctx, getSMAIndicators,
		arg.Symbol,
		arg.Timeframe,
		arg.Period,
		arg.Timestamp,
		arg.Timestamp_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSMAIndicatorsRow
	for rows.Next() {
		var i GetSMAIndicatorsRow
		if err := rows.Scan(
			&i.ID,
			&i.CandleID,
			&i.IndicatorType,
			&i.Value,
			&i.ValueUpper,
			&i.ValueLower,
			&i.ValueMiddle,
			&i.SignalLine,
			&i.Histogram,
			&i.Period,
			&i.PeriodFast,
			&i.PeriodSlow,
			&i.PeriodSignal,
			&i.StandardDeviations,
			&i.Signal,
			&i.SignalStrength,
			&i.IsCrossover,
			&i.CrossoverType,
			&i.Metadata,
			&i.CalculatedAt,
			&i.Timestamp,
			&i.Close,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSellSignals = `-- name: GetSellSignals :many
SELECT 
    i.id, i.candle_id, i.indicator_type, i.value, i.value_upper, i.value_lower, i.value_middle, i.signal_line, i.histogram, i.period, i.period_fast, i.period_slow, i.period_signal, i.standard_deviations, i.signal, i.signal_strength, i.is_crossover, i.crossover_type, i.metadata, i.calculated_at,
    c.symbol,
    c.timeframe,
    c.timestamp,
    c.close
FROM indicators i
JOIN candles c ON c.id = i.candle_id
WHERE c.symbol = $1
  AND c.timeframe = $2
  AND i.signal = 'sell'
  AND c.timestamp >= $3
ORDER BY c.timestamp DESC
LIMIT $4
`

type GetSellSignalsParams struct {
	Symbol    string `json:"symbol"`
	Timeframe string `json:"timeframe"`
	Timestamp int64  `json:"timestamp"`
	Limit     int32  `json:"limit"`
}

type GetSellSignalsRow struct {
	ID                 int64              `json:"id"`
	CandleID           int64              `json:"candle_id"`
	IndicatorType      string             `json:"indicator_type"`
	Value              pgtype.Numeric     `json:"value"`
	ValueUpper         pgtype.Numeric     `json:"value_upper"`
	ValueLower         pgtype.Numeric     `json:"value_lower"`
	ValueMiddle        pgtype.Numeric     `json:"value_middle"`
	SignalLine         pgtype.Numeric     `json:"signal_line"`
	Histogram          pgtype.Numeric     `json:"histogram"`
	Period             pgtype.Int4        `json:"period"`
	PeriodFast         pgtype.Int4        `json:"period_fast"`
	PeriodSlow         pgtype.Int4        `json:"period_slow"`
	PeriodSignal       pgtype.Int4        `json:"period_signal"`
	StandardDeviations pgtype.Numeric     `json:"standard_deviations"`
	Signal             pgtype.Text        `json:"signal"`
	SignalStrength     pgtype.Numeric     `json:"signal_strength"`
	IsCrossover        pgtype.Bool        `json:"is_crossover"`
	CrossoverType      pgtype.Text        `json:"crossover_type"`
	Metadata           []byte             `json:"metadata"`
	CalculatedAt       pgtype.Timestamptz `json:"calculated_at"`
	Symbol             string             `json:"symbol"`
	Timeframe          string             `json:"timeframe"`
	Timestamp          int64              `json:"timestamp"`
	Close              pgtype.Numeric     `json:"close"`
}

func (q *Queries) GetSellSignals(ctx context.Context, arg GetSellSignalsParams) ([]GetSellSignalsRow, error) {
	rows, err := q.db.Query(ctx, getSellSignals,
		arg.Symbol,
		arg.Timeframe,
		arg.Timestamp,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSellSignalsRow
	for rows.Next() {
		var i GetSellSignalsRow
		if err := rows.Scan(
			&i.ID,
			&i.CandleID,
			&i.IndicatorType,
			&i.Value,
			&i.ValueUpper,
			&i.ValueLower,
			&i.ValueMiddle,
			&i.SignalLine,
			&i.Histogram,
			&i.Period,
			&i.PeriodFast,
			&i.PeriodSlow,
			&i.PeriodSignal,
			&i.StandardDeviations,
			&i.Signal,
			&i.SignalStrength,
			&i.IsCrossover,
			&i.CrossoverType,
			&i.Metadata,
			&i.CalculatedAt,
			&i.Symbol,
			&i.Timeframe,
			&i.Timestamp,
			&i.Close,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSignalDistribution = `-- name: GetSignalDistribution :many
SELECT 
    indicator_type,
    signal,
    COUNT(*) as signal_count,
    AVG(signal_strength) as avg_strength
FROM indicators
WHERE signal IS NOT NULL
GROUP BY indicator_type, signal
ORDER BY indicator_type, signal_count DESC
`

type GetSignalDistributionRow struct {
	IndicatorType string      `json:"indicator_type"`
	Signal        pgtype.Text `json:"signal"`
	SignalCount   int64       `json:"signal_count"`
	AvgStrength   float64     `json:"avg_strength"`
}

func (q *Queries) GetSignalDistribution(ctx context.Context) ([]GetSignalDistributionRow, error) {
	rows, err := q.db.Query(ctx, getSignalDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSignalDistributionRow
	for rows.Next() {
		var i GetSignalDistributionRow
		if err := rows.Scan(
			&i.IndicatorType,
			&i.Signal,
			&i.SignalCount,
			&i.AvgStrength,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSignalsByStrength = `-- name: GetSignalsByStrength :many
SELECT 
    i.id, i.candle_id, i.indicator_type, i.value, i.value_upper, i.value_lower, i.value_middle, i.signal_line, i.histogram, i.period, i.period_fast, i.period_slow, i.period_signal, i.standard_deviations, i.signal, i.signal_strength, i.is_crossover, i.crossover_type, i.metadata, i.calculated_at,
    c.timestamp,
    c.close
FROM indicators i
JOIN candles c ON c.id = i.candle_id
WHERE c.symbol = $1
  AND c.timeframe = $2
  AND i.signal_strength >= $3
  AND i.signal IN ('buy', 'sell')
ORDER BY i.signal_strength DESC, c.timestamp DESC
LIMIT $4
`

type GetSignalsByStrengthParams struct {
	Symbol         string         `json:"symbol"`
	Timeframe      string         `json:"timeframe"`
	SignalStrength pgtype.Numeric `json:"signal_strength"`
	Limit          int32          `json:"limit"`
}

type GetSignalsByStrengthRow struct {
	ID                 int64              `json:"id"`
	CandleID           int64              `json:"candle_id"`
	IndicatorType      string             `json:"indicator_type"`
	Value              pgtype.Numeric     `json:"value"`
	ValueUpper         pgtype.Numeric     `json:"value_upper"`
	ValueLower         pgtype.Numeric     `json:"value_lower"`
	ValueMiddle        pgtype.Numeric     `json:"value_middle"`
	SignalLine         pgtype.Numeric     `json:"signal_line"`
	Histogram          pgtype.Numeric     `json:"histogram"`
	Period             pgtype.Int4        `json:"period"`
	PeriodFast         pgtype.Int4        `json:"period_fast"`
	PeriodSlow         pgtype.Int4        `json:"period_slow"`
	PeriodSignal       pgtype.Int4        `json:"period_signal"`
	StandardDeviations pgtype.Numeric     `json:"standard_deviations"`
	Signal             pgtype.Text        `json:"signal"`
	SignalStrength     pgtype.Numeric     `json:"signal_strength"`
	IsCrossover        pgtype.Bool        `json:"is_crossover"`
	CrossoverType      pgtype.Text        `json:"crossover_type"`
	Metadata           []byte             `json:"metadata"`
	CalculatedAt       pgtype.Timestamptz `json:"calculated_at"`
	Timestamp          int64              `json:"timestamp"`
	Close              pgtype.Numeric     `json:"close"`
}

func (q *Queries) GetSignalsByStrength(ctx context.Context, arg GetSignalsByStrengthParams) ([]GetSignalsByStrengthRow, error) {
	rows, err := q.db.Query(ctx, getSignalsByStrength,
		arg.Symbol,
		arg.Timeframe,
		arg.SignalStrength,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSignalsByStrengthRow
	for rows.Next() {
		var i GetSignalsByStrengthRow
		if err := rows.Scan(
			&i.ID,
			&i.CandleID,
			&i.IndicatorType,
			&i.Value,
			&i.ValueUpper,
			&i.ValueLower,
			&i.ValueMiddle,
			&i.SignalLine,
			&i.Histogram,
			&i.Period,
			&i.PeriodFast,
			&i.PeriodSlow,
			&i.PeriodSignal,
			&i.StandardDeviations,
			&i.Signal,
			&i.SignalStrength,
			&i.IsCrossover,
			&i.CrossoverType,
			&i.Metadata,
			&i.CalculatedAt,
			&i.Timestamp,
			&i.Close,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCrossover = `-- name: MarkCrossover :exec
UPDATE indicators
SET 
    is_crossover = true,
    crossover_type = $2
WHERE id = $1
`

type MarkCrossoverParams struct {
	ID            int64       `json:"id"`
	CrossoverType pgtype.Text `json:"crossover_type"`
}

func (q *Queries) MarkCrossover(ctx context.Context, arg MarkCrossoverParams) error {
	_, err := q.db.Exec(ctx, markCrossover, arg.ID, arg.CrossoverType)
	return err
}

const updateIndicator = `-- name: UpdateIndicator :one

UPDATE indicators
SET 
    value = $2,
    value_upper = $3,
    value_lower = $4,
    signal = $5,
    signal_strength = $6
WHERE id = $1
RETURNING id, candle_id, indicator_type, value, value_upper, value_lower, value_middle, signal_line, histogram, period, period_fast, period_slow, period_signal, standard_deviations, signal, signal_strength, is_crossover, crossover_type, metadata, calculated_at
`

type UpdateIndicatorParams struct {
	ID             int64          `json:"id"`
	Value          pgtype.Numeric `json:"value"`
	ValueUpper     pgtype.Numeric `json:"value_upper"`
	ValueLower     pgtype.Numeric `json:"value_lower"`
	Signal         pgtype.Text    `json:"signal"`
	SignalStrength pgtype.Numeric `json:"signal_strength"`
}

// =============================================================================
// UPDATE Operations
// =============================================================================
func (q *Queries) UpdateIndicator(ctx context.Context, arg UpdateIndicatorParams) (Indicator, error) {
	row := q.db.QueryRow(ctx, updateIndicator,
		arg.ID,
		arg.Value,
		arg.ValueUpper,
		arg.ValueLower,
		arg.Signal,
		arg.SignalStrength,
	)
	var i Indicator
	err := row.Scan(
		&i.ID,
		&i.CandleID,
		&i.IndicatorType,
		&i.Value,
		&i.ValueUpper,
		&i.ValueLower,
		&i.ValueMiddle,
		&i.SignalLine,
		&i.Histogram,
		&i.Period,
		&i.PeriodFast,
		&i.PeriodSlow,
		&i.PeriodSignal,
		&i.StandardDeviations,
		&i.Signal,
		&i.SignalStrength,
		&i.IsCrossover,
		&i.CrossoverType,
		&i.Metadata,
		&i.CalculatedAt,
	)
	return i, err
}

const updateIndicatorSignal = `-- name: UpdateIndicatorSignal :exec
UPDATE indicators
SET 
    signal = $2,
    signal_strength = $3
WHERE id = $1
`

type UpdateIndicatorSignalParams struct {
	ID             int64          `json:"id"`
	Signal         pgtype.Text    `json:"signal"`
	SignalStrength pgtype.Numeric `json:"signal_strength"`
}

func (q *Queries) UpdateIndicatorSignal(ctx context.Context, arg UpdateIndicatorSignalParams) error {
	_, err := q.db.Exec(ctx, updateIndicatorSignal, arg.ID, arg.Signal, arg.SignalStrength)
	return err
}
