// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metrics.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkMetricExists = `-- name: CheckMetricExists :one
SELECT EXISTS(
    SELECT 1 FROM metrics 
    WHERE session_id = $1 
      AND timestamp = $2
) AS exists
`

type CheckMetricExistsParams struct {
	SessionID int64 `json:"session_id"`
	Timestamp int64 `json:"timestamp"`
}

func (q *Queries) CheckMetricExists(ctx context.Context, arg CheckMetricExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkMetricExists, arg.SessionID, arg.Timestamp)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countMetrics = `-- name: CountMetrics :one

SELECT COUNT(*) FROM metrics
WHERE session_id = $1
`

// =============================================================================
// AGGREGATE Operations
// =============================================================================
func (q *Queries) CountMetrics(ctx context.Context, sessionID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countMetrics, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMetric = `-- name: CreateMetric :one


INSERT INTO metrics (
    session_id,
    timestamp,
    current_price,
    price_change,
    price_change_percent,
    session_high,
    session_low,
    session_open,
    realized_volatility,
    volatility_1min,
    volatility_5min,
    volatility_1hour,
    volume,
    volume_ma_5,
    volume_ma_20,
    drawdown_percent,
    max_drawdown_percent,
    return_percent,
    sma_10,
    sma_20,
    sma_50,
    sma_200,
    ema_10,
    ema_20,
    rsi_14,
    macd,
    macd_signal,
    macd_histogram,
    standard_deviation,
    variance,
    signal,
    signal_strength,
    custom_metrics
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
    $21, $22, $23, $24, $25, $26, $27, $28, $29, $30,
    $31, $32, $33
)
RETURNING id, session_id, timestamp, current_price, price_change, price_change_percent, session_high, session_low, session_open, realized_volatility, volatility_1min, volatility_5min, volatility_1hour, volume, volume_ma_5, volume_ma_20, drawdown_percent, max_drawdown_percent, return_percent, sma_10, sma_20, sma_50, sma_200, ema_10, ema_20, rsi_14, macd, macd_signal, macd_histogram, standard_deviation, variance, skewness, kurtosis, signal, signal_strength, custom_metrics, created_at
`

type CreateMetricParams struct {
	SessionID          int64          `json:"session_id"`
	Timestamp          int64          `json:"timestamp"`
	CurrentPrice       pgtype.Numeric `json:"current_price"`
	PriceChange        pgtype.Numeric `json:"price_change"`
	PriceChangePercent pgtype.Numeric `json:"price_change_percent"`
	SessionHigh        pgtype.Numeric `json:"session_high"`
	SessionLow         pgtype.Numeric `json:"session_low"`
	SessionOpen        pgtype.Numeric `json:"session_open"`
	RealizedVolatility pgtype.Numeric `json:"realized_volatility"`
	Volatility1min     pgtype.Numeric `json:"volatility_1min"`
	Volatility5min     pgtype.Numeric `json:"volatility_5min"`
	Volatility1hour    pgtype.Numeric `json:"volatility_1hour"`
	Volume             pgtype.Numeric `json:"volume"`
	VolumeMa5          pgtype.Numeric `json:"volume_ma_5"`
	VolumeMa20         pgtype.Numeric `json:"volume_ma_20"`
	DrawdownPercent    pgtype.Numeric `json:"drawdown_percent"`
	MaxDrawdownPercent pgtype.Numeric `json:"max_drawdown_percent"`
	ReturnPercent      pgtype.Numeric `json:"return_percent"`
	Sma10              pgtype.Numeric `json:"sma_10"`
	Sma20              pgtype.Numeric `json:"sma_20"`
	Sma50              pgtype.Numeric `json:"sma_50"`
	Sma200             pgtype.Numeric `json:"sma_200"`
	Ema10              pgtype.Numeric `json:"ema_10"`
	Ema20              pgtype.Numeric `json:"ema_20"`
	Rsi14              pgtype.Numeric `json:"rsi_14"`
	Macd               pgtype.Numeric `json:"macd"`
	MacdSignal         pgtype.Numeric `json:"macd_signal"`
	MacdHistogram      pgtype.Numeric `json:"macd_histogram"`
	StandardDeviation  pgtype.Numeric `json:"standard_deviation"`
	Variance           pgtype.Numeric `json:"variance"`
	Signal             pgtype.Text    `json:"signal"`
	SignalStrength     pgtype.Numeric `json:"signal_strength"`
	CustomMetrics      []byte         `json:"custom_metrics"`
}

// Metrics Queries
// CRUD operations and queries for session analytics and metrics
// =============================================================================
// CREATE Operations
// =============================================================================
func (q *Queries) CreateMetric(ctx context.Context, arg CreateMetricParams) (Metric, error) {
	row := q.db.QueryRow(ctx, createMetric,
		arg.SessionID,
		arg.Timestamp,
		arg.CurrentPrice,
		arg.PriceChange,
		arg.PriceChangePercent,
		arg.SessionHigh,
		arg.SessionLow,
		arg.SessionOpen,
		arg.RealizedVolatility,
		arg.Volatility1min,
		arg.Volatility5min,
		arg.Volatility1hour,
		arg.Volume,
		arg.VolumeMa5,
		arg.VolumeMa20,
		arg.DrawdownPercent,
		arg.MaxDrawdownPercent,
		arg.ReturnPercent,
		arg.Sma10,
		arg.Sma20,
		arg.Sma50,
		arg.Sma200,
		arg.Ema10,
		arg.Ema20,
		arg.Rsi14,
		arg.Macd,
		arg.MacdSignal,
		arg.MacdHistogram,
		arg.StandardDeviation,
		arg.Variance,
		arg.Signal,
		arg.SignalStrength,
		arg.CustomMetrics,
	)
	var i Metric
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Timestamp,
		&i.CurrentPrice,
		&i.PriceChange,
		&i.PriceChangePercent,
		&i.SessionHigh,
		&i.SessionLow,
		&i.SessionOpen,
		&i.RealizedVolatility,
		&i.Volatility1min,
		&i.Volatility5min,
		&i.Volatility1hour,
		&i.Volume,
		&i.VolumeMa5,
		&i.VolumeMa20,
		&i.DrawdownPercent,
		&i.MaxDrawdownPercent,
		&i.ReturnPercent,
		&i.Sma10,
		&i.Sma20,
		&i.Sma50,
		&i.Sma200,
		&i.Ema10,
		&i.Ema20,
		&i.Rsi14,
		&i.Macd,
		&i.MacdSignal,
		&i.MacdHistogram,
		&i.StandardDeviation,
		&i.Variance,
		&i.Skewness,
		&i.Kurtosis,
		&i.Signal,
		&i.SignalStrength,
		&i.CustomMetrics,
		&i.CreatedAt,
	)
	return i, err
}

type CreateMetricBatchParams struct {
	SessionID    int64          `json:"session_id"`
	Timestamp    int64          `json:"timestamp"`
	CurrentPrice pgtype.Numeric `json:"current_price"`
	Volume       pgtype.Numeric `json:"volume"`
	Rsi14        pgtype.Numeric `json:"rsi_14"`
	Signal       pgtype.Text    `json:"signal"`
}

const deleteMetric = `-- name: DeleteMetric :exec

DELETE FROM metrics
WHERE id = $1
`

// =============================================================================
// DELETE Operations
// =============================================================================
func (q *Queries) DeleteMetric(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMetric, id)
	return err
}

const deleteMetricsBySession = `-- name: DeleteMetricsBySession :exec
DELETE FROM metrics
WHERE session_id = $1
`

func (q *Queries) DeleteMetricsBySession(ctx context.Context, sessionID int64) error {
	_, err := q.db.Exec(ctx, deleteMetricsBySession, sessionID)
	return err
}

const deleteOldMetrics = `-- name: DeleteOldMetrics :exec
DELETE FROM metrics
WHERE created_at < $1
`

func (q *Queries) DeleteOldMetrics(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldMetrics, createdAt)
	return err
}

const getDrawdownAnalysis = `-- name: GetDrawdownAnalysis :one
SELECT 
    MAX(drawdown_percent) as max_drawdown,
    AVG(drawdown_percent) as avg_drawdown,
    COUNT(*) FILTER (WHERE drawdown_percent > 5) as drawdowns_over_5pct,
    COUNT(*) FILTER (WHERE drawdown_percent > 10) as drawdowns_over_10pct
FROM metrics
WHERE session_id = $1
`

type GetDrawdownAnalysisRow struct {
	MaxDrawdown        interface{} `json:"max_drawdown"`
	AvgDrawdown        float64     `json:"avg_drawdown"`
	DrawdownsOver5pct  int64       `json:"drawdowns_over_5pct"`
	DrawdownsOver10pct int64       `json:"drawdowns_over_10pct"`
}

func (q *Queries) GetDrawdownAnalysis(ctx context.Context, sessionID int64) (GetDrawdownAnalysisRow, error) {
	row := q.db.QueryRow(ctx, getDrawdownAnalysis, sessionID)
	var i GetDrawdownAnalysisRow
	err := row.Scan(
		&i.MaxDrawdown,
		&i.AvgDrawdown,
		&i.DrawdownsOver5pct,
		&i.DrawdownsOver10pct,
	)
	return i, err
}

const getFirstMetric = `-- name: GetFirstMetric :one
SELECT id, session_id, timestamp, current_price, price_change, price_change_percent, session_high, session_low, session_open, realized_volatility, volatility_1min, volatility_5min, volatility_1hour, volume, volume_ma_5, volume_ma_20, drawdown_percent, max_drawdown_percent, return_percent, sma_10, sma_20, sma_50, sma_200, ema_10, ema_20, rsi_14, macd, macd_signal, macd_histogram, standard_deviation, variance, skewness, kurtosis, signal, signal_strength, custom_metrics, created_at FROM metrics
WHERE session_id = $1
ORDER BY timestamp ASC
LIMIT 1
`

func (q *Queries) GetFirstMetric(ctx context.Context, sessionID int64) (Metric, error) {
	row := q.db.QueryRow(ctx, getFirstMetric, sessionID)
	var i Metric
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Timestamp,
		&i.CurrentPrice,
		&i.PriceChange,
		&i.PriceChangePercent,
		&i.SessionHigh,
		&i.SessionLow,
		&i.SessionOpen,
		&i.RealizedVolatility,
		&i.Volatility1min,
		&i.Volatility5min,
		&i.Volatility1hour,
		&i.Volume,
		&i.VolumeMa5,
		&i.VolumeMa20,
		&i.DrawdownPercent,
		&i.MaxDrawdownPercent,
		&i.ReturnPercent,
		&i.Sma10,
		&i.Sma20,
		&i.Sma50,
		&i.Sma200,
		&i.Ema10,
		&i.Ema20,
		&i.Rsi14,
		&i.Macd,
		&i.MacdSignal,
		&i.MacdHistogram,
		&i.StandardDeviation,
		&i.Variance,
		&i.Skewness,
		&i.Kurtosis,
		&i.Signal,
		&i.SignalStrength,
		&i.CustomMetrics,
		&i.CreatedAt,
	)
	return i, err
}

const getHighVolatilityPeriods = `-- name: GetHighVolatilityPeriods :many
SELECT id, session_id, timestamp, current_price, price_change, price_change_percent, session_high, session_low, session_open, realized_volatility, volatility_1min, volatility_5min, volatility_1hour, volume, volume_ma_5, volume_ma_20, drawdown_percent, max_drawdown_percent, return_percent, sma_10, sma_20, sma_50, sma_200, ema_10, ema_20, rsi_14, macd, macd_signal, macd_histogram, standard_deviation, variance, skewness, kurtosis, signal, signal_strength, custom_metrics, created_at FROM metrics
WHERE session_id = $1
  AND realized_volatility > $2
ORDER BY realized_volatility DESC
LIMIT $3
`

type GetHighVolatilityPeriodsParams struct {
	SessionID          int64          `json:"session_id"`
	RealizedVolatility pgtype.Numeric `json:"realized_volatility"`
	Limit              int32          `json:"limit"`
}

func (q *Queries) GetHighVolatilityPeriods(ctx context.Context, arg GetHighVolatilityPeriodsParams) ([]Metric, error) {
	rows, err := q.db.Query(ctx, getHighVolatilityPeriods, arg.SessionID, arg.RealizedVolatility, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Metric
	for rows.Next() {
		var i Metric
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Timestamp,
			&i.CurrentPrice,
			&i.PriceChange,
			&i.PriceChangePercent,
			&i.SessionHigh,
			&i.SessionLow,
			&i.SessionOpen,
			&i.RealizedVolatility,
			&i.Volatility1min,
			&i.Volatility5min,
			&i.Volatility1hour,
			&i.Volume,
			&i.VolumeMa5,
			&i.VolumeMa20,
			&i.DrawdownPercent,
			&i.MaxDrawdownPercent,
			&i.ReturnPercent,
			&i.Sma10,
			&i.Sma20,
			&i.Sma50,
			&i.Sma200,
			&i.Ema10,
			&i.Ema20,
			&i.Rsi14,
			&i.Macd,
			&i.MacdSignal,
			&i.MacdHistogram,
			&i.StandardDeviation,
			&i.Variance,
			&i.Skewness,
			&i.Kurtosis,
			&i.Signal,
			&i.SignalStrength,
			&i.CustomMetrics,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastMetric = `-- name: GetLastMetric :one
SELECT id, session_id, timestamp, current_price, price_change, price_change_percent, session_high, session_low, session_open, realized_volatility, volatility_1min, volatility_5min, volatility_1hour, volume, volume_ma_5, volume_ma_20, drawdown_percent, max_drawdown_percent, return_percent, sma_10, sma_20, sma_50, sma_200, ema_10, ema_20, rsi_14, macd, macd_signal, macd_histogram, standard_deviation, variance, skewness, kurtosis, signal, signal_strength, custom_metrics, created_at FROM metrics
WHERE session_id = $1
ORDER BY timestamp DESC
LIMIT 1
`

func (q *Queries) GetLastMetric(ctx context.Context, sessionID int64) (Metric, error) {
	row := q.db.QueryRow(ctx, getLastMetric, sessionID)
	var i Metric
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Timestamp,
		&i.CurrentPrice,
		&i.PriceChange,
		&i.PriceChangePercent,
		&i.SessionHigh,
		&i.SessionLow,
		&i.SessionOpen,
		&i.RealizedVolatility,
		&i.Volatility1min,
		&i.Volatility5min,
		&i.Volatility1hour,
		&i.Volume,
		&i.VolumeMa5,
		&i.VolumeMa20,
		&i.DrawdownPercent,
		&i.MaxDrawdownPercent,
		&i.ReturnPercent,
		&i.Sma10,
		&i.Sma20,
		&i.Sma50,
		&i.Sma200,
		&i.Ema10,
		&i.Ema20,
		&i.Rsi14,
		&i.Macd,
		&i.MacdSignal,
		&i.MacdHistogram,
		&i.StandardDeviation,
		&i.Variance,
		&i.Skewness,
		&i.Kurtosis,
		&i.Signal,
		&i.SignalStrength,
		&i.CustomMetrics,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestMetric = `-- name: GetLatestMetric :one
SELECT id, session_id, timestamp, current_price, price_change, price_change_percent, session_high, session_low, session_open, realized_volatility, volatility_1min, volatility_5min, volatility_1hour, volume, volume_ma_5, volume_ma_20, drawdown_percent, max_drawdown_percent, return_percent, sma_10, sma_20, sma_50, sma_200, ema_10, ema_20, rsi_14, macd, macd_signal, macd_histogram, standard_deviation, variance, skewness, kurtosis, signal, signal_strength, custom_metrics, created_at FROM metrics
WHERE session_id = $1
ORDER BY timestamp DESC
LIMIT 1
`

func (q *Queries) GetLatestMetric(ctx context.Context, sessionID int64) (Metric, error) {
	row := q.db.QueryRow(ctx, getLatestMetric, sessionID)
	var i Metric
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Timestamp,
		&i.CurrentPrice,
		&i.PriceChange,
		&i.PriceChangePercent,
		&i.SessionHigh,
		&i.SessionLow,
		&i.SessionOpen,
		&i.RealizedVolatility,
		&i.Volatility1min,
		&i.Volatility5min,
		&i.Volatility1hour,
		&i.Volume,
		&i.VolumeMa5,
		&i.VolumeMa20,
		&i.DrawdownPercent,
		&i.MaxDrawdownPercent,
		&i.ReturnPercent,
		&i.Sma10,
		&i.Sma20,
		&i.Sma50,
		&i.Sma200,
		&i.Ema10,
		&i.Ema20,
		&i.Rsi14,
		&i.Macd,
		&i.MacdSignal,
		&i.MacdHistogram,
		&i.StandardDeviation,
		&i.Variance,
		&i.Skewness,
		&i.Kurtosis,
		&i.Signal,
		&i.SignalStrength,
		&i.CustomMetrics,
		&i.CreatedAt,
	)
	return i, err
}

const getMACDSeries = `-- name: GetMACDSeries :many
SELECT 
    timestamp,
    macd,
    macd_signal,
    macd_histogram
FROM metrics
WHERE session_id = $1
  AND timestamp >= $2
  AND timestamp <= $3
ORDER BY timestamp ASC
`

type GetMACDSeriesParams struct {
	SessionID   int64 `json:"session_id"`
	Timestamp   int64 `json:"timestamp"`
	Timestamp_2 int64 `json:"timestamp_2"`
}

type GetMACDSeriesRow struct {
	Timestamp     int64          `json:"timestamp"`
	Macd          pgtype.Numeric `json:"macd"`
	MacdSignal    pgtype.Numeric `json:"macd_signal"`
	MacdHistogram pgtype.Numeric `json:"macd_histogram"`
}

func (q *Queries) GetMACDSeries(ctx context.Context, arg GetMACDSeriesParams) ([]GetMACDSeriesRow, error) {
	rows, err := q.db.Query(ctx, getMACDSeries, arg.SessionID, arg.Timestamp, arg.Timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMACDSeriesRow
	for rows.Next() {
		var i GetMACDSeriesRow
		if err := rows.Scan(
			&i.Timestamp,
			&i.Macd,
			&i.MacdSignal,
			&i.MacdHistogram,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMetricByID = `-- name: GetMetricByID :one

SELECT id, session_id, timestamp, current_price, price_change, price_change_percent, session_high, session_low, session_open, realized_volatility, volatility_1min, volatility_5min, volatility_1hour, volume, volume_ma_5, volume_ma_20, drawdown_percent, max_drawdown_percent, return_percent, sma_10, sma_20, sma_50, sma_200, ema_10, ema_20, rsi_14, macd, macd_signal, macd_histogram, standard_deviation, variance, skewness, kurtosis, signal, signal_strength, custom_metrics, created_at FROM metrics
WHERE id = $1
`

// =============================================================================
// READ Operations
// =============================================================================
func (q *Queries) GetMetricByID(ctx context.Context, id int64) (Metric, error) {
	row := q.db.QueryRow(ctx, getMetricByID, id)
	var i Metric
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Timestamp,
		&i.CurrentPrice,
		&i.PriceChange,
		&i.PriceChangePercent,
		&i.SessionHigh,
		&i.SessionLow,
		&i.SessionOpen,
		&i.RealizedVolatility,
		&i.Volatility1min,
		&i.Volatility5min,
		&i.Volatility1hour,
		&i.Volume,
		&i.VolumeMa5,
		&i.VolumeMa20,
		&i.DrawdownPercent,
		&i.MaxDrawdownPercent,
		&i.ReturnPercent,
		&i.Sma10,
		&i.Sma20,
		&i.Sma50,
		&i.Sma200,
		&i.Ema10,
		&i.Ema20,
		&i.Rsi14,
		&i.Macd,
		&i.MacdSignal,
		&i.MacdHistogram,
		&i.StandardDeviation,
		&i.Variance,
		&i.Skewness,
		&i.Kurtosis,
		&i.Signal,
		&i.SignalStrength,
		&i.CustomMetrics,
		&i.CreatedAt,
	)
	return i, err
}

const getMetricCount = `-- name: GetMetricCount :one
SELECT COUNT(*) 
FROM metrics
WHERE session_id = $1
`

func (q *Queries) GetMetricCount(ctx context.Context, sessionID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getMetricCount, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMetricTimestamps = `-- name: GetMetricTimestamps :many

SELECT DISTINCT timestamp
FROM metrics
WHERE session_id = $1
ORDER BY timestamp ASC
`

// =============================================================================
// UTILITY Operations
// =============================================================================
func (q *Queries) GetMetricTimestamps(ctx context.Context, sessionID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getMetricTimestamps, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var timestamp int64
		if err := rows.Scan(&timestamp); err != nil {
			return nil, err
		}
		items = append(items, timestamp)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMetricsAboveRSI = `-- name: GetMetricsAboveRSI :many
SELECT id, session_id, timestamp, current_price, price_change, price_change_percent, session_high, session_low, session_open, realized_volatility, volatility_1min, volatility_5min, volatility_1hour, volume, volume_ma_5, volume_ma_20, drawdown_percent, max_drawdown_percent, return_percent, sma_10, sma_20, sma_50, sma_200, ema_10, ema_20, rsi_14, macd, macd_signal, macd_histogram, standard_deviation, variance, skewness, kurtosis, signal, signal_strength, custom_metrics, created_at FROM metrics
WHERE session_id = $1
  AND rsi_14 > $2
ORDER BY timestamp DESC
LIMIT $3
`

type GetMetricsAboveRSIParams struct {
	SessionID int64          `json:"session_id"`
	Rsi14     pgtype.Numeric `json:"rsi_14"`
	Limit     int32          `json:"limit"`
}

func (q *Queries) GetMetricsAboveRSI(ctx context.Context, arg GetMetricsAboveRSIParams) ([]Metric, error) {
	rows, err := q.db.Query(ctx, getMetricsAboveRSI, arg.SessionID, arg.Rsi14, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Metric
	for rows.Next() {
		var i Metric
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Timestamp,
			&i.CurrentPrice,
			&i.PriceChange,
			&i.PriceChangePercent,
			&i.SessionHigh,
			&i.SessionLow,
			&i.SessionOpen,
			&i.RealizedVolatility,
			&i.Volatility1min,
			&i.Volatility5min,
			&i.Volatility1hour,
			&i.Volume,
			&i.VolumeMa5,
			&i.VolumeMa20,
			&i.DrawdownPercent,
			&i.MaxDrawdownPercent,
			&i.ReturnPercent,
			&i.Sma10,
			&i.Sma20,
			&i.Sma50,
			&i.Sma200,
			&i.Ema10,
			&i.Ema20,
			&i.Rsi14,
			&i.Macd,
			&i.MacdSignal,
			&i.MacdHistogram,
			&i.StandardDeviation,
			&i.Variance,
			&i.Skewness,
			&i.Kurtosis,
			&i.Signal,
			&i.SignalStrength,
			&i.CustomMetrics,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMetricsBelowRSI = `-- name: GetMetricsBelowRSI :many
SELECT id, session_id, timestamp, current_price, price_change, price_change_percent, session_high, session_low, session_open, realized_volatility, volatility_1min, volatility_5min, volatility_1hour, volume, volume_ma_5, volume_ma_20, drawdown_percent, max_drawdown_percent, return_percent, sma_10, sma_20, sma_50, sma_200, ema_10, ema_20, rsi_14, macd, macd_signal, macd_histogram, standard_deviation, variance, skewness, kurtosis, signal, signal_strength, custom_metrics, created_at FROM metrics
WHERE session_id = $1
  AND rsi_14 < $2
ORDER BY timestamp DESC
LIMIT $3
`

type GetMetricsBelowRSIParams struct {
	SessionID int64          `json:"session_id"`
	Rsi14     pgtype.Numeric `json:"rsi_14"`
	Limit     int32          `json:"limit"`
}

func (q *Queries) GetMetricsBelowRSI(ctx context.Context, arg GetMetricsBelowRSIParams) ([]Metric, error) {
	rows, err := q.db.Query(ctx, getMetricsBelowRSI, arg.SessionID, arg.Rsi14, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Metric
	for rows.Next() {
		var i Metric
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Timestamp,
			&i.CurrentPrice,
			&i.PriceChange,
			&i.PriceChangePercent,
			&i.SessionHigh,
			&i.SessionLow,
			&i.SessionOpen,
			&i.RealizedVolatility,
			&i.Volatility1min,
			&i.Volatility5min,
			&i.Volatility1hour,
			&i.Volume,
			&i.VolumeMa5,
			&i.VolumeMa20,
			&i.DrawdownPercent,
			&i.MaxDrawdownPercent,
			&i.ReturnPercent,
			&i.Sma10,
			&i.Sma20,
			&i.Sma50,
			&i.Sma200,
			&i.Ema10,
			&i.Ema20,
			&i.Rsi14,
			&i.Macd,
			&i.MacdSignal,
			&i.MacdHistogram,
			&i.StandardDeviation,
			&i.Variance,
			&i.Skewness,
			&i.Kurtosis,
			&i.Signal,
			&i.SignalStrength,
			&i.CustomMetrics,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMetricsBuySignals = `-- name: GetMetricsBuySignals :many
SELECT id, session_id, timestamp, current_price, price_change, price_change_percent, session_high, session_low, session_open, realized_volatility, volatility_1min, volatility_5min, volatility_1hour, volume, volume_ma_5, volume_ma_20, drawdown_percent, max_drawdown_percent, return_percent, sma_10, sma_20, sma_50, sma_200, ema_10, ema_20, rsi_14, macd, macd_signal, macd_histogram, standard_deviation, variance, skewness, kurtosis, signal, signal_strength, custom_metrics, created_at FROM metrics
WHERE session_id = $1
  AND signal = 'buy'
ORDER BY timestamp ASC
`

func (q *Queries) GetMetricsBuySignals(ctx context.Context, sessionID int64) ([]Metric, error) {
	rows, err := q.db.Query(ctx, getMetricsBuySignals, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Metric
	for rows.Next() {
		var i Metric
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Timestamp,
			&i.CurrentPrice,
			&i.PriceChange,
			&i.PriceChangePercent,
			&i.SessionHigh,
			&i.SessionLow,
			&i.SessionOpen,
			&i.RealizedVolatility,
			&i.Volatility1min,
			&i.Volatility5min,
			&i.Volatility1hour,
			&i.Volume,
			&i.VolumeMa5,
			&i.VolumeMa20,
			&i.DrawdownPercent,
			&i.MaxDrawdownPercent,
			&i.ReturnPercent,
			&i.Sma10,
			&i.Sma20,
			&i.Sma50,
			&i.Sma200,
			&i.Ema10,
			&i.Ema20,
			&i.Rsi14,
			&i.Macd,
			&i.MacdSignal,
			&i.MacdHistogram,
			&i.StandardDeviation,
			&i.Variance,
			&i.Skewness,
			&i.Kurtosis,
			&i.Signal,
			&i.SignalStrength,
			&i.CustomMetrics,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMetricsBySession = `-- name: GetMetricsBySession :many
SELECT id, session_id, timestamp, current_price, price_change, price_change_percent, session_high, session_low, session_open, realized_volatility, volatility_1min, volatility_5min, volatility_1hour, volume, volume_ma_5, volume_ma_20, drawdown_percent, max_drawdown_percent, return_percent, sma_10, sma_20, sma_50, sma_200, ema_10, ema_20, rsi_14, macd, macd_signal, macd_histogram, standard_deviation, variance, skewness, kurtosis, signal, signal_strength, custom_metrics, created_at FROM metrics
WHERE session_id = $1
ORDER BY timestamp ASC
`

func (q *Queries) GetMetricsBySession(ctx context.Context, sessionID int64) ([]Metric, error) {
	rows, err := q.db.Query(ctx, getMetricsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Metric
	for rows.Next() {
		var i Metric
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Timestamp,
			&i.CurrentPrice,
			&i.PriceChange,
			&i.PriceChangePercent,
			&i.SessionHigh,
			&i.SessionLow,
			&i.SessionOpen,
			&i.RealizedVolatility,
			&i.Volatility1min,
			&i.Volatility5min,
			&i.Volatility1hour,
			&i.Volume,
			&i.VolumeMa5,
			&i.VolumeMa20,
			&i.DrawdownPercent,
			&i.MaxDrawdownPercent,
			&i.ReturnPercent,
			&i.Sma10,
			&i.Sma20,
			&i.Sma50,
			&i.Sma200,
			&i.Ema10,
			&i.Ema20,
			&i.Rsi14,
			&i.Macd,
			&i.MacdSignal,
			&i.MacdHistogram,
			&i.StandardDeviation,
			&i.Variance,
			&i.Skewness,
			&i.Kurtosis,
			&i.Signal,
			&i.SignalStrength,
			&i.CustomMetrics,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMetricsInRange = `-- name: GetMetricsInRange :many
SELECT id, session_id, timestamp, current_price, price_change, price_change_percent, session_high, session_low, session_open, realized_volatility, volatility_1min, volatility_5min, volatility_1hour, volume, volume_ma_5, volume_ma_20, drawdown_percent, max_drawdown_percent, return_percent, sma_10, sma_20, sma_50, sma_200, ema_10, ema_20, rsi_14, macd, macd_signal, macd_histogram, standard_deviation, variance, skewness, kurtosis, signal, signal_strength, custom_metrics, created_at FROM metrics
WHERE session_id = $1
  AND timestamp >= $2
  AND timestamp <= $3
ORDER BY timestamp ASC
`

type GetMetricsInRangeParams struct {
	SessionID   int64 `json:"session_id"`
	Timestamp   int64 `json:"timestamp"`
	Timestamp_2 int64 `json:"timestamp_2"`
}

func (q *Queries) GetMetricsInRange(ctx context.Context, arg GetMetricsInRangeParams) ([]Metric, error) {
	rows, err := q.db.Query(ctx, getMetricsInRange, arg.SessionID, arg.Timestamp, arg.Timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Metric
	for rows.Next() {
		var i Metric
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Timestamp,
			&i.CurrentPrice,
			&i.PriceChange,
			&i.PriceChangePercent,
			&i.SessionHigh,
			&i.SessionLow,
			&i.SessionOpen,
			&i.RealizedVolatility,
			&i.Volatility1min,
			&i.Volatility5min,
			&i.Volatility1hour,
			&i.Volume,
			&i.VolumeMa5,
			&i.VolumeMa20,
			&i.DrawdownPercent,
			&i.MaxDrawdownPercent,
			&i.ReturnPercent,
			&i.Sma10,
			&i.Sma20,
			&i.Sma50,
			&i.Sma200,
			&i.Ema10,
			&i.Ema20,
			&i.Rsi14,
			&i.Macd,
			&i.MacdSignal,
			&i.MacdHistogram,
			&i.StandardDeviation,
			&i.Variance,
			&i.Skewness,
			&i.Kurtosis,
			&i.Signal,
			&i.SignalStrength,
			&i.CustomMetrics,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMetricsPaginated = `-- name: GetMetricsPaginated :many
SELECT id, session_id, timestamp, current_price, price_change, price_change_percent, session_high, session_low, session_open, realized_volatility, volatility_1min, volatility_5min, volatility_1hour, volume, volume_ma_5, volume_ma_20, drawdown_percent, max_drawdown_percent, return_percent, sma_10, sma_20, sma_50, sma_200, ema_10, ema_20, rsi_14, macd, macd_signal, macd_histogram, standard_deviation, variance, skewness, kurtosis, signal, signal_strength, custom_metrics, created_at FROM metrics
WHERE session_id = $1
ORDER BY timestamp DESC
LIMIT $2
OFFSET $3
`

type GetMetricsPaginatedParams struct {
	SessionID int64 `json:"session_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) GetMetricsPaginated(ctx context.Context, arg GetMetricsPaginatedParams) ([]Metric, error) {
	rows, err := q.db.Query(ctx, getMetricsPaginated, arg.SessionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Metric
	for rows.Next() {
		var i Metric
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Timestamp,
			&i.CurrentPrice,
			&i.PriceChange,
			&i.PriceChangePercent,
			&i.SessionHigh,
			&i.SessionLow,
			&i.SessionOpen,
			&i.RealizedVolatility,
			&i.Volatility1min,
			&i.Volatility5min,
			&i.Volatility1hour,
			&i.Volume,
			&i.VolumeMa5,
			&i.VolumeMa20,
			&i.DrawdownPercent,
			&i.MaxDrawdownPercent,
			&i.ReturnPercent,
			&i.Sma10,
			&i.Sma20,
			&i.Sma50,
			&i.Sma200,
			&i.Ema10,
			&i.Ema20,
			&i.Rsi14,
			&i.Macd,
			&i.MacdSignal,
			&i.MacdHistogram,
			&i.StandardDeviation,
			&i.Variance,
			&i.Skewness,
			&i.Kurtosis,
			&i.Signal,
			&i.SignalStrength,
			&i.CustomMetrics,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMetricsRSIExtremes = `-- name: GetMetricsRSIExtremes :many

SELECT id, session_id, timestamp, current_price, price_change, price_change_percent, session_high, session_low, session_open, realized_volatility, volatility_1min, volatility_5min, volatility_1hour, volume, volume_ma_5, volume_ma_20, drawdown_percent, max_drawdown_percent, return_percent, sma_10, sma_20, sma_50, sma_200, ema_10, ema_20, rsi_14, macd, macd_signal, macd_histogram, standard_deviation, variance, skewness, kurtosis, signal, signal_strength, custom_metrics, created_at FROM metrics
WHERE session_id = $1
  AND (rsi_14 > 70 OR rsi_14 < 30)
ORDER BY timestamp ASC
`

// =============================================================================
// ANALYSIS Operations
// =============================================================================
func (q *Queries) GetMetricsRSIExtremes(ctx context.Context, sessionID int64) ([]Metric, error) {
	rows, err := q.db.Query(ctx, getMetricsRSIExtremes, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Metric
	for rows.Next() {
		var i Metric
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Timestamp,
			&i.CurrentPrice,
			&i.PriceChange,
			&i.PriceChangePercent,
			&i.SessionHigh,
			&i.SessionLow,
			&i.SessionOpen,
			&i.RealizedVolatility,
			&i.Volatility1min,
			&i.Volatility5min,
			&i.Volatility1hour,
			&i.Volume,
			&i.VolumeMa5,
			&i.VolumeMa20,
			&i.DrawdownPercent,
			&i.MaxDrawdownPercent,
			&i.ReturnPercent,
			&i.Sma10,
			&i.Sma20,
			&i.Sma50,
			&i.Sma200,
			&i.Ema10,
			&i.Ema20,
			&i.Rsi14,
			&i.Macd,
			&i.MacdSignal,
			&i.MacdHistogram,
			&i.StandardDeviation,
			&i.Variance,
			&i.Skewness,
			&i.Kurtosis,
			&i.Signal,
			&i.SignalStrength,
			&i.CustomMetrics,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMetricsSellSignals = `-- name: GetMetricsSellSignals :many
SELECT id, session_id, timestamp, current_price, price_change, price_change_percent, session_high, session_low, session_open, realized_volatility, volatility_1min, volatility_5min, volatility_1hour, volume, volume_ma_5, volume_ma_20, drawdown_percent, max_drawdown_percent, return_percent, sma_10, sma_20, sma_50, sma_200, ema_10, ema_20, rsi_14, macd, macd_signal, macd_histogram, standard_deviation, variance, skewness, kurtosis, signal, signal_strength, custom_metrics, created_at FROM metrics
WHERE session_id = $1
  AND signal = 'sell'
ORDER BY timestamp ASC
`

func (q *Queries) GetMetricsSellSignals(ctx context.Context, sessionID int64) ([]Metric, error) {
	rows, err := q.db.Query(ctx, getMetricsSellSignals, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Metric
	for rows.Next() {
		var i Metric
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Timestamp,
			&i.CurrentPrice,
			&i.PriceChange,
			&i.PriceChangePercent,
			&i.SessionHigh,
			&i.SessionLow,
			&i.SessionOpen,
			&i.RealizedVolatility,
			&i.Volatility1min,
			&i.Volatility5min,
			&i.Volatility1hour,
			&i.Volume,
			&i.VolumeMa5,
			&i.VolumeMa20,
			&i.DrawdownPercent,
			&i.MaxDrawdownPercent,
			&i.ReturnPercent,
			&i.Sma10,
			&i.Sma20,
			&i.Sma50,
			&i.Sma200,
			&i.Ema10,
			&i.Ema20,
			&i.Rsi14,
			&i.Macd,
			&i.MacdSignal,
			&i.MacdHistogram,
			&i.StandardDeviation,
			&i.Variance,
			&i.Skewness,
			&i.Kurtosis,
			&i.Signal,
			&i.SignalStrength,
			&i.CustomMetrics,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMetricsSignalDistribution = `-- name: GetMetricsSignalDistribution :many
SELECT 
    signal,
    COUNT(*) as signal_count,
    AVG(signal_strength) as avg_strength
FROM metrics
WHERE session_id = $1
  AND signal IS NOT NULL
GROUP BY signal
ORDER BY signal_count DESC
`

type GetMetricsSignalDistributionRow struct {
	Signal      pgtype.Text `json:"signal"`
	SignalCount int64       `json:"signal_count"`
	AvgStrength float64     `json:"avg_strength"`
}

func (q *Queries) GetMetricsSignalDistribution(ctx context.Context, sessionID int64) ([]GetMetricsSignalDistributionRow, error) {
	rows, err := q.db.Query(ctx, getMetricsSignalDistribution, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMetricsSignalDistributionRow
	for rows.Next() {
		var i GetMetricsSignalDistributionRow
		if err := rows.Scan(&i.Signal, &i.SignalCount, &i.AvgStrength); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMetricsStatsInRange = `-- name: GetMetricsStatsInRange :one
SELECT 
    COUNT(*) as data_points,
    AVG(current_price) as avg_price,
    STDDEV(current_price) as price_stddev,
    AVG(rsi_14) as avg_rsi,
    AVG(realized_volatility) as avg_volatility,
    COUNT(*) FILTER (WHERE signal = 'buy') as buy_signals,
    COUNT(*) FILTER (WHERE signal = 'sell') as sell_signals
FROM metrics
WHERE session_id = $1
  AND timestamp >= $2
  AND timestamp <= $3
`

type GetMetricsStatsInRangeParams struct {
	SessionID   int64 `json:"session_id"`
	Timestamp   int64 `json:"timestamp"`
	Timestamp_2 int64 `json:"timestamp_2"`
}

type GetMetricsStatsInRangeRow struct {
	DataPoints    int64   `json:"data_points"`
	AvgPrice      float64 `json:"avg_price"`
	PriceStddev   float64 `json:"price_stddev"`
	AvgRsi        float64 `json:"avg_rsi"`
	AvgVolatility float64 `json:"avg_volatility"`
	BuySignals    int64   `json:"buy_signals"`
	SellSignals   int64   `json:"sell_signals"`
}

func (q *Queries) GetMetricsStatsInRange(ctx context.Context, arg GetMetricsStatsInRangeParams) (GetMetricsStatsInRangeRow, error) {
	row := q.db.QueryRow(ctx, getMetricsStatsInRange, arg.SessionID, arg.Timestamp, arg.Timestamp_2)
	var i GetMetricsStatsInRangeRow
	err := row.Scan(
		&i.DataPoints,
		&i.AvgPrice,
		&i.PriceStddev,
		&i.AvgRsi,
		&i.AvgVolatility,
		&i.BuySignals,
		&i.SellSignals,
	)
	return i, err
}

const getMetricsSummary = `-- name: GetMetricsSummary :one
SELECT 
    COUNT(*) as total_metrics,
    MIN(current_price) as min_price,
    MAX(current_price) as max_price,
    AVG(current_price) as avg_price,
    MIN(rsi_14) as min_rsi,
    MAX(rsi_14) as max_rsi,
    AVG(rsi_14) as avg_rsi,
    AVG(realized_volatility) as avg_volatility,
    MAX(drawdown_percent) as max_drawdown,
    SUM(volume) as total_volume
FROM metrics
WHERE session_id = $1
`

type GetMetricsSummaryRow struct {
	TotalMetrics  int64       `json:"total_metrics"`
	MinPrice      interface{} `json:"min_price"`
	MaxPrice      interface{} `json:"max_price"`
	AvgPrice      float64     `json:"avg_price"`
	MinRsi        interface{} `json:"min_rsi"`
	MaxRsi        interface{} `json:"max_rsi"`
	AvgRsi        float64     `json:"avg_rsi"`
	AvgVolatility float64     `json:"avg_volatility"`
	MaxDrawdown   interface{} `json:"max_drawdown"`
	TotalVolume   int64       `json:"total_volume"`
}

func (q *Queries) GetMetricsSummary(ctx context.Context, sessionID int64) (GetMetricsSummaryRow, error) {
	row := q.db.QueryRow(ctx, getMetricsSummary, sessionID)
	var i GetMetricsSummaryRow
	err := row.Scan(
		&i.TotalMetrics,
		&i.MinPrice,
		&i.MaxPrice,
		&i.AvgPrice,
		&i.MinRsi,
		&i.MaxRsi,
		&i.AvgRsi,
		&i.AvgVolatility,
		&i.MaxDrawdown,
		&i.TotalVolume,
	)
	return i, err
}

const getMetricsWithSignal = `-- name: GetMetricsWithSignal :many
SELECT id, session_id, timestamp, current_price, price_change, price_change_percent, session_high, session_low, session_open, realized_volatility, volatility_1min, volatility_5min, volatility_1hour, volume, volume_ma_5, volume_ma_20, drawdown_percent, max_drawdown_percent, return_percent, sma_10, sma_20, sma_50, sma_200, ema_10, ema_20, rsi_14, macd, macd_signal, macd_histogram, standard_deviation, variance, skewness, kurtosis, signal, signal_strength, custom_metrics, created_at FROM metrics
WHERE session_id = $1
  AND signal = $2
ORDER BY timestamp DESC
LIMIT $3
`

type GetMetricsWithSignalParams struct {
	SessionID int64       `json:"session_id"`
	Signal    pgtype.Text `json:"signal"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) GetMetricsWithSignal(ctx context.Context, arg GetMetricsWithSignalParams) ([]Metric, error) {
	rows, err := q.db.Query(ctx, getMetricsWithSignal, arg.SessionID, arg.Signal, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Metric
	for rows.Next() {
		var i Metric
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Timestamp,
			&i.CurrentPrice,
			&i.PriceChange,
			&i.PriceChangePercent,
			&i.SessionHigh,
			&i.SessionLow,
			&i.SessionOpen,
			&i.RealizedVolatility,
			&i.Volatility1min,
			&i.Volatility5min,
			&i.Volatility1hour,
			&i.Volume,
			&i.VolumeMa5,
			&i.VolumeMa20,
			&i.DrawdownPercent,
			&i.MaxDrawdownPercent,
			&i.ReturnPercent,
			&i.Sma10,
			&i.Sma20,
			&i.Sma50,
			&i.Sma200,
			&i.Ema10,
			&i.Ema20,
			&i.Rsi14,
			&i.Macd,
			&i.MacdSignal,
			&i.MacdHistogram,
			&i.StandardDeviation,
			&i.Variance,
			&i.Skewness,
			&i.Kurtosis,
			&i.Signal,
			&i.SignalStrength,
			&i.CustomMetrics,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMovingAverages = `-- name: GetMovingAverages :many
SELECT 
    timestamp,
    current_price,
    sma_10,
    sma_20,
    sma_50,
    sma_200,
    ema_10,
    ema_20
FROM metrics
WHERE session_id = $1
  AND timestamp >= $2
  AND timestamp <= $3
ORDER BY timestamp ASC
`

type GetMovingAveragesParams struct {
	SessionID   int64 `json:"session_id"`
	Timestamp   int64 `json:"timestamp"`
	Timestamp_2 int64 `json:"timestamp_2"`
}

type GetMovingAveragesRow struct {
	Timestamp    int64          `json:"timestamp"`
	CurrentPrice pgtype.Numeric `json:"current_price"`
	Sma10        pgtype.Numeric `json:"sma_10"`
	Sma20        pgtype.Numeric `json:"sma_20"`
	Sma50        pgtype.Numeric `json:"sma_50"`
	Sma200       pgtype.Numeric `json:"sma_200"`
	Ema10        pgtype.Numeric `json:"ema_10"`
	Ema20        pgtype.Numeric `json:"ema_20"`
}

func (q *Queries) GetMovingAverages(ctx context.Context, arg GetMovingAveragesParams) ([]GetMovingAveragesRow, error) {
	rows, err := q.db.Query(ctx, getMovingAverages, arg.SessionID, arg.Timestamp, arg.Timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMovingAveragesRow
	for rows.Next() {
		var i GetMovingAveragesRow
		if err := rows.Scan(
			&i.Timestamp,
			&i.CurrentPrice,
			&i.Sma10,
			&i.Sma20,
			&i.Sma50,
			&i.Sma200,
			&i.Ema10,
			&i.Ema20,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPriceCrossovers = `-- name: GetPriceCrossovers :many
SELECT 
    m1.timestamp,
    m1.current_price,
    m1.sma_20,
    m1.sma_50,
    CASE 
        WHEN m1.sma_20 > m1.sma_50 AND m2.sma_20 <= m2.sma_50 THEN 'golden_cross'
        WHEN m1.sma_20 < m1.sma_50 AND m2.sma_20 >= m2.sma_50 THEN 'death_cross'
    END as crossover_type
FROM metrics m1
JOIN metrics m2 ON m2.session_id = m1.session_id 
    AND m2.timestamp < m1.timestamp
WHERE m1.session_id = $1
  AND m1.sma_20 IS NOT NULL
  AND m1.sma_50 IS NOT NULL
  AND m2.sma_20 IS NOT NULL
  AND m2.sma_50 IS NOT NULL
  AND (
      (m1.sma_20 > m1.sma_50 AND m2.sma_20 <= m2.sma_50) OR
      (m1.sma_20 < m1.sma_50 AND m2.sma_20 >= m2.sma_50)
  )
ORDER BY m1.timestamp ASC
`

type GetPriceCrossoversRow struct {
	Timestamp     int64          `json:"timestamp"`
	CurrentPrice  pgtype.Numeric `json:"current_price"`
	Sma20         pgtype.Numeric `json:"sma_20"`
	Sma50         pgtype.Numeric `json:"sma_50"`
	CrossoverType interface{}    `json:"crossover_type"`
}

func (q *Queries) GetPriceCrossovers(ctx context.Context, sessionID int64) ([]GetPriceCrossoversRow, error) {
	rows, err := q.db.Query(ctx, getPriceCrossovers, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPriceCrossoversRow
	for rows.Next() {
		var i GetPriceCrossoversRow
		if err := rows.Scan(
			&i.Timestamp,
			&i.CurrentPrice,
			&i.Sma20,
			&i.Sma50,
			&i.CrossoverType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPriceMovementStats = `-- name: GetPriceMovementStats :one
SELECT 
    AVG(price_change) as avg_price_change,
    STDDEV(price_change) as price_change_stddev,
    MAX(price_change) as max_price_increase,
    MIN(price_change) as max_price_decrease,
    AVG(ABS(price_change)) as avg_absolute_change
FROM metrics
WHERE session_id = $1
`

type GetPriceMovementStatsRow struct {
	AvgPriceChange    float64     `json:"avg_price_change"`
	PriceChangeStddev float64     `json:"price_change_stddev"`
	MaxPriceIncrease  interface{} `json:"max_price_increase"`
	MaxPriceDecrease  interface{} `json:"max_price_decrease"`
	AvgAbsoluteChange float64     `json:"avg_absolute_change"`
}

func (q *Queries) GetPriceMovementStats(ctx context.Context, sessionID int64) (GetPriceMovementStatsRow, error) {
	row := q.db.QueryRow(ctx, getPriceMovementStats, sessionID)
	var i GetPriceMovementStatsRow
	err := row.Scan(
		&i.AvgPriceChange,
		&i.PriceChangeStddev,
		&i.MaxPriceIncrease,
		&i.MaxPriceDecrease,
		&i.AvgAbsoluteChange,
	)
	return i, err
}

const getPriceSeries = `-- name: GetPriceSeries :many

SELECT 
    timestamp,
    current_price
FROM metrics
WHERE session_id = $1
  AND timestamp >= $2
  AND timestamp <= $3
ORDER BY timestamp ASC
`

type GetPriceSeriesParams struct {
	SessionID   int64 `json:"session_id"`
	Timestamp   int64 `json:"timestamp"`
	Timestamp_2 int64 `json:"timestamp_2"`
}

type GetPriceSeriesRow struct {
	Timestamp    int64          `json:"timestamp"`
	CurrentPrice pgtype.Numeric `json:"current_price"`
}

// =============================================================================
// TIME SERIES Operations
// =============================================================================
func (q *Queries) GetPriceSeries(ctx context.Context, arg GetPriceSeriesParams) ([]GetPriceSeriesRow, error) {
	rows, err := q.db.Query(ctx, getPriceSeries, arg.SessionID, arg.Timestamp, arg.Timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPriceSeriesRow
	for rows.Next() {
		var i GetPriceSeriesRow
		if err := rows.Scan(&i.Timestamp, &i.CurrentPrice); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRSISeries = `-- name: GetRSISeries :many
SELECT 
    timestamp,
    rsi_14
FROM metrics
WHERE session_id = $1
  AND timestamp >= $2
  AND timestamp <= $3
ORDER BY timestamp ASC
`

type GetRSISeriesParams struct {
	SessionID   int64 `json:"session_id"`
	Timestamp   int64 `json:"timestamp"`
	Timestamp_2 int64 `json:"timestamp_2"`
}

type GetRSISeriesRow struct {
	Timestamp int64          `json:"timestamp"`
	Rsi14     pgtype.Numeric `json:"rsi_14"`
}

func (q *Queries) GetRSISeries(ctx context.Context, arg GetRSISeriesParams) ([]GetRSISeriesRow, error) {
	rows, err := q.db.Query(ctx, getRSISeries, arg.SessionID, arg.Timestamp, arg.Timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRSISeriesRow
	for rows.Next() {
		var i GetRSISeriesRow
		if err := rows.Scan(&i.Timestamp, &i.Rsi14); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentMetrics = `-- name: GetRecentMetrics :many
SELECT id, session_id, timestamp, current_price, price_change, price_change_percent, session_high, session_low, session_open, realized_volatility, volatility_1min, volatility_5min, volatility_1hour, volume, volume_ma_5, volume_ma_20, drawdown_percent, max_drawdown_percent, return_percent, sma_10, sma_20, sma_50, sma_200, ema_10, ema_20, rsi_14, macd, macd_signal, macd_histogram, standard_deviation, variance, skewness, kurtosis, signal, signal_strength, custom_metrics, created_at FROM metrics
WHERE session_id = $1
ORDER BY timestamp DESC
LIMIT $2
`

type GetRecentMetricsParams struct {
	SessionID int64 `json:"session_id"`
	Limit     int32 `json:"limit"`
}

func (q *Queries) GetRecentMetrics(ctx context.Context, arg GetRecentMetricsParams) ([]Metric, error) {
	rows, err := q.db.Query(ctx, getRecentMetrics, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Metric
	for rows.Next() {
		var i Metric
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Timestamp,
			&i.CurrentPrice,
			&i.PriceChange,
			&i.PriceChangePercent,
			&i.SessionHigh,
			&i.SessionLow,
			&i.SessionOpen,
			&i.RealizedVolatility,
			&i.Volatility1min,
			&i.Volatility5min,
			&i.Volatility1hour,
			&i.Volume,
			&i.VolumeMa5,
			&i.VolumeMa20,
			&i.DrawdownPercent,
			&i.MaxDrawdownPercent,
			&i.ReturnPercent,
			&i.Sma10,
			&i.Sma20,
			&i.Sma50,
			&i.Sma200,
			&i.Ema10,
			&i.Ema20,
			&i.Rsi14,
			&i.Macd,
			&i.MacdSignal,
			&i.MacdHistogram,
			&i.StandardDeviation,
			&i.Variance,
			&i.Skewness,
			&i.Kurtosis,
			&i.Signal,
			&i.SignalStrength,
			&i.CustomMetrics,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentPerformance = `-- name: GetRecentPerformance :one
SELECT 
    COUNT(*) as period_count,
    (MAX(current_price) - MIN(current_price)) / MIN(current_price) * 100 as period_return,
    AVG(realized_volatility) as period_volatility,
    MAX(drawdown_percent) as period_max_drawdown
FROM metrics
WHERE session_id = $1
  AND timestamp >= $2
`

type GetRecentPerformanceParams struct {
	SessionID int64 `json:"session_id"`
	Timestamp int64 `json:"timestamp"`
}

type GetRecentPerformanceRow struct {
	PeriodCount       int64       `json:"period_count"`
	PeriodReturn      int32       `json:"period_return"`
	PeriodVolatility  float64     `json:"period_volatility"`
	PeriodMaxDrawdown interface{} `json:"period_max_drawdown"`
}

func (q *Queries) GetRecentPerformance(ctx context.Context, arg GetRecentPerformanceParams) (GetRecentPerformanceRow, error) {
	row := q.db.QueryRow(ctx, getRecentPerformance, arg.SessionID, arg.Timestamp)
	var i GetRecentPerformanceRow
	err := row.Scan(
		&i.PeriodCount,
		&i.PeriodReturn,
		&i.PeriodVolatility,
		&i.PeriodMaxDrawdown,
	)
	return i, err
}

const getVolatilityStats = `-- name: GetVolatilityStats :one
SELECT 
    AVG(realized_volatility) as avg_realized_volatility,
    MAX(realized_volatility) as max_realized_volatility,
    MIN(realized_volatility) as min_realized_volatility,
    STDDEV(realized_volatility) as volatility_stddev
FROM metrics
WHERE session_id = $1
`

type GetVolatilityStatsRow struct {
	AvgRealizedVolatility float64     `json:"avg_realized_volatility"`
	MaxRealizedVolatility interface{} `json:"max_realized_volatility"`
	MinRealizedVolatility interface{} `json:"min_realized_volatility"`
	VolatilityStddev      float64     `json:"volatility_stddev"`
}

func (q *Queries) GetVolatilityStats(ctx context.Context, sessionID int64) (GetVolatilityStatsRow, error) {
	row := q.db.QueryRow(ctx, getVolatilityStats, sessionID)
	var i GetVolatilityStatsRow
	err := row.Scan(
		&i.AvgRealizedVolatility,
		&i.MaxRealizedVolatility,
		&i.MinRealizedVolatility,
		&i.VolatilityStddev,
	)
	return i, err
}

const getVolumeSeries = `-- name: GetVolumeSeries :many
SELECT 
    timestamp,
    volume,
    volume_ma_5,
    volume_ma_20
FROM metrics
WHERE session_id = $1
  AND timestamp >= $2
  AND timestamp <= $3
ORDER BY timestamp ASC
`

type GetVolumeSeriesParams struct {
	SessionID   int64 `json:"session_id"`
	Timestamp   int64 `json:"timestamp"`
	Timestamp_2 int64 `json:"timestamp_2"`
}

type GetVolumeSeriesRow struct {
	Timestamp  int64          `json:"timestamp"`
	Volume     pgtype.Numeric `json:"volume"`
	VolumeMa5  pgtype.Numeric `json:"volume_ma_5"`
	VolumeMa20 pgtype.Numeric `json:"volume_ma_20"`
}

func (q *Queries) GetVolumeSeries(ctx context.Context, arg GetVolumeSeriesParams) ([]GetVolumeSeriesRow, error) {
	rows, err := q.db.Query(ctx, getVolumeSeries, arg.SessionID, arg.Timestamp, arg.Timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVolumeSeriesRow
	for rows.Next() {
		var i GetVolumeSeriesRow
		if err := rows.Scan(
			&i.Timestamp,
			&i.Volume,
			&i.VolumeMa5,
			&i.VolumeMa20,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMetric = `-- name: UpdateMetric :one

UPDATE metrics
SET 
    current_price = $3,
    price_change = $4,
    price_change_percent = $5,
    rsi_14 = $6,
    macd = $7,
    signal = $8
WHERE session_id = $1
  AND timestamp = $2
RETURNING id, session_id, timestamp, current_price, price_change, price_change_percent, session_high, session_low, session_open, realized_volatility, volatility_1min, volatility_5min, volatility_1hour, volume, volume_ma_5, volume_ma_20, drawdown_percent, max_drawdown_percent, return_percent, sma_10, sma_20, sma_50, sma_200, ema_10, ema_20, rsi_14, macd, macd_signal, macd_histogram, standard_deviation, variance, skewness, kurtosis, signal, signal_strength, custom_metrics, created_at
`

type UpdateMetricParams struct {
	SessionID          int64          `json:"session_id"`
	Timestamp          int64          `json:"timestamp"`
	CurrentPrice       pgtype.Numeric `json:"current_price"`
	PriceChange        pgtype.Numeric `json:"price_change"`
	PriceChangePercent pgtype.Numeric `json:"price_change_percent"`
	Rsi14              pgtype.Numeric `json:"rsi_14"`
	Macd               pgtype.Numeric `json:"macd"`
	Signal             pgtype.Text    `json:"signal"`
}

// =============================================================================
// UPDATE Operations
// =============================================================================
func (q *Queries) UpdateMetric(ctx context.Context, arg UpdateMetricParams) (Metric, error) {
	row := q.db.QueryRow(ctx, updateMetric,
		arg.SessionID,
		arg.Timestamp,
		arg.CurrentPrice,
		arg.PriceChange,
		arg.PriceChangePercent,
		arg.Rsi14,
		arg.Macd,
		arg.Signal,
	)
	var i Metric
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Timestamp,
		&i.CurrentPrice,
		&i.PriceChange,
		&i.PriceChangePercent,
		&i.SessionHigh,
		&i.SessionLow,
		&i.SessionOpen,
		&i.RealizedVolatility,
		&i.Volatility1min,
		&i.Volatility5min,
		&i.Volatility1hour,
		&i.Volume,
		&i.VolumeMa5,
		&i.VolumeMa20,
		&i.DrawdownPercent,
		&i.MaxDrawdownPercent,
		&i.ReturnPercent,
		&i.Sma10,
		&i.Sma20,
		&i.Sma50,
		&i.Sma200,
		&i.Ema10,
		&i.Ema20,
		&i.Rsi14,
		&i.Macd,
		&i.MacdSignal,
		&i.MacdHistogram,
		&i.StandardDeviation,
		&i.Variance,
		&i.Skewness,
		&i.Kurtosis,
		&i.Signal,
		&i.SignalStrength,
		&i.CustomMetrics,
		&i.CreatedAt,
	)
	return i, err
}

const updateMetricSignal = `-- name: UpdateMetricSignal :exec
UPDATE metrics
SET 
    signal = $2,
    signal_strength = $3
WHERE id = $1
`

type UpdateMetricSignalParams struct {
	ID             int64          `json:"id"`
	Signal         pgtype.Text    `json:"signal"`
	SignalStrength pgtype.Numeric `json:"signal_strength"`
}

func (q *Queries) UpdateMetricSignal(ctx context.Context, arg UpdateMetricSignalParams) error {
	_, err := q.db.Exec(ctx, updateMetricSignal, arg.ID, arg.Signal, arg.SignalStrength)
	return err
}
