// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Stores OHLC candlestick data for all symbols and timeframes
type Candle struct {
	ID int64 `json:"id"`
	// Trading symbol (e.g., BTC, AAPL, EURUSD)
	Symbol string `json:"symbol"`
	// Candle interval (e.g., 1m, 5m, 15m, 1h, 1d)
	Timeframe string `json:"timeframe"`
	// Unix timestamp in seconds representing candle open time
	Timestamp int64 `json:"timestamp"`
	// Opening price for the time period
	Open pgtype.Numeric `json:"open"`
	// Highest price during the time period
	High pgtype.Numeric `json:"high"`
	// Lowest price during the time period
	Low pgtype.Numeric `json:"low"`
	// Closing price for the time period
	Close pgtype.Numeric `json:"close"`
	// Total volume traded during the time period
	Volume    pgtype.Numeric     `json:"volume"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Stores simulation configuration presets and user preferences
type Config struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Strategy    string      `json:"strategy"`
	// Price volatility coefficient (0.02 = 2% standard deviation)
	Volatility pgtype.Numeric `json:"volatility"`
	// Price drift/trend direction (-1 to 1, negative=bearish, positive=bullish)
	Drift          pgtype.Numeric `json:"drift"`
	StartingPrice  pgtype.Numeric `json:"starting_price"`
	CandleInterval string         `json:"candle_interval"`
	Symbol         string         `json:"symbol"`
	MarketBehavior pgtype.Text    `json:"market_behavior"`
	// Strength of trending behavior (0-1)
	TrendStrength pgtype.Numeric `json:"trend_strength"`
	// How quickly prices revert to mean (0-1, higher = faster)
	MeanReversionSpeed pgtype.Numeric `json:"mean_reversion_speed"`
	// Additional parameters in JSON format for extensibility
	AdvancedParams []byte `json:"advanced_params"`
	// Whether this is the default configuration (only one can be true)
	IsDefault  pgtype.Bool        `json:"is_default"`
	IsFavorite pgtype.Bool        `json:"is_favorite"`
	IsPublic   pgtype.Bool        `json:"is_public"`
	TimesUsed  pgtype.Int4        `json:"times_used"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedBy  pgtype.Text        `json:"created_by"`
	Tags       []string           `json:"tags"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// Tracks significant market events, alerts, and user markers during simulations
type Event struct {
	ID        int64       `json:"id"`
	SessionID int64       `json:"session_id"`
	CandleID  pgtype.Int8 `json:"candle_id"`
	// Type of event (spike, crash, breakout, consolidation, volume_spike, ma_cross, signal_generated, etc.)
	EventType string `json:"event_type"`
	// Broad category for grouping events (market, technical, system, user, alert)
	EventCategory pgtype.Text `json:"event_category"`
	Title         string      `json:"title"`
	Description   pgtype.Text `json:"description"`
	Timestamp     int64       `json:"timestamp"`
	// How long the event lasted (NULL for instantaneous events)
	DurationSeconds pgtype.Int4 `json:"duration_seconds"`
	// Importance level of the event
	Severity pgtype.Text `json:"severity"`
	// Normalized score (0-1) indicating event impact magnitude
	ImpactScore        pgtype.Numeric `json:"impact_score"`
	PriceAtEvent       pgtype.Numeric `json:"price_at_event"`
	PriceBefore        pgtype.Numeric `json:"price_before"`
	PriceAfter         pgtype.Numeric `json:"price_after"`
	PriceChangePercent pgtype.Numeric `json:"price_change_percent"`
	VolumeAtEvent      pgtype.Numeric `json:"volume_at_event"`
	// Ratio of current volume to average (e.g., 2.5 = 250% of normal)
	VolumeSpikeRatio pgtype.Numeric `json:"volume_spike_ratio"`
	// What caused this event (indicator name, system component, user action)
	TriggeredBy pgtype.Text `json:"triggered_by"`
	// JSON object with conditions that triggered the event
	TriggerConditions []byte   `json:"trigger_conditions"`
	Tags              []string `json:"tags"`
	// Snapshot of indicator values when event occurred
	IndicatorsAtEvent []byte `json:"indicators_at_event"`
	// Flexible field for event-specific data
	AdditionalData []byte             `json:"additional_data"`
	IsUserMarked   pgtype.Bool        `json:"is_user_marked"`
	UserNotes      pgtype.Text        `json:"user_notes"`
	IsAcknowledged pgtype.Bool        `json:"is_acknowledged"`
	AcknowledgedAt pgtype.Timestamptz `json:"acknowledged_at"`
	Status         pgtype.Text        `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// Stores calculated technical indicators for each candle
type Indicator struct {
	ID       int64 `json:"id"`
	CandleID int64 `json:"candle_id"`
	// Type of indicator (SMA, EMA, RSI, MACD, BB, STOCH, ADX, etc.)
	IndicatorType string `json:"indicator_type"`
	// Primary indicator value
	Value pgtype.Numeric `json:"value"`
	// Upper band/line (e.g., Bollinger upper band)
	ValueUpper pgtype.Numeric `json:"value_upper"`
	// Lower band/line (e.g., Bollinger lower band)
	ValueLower pgtype.Numeric `json:"value_lower"`
	// Middle line (e.g., Bollinger middle band/SMA)
	ValueMiddle pgtype.Numeric `json:"value_middle"`
	// Signal line for indicators like MACD
	SignalLine pgtype.Numeric `json:"signal_line"`
	// Histogram value (e.g., MACD histogram)
	Histogram pgtype.Numeric `json:"histogram"`
	// Period used for calculation (e.g., 14 for RSI-14)
	Period pgtype.Int4 `json:"period"`
	// Fast period for dual-period indicators (e.g., MACD fast)
	PeriodFast pgtype.Int4 `json:"period_fast"`
	// Slow period for dual-period indicators (e.g., MACD slow)
	PeriodSlow   pgtype.Int4 `json:"period_slow"`
	PeriodSignal pgtype.Int4 `json:"period_signal"`
	// Standard deviations for Bollinger Bands
	StandardDeviations pgtype.Numeric `json:"standard_deviations"`
	Signal             pgtype.Text    `json:"signal"`
	SignalStrength     pgtype.Numeric `json:"signal_strength"`
	IsCrossover        pgtype.Bool    `json:"is_crossover"`
	// Type of crossover event detected
	CrossoverType pgtype.Text `json:"crossover_type"`
	// Additional indicator-specific data in JSON format
	Metadata     []byte             `json:"metadata"`
	CalculatedAt pgtype.Timestamptz `json:"calculated_at"`
}

// Stores calculated metrics and analytics for each point in a session
type Metric struct {
	ID                 int64          `json:"id"`
	SessionID          int64          `json:"session_id"`
	Timestamp          int64          `json:"timestamp"`
	CurrentPrice       pgtype.Numeric `json:"current_price"`
	PriceChange        pgtype.Numeric `json:"price_change"`
	PriceChangePercent pgtype.Numeric `json:"price_change_percent"`
	SessionHigh        pgtype.Numeric `json:"session_high"`
	SessionLow         pgtype.Numeric `json:"session_low"`
	SessionOpen        pgtype.Numeric `json:"session_open"`
	// Actual measured volatility over the period
	RealizedVolatility pgtype.Numeric `json:"realized_volatility"`
	Volatility1min     pgtype.Numeric `json:"volatility_1min"`
	Volatility5min     pgtype.Numeric `json:"volatility_5min"`
	Volatility1hour    pgtype.Numeric `json:"volatility_1hour"`
	Volume             pgtype.Numeric `json:"volume"`
	VolumeMa5          pgtype.Numeric `json:"volume_ma_5"`
	VolumeMa20         pgtype.Numeric `json:"volume_ma_20"`
	// Current drawdown from session high
	DrawdownPercent pgtype.Numeric `json:"drawdown_percent"`
	// Maximum drawdown experienced in session so far
	MaxDrawdownPercent pgtype.Numeric `json:"max_drawdown_percent"`
	ReturnPercent      pgtype.Numeric `json:"return_percent"`
	Sma10              pgtype.Numeric `json:"sma_10"`
	Sma20              pgtype.Numeric `json:"sma_20"`
	Sma50              pgtype.Numeric `json:"sma_50"`
	Sma200             pgtype.Numeric `json:"sma_200"`
	Ema10              pgtype.Numeric `json:"ema_10"`
	Ema20              pgtype.Numeric `json:"ema_20"`
	// Relative Strength Index (14 period)
	Rsi14 pgtype.Numeric `json:"rsi_14"`
	// Moving Average Convergence Divergence indicator
	Macd              pgtype.Numeric `json:"macd"`
	MacdSignal        pgtype.Numeric `json:"macd_signal"`
	MacdHistogram     pgtype.Numeric `json:"macd_histogram"`
	StandardDeviation pgtype.Numeric `json:"standard_deviation"`
	Variance          pgtype.Numeric `json:"variance"`
	Skewness          pgtype.Numeric `json:"skewness"`
	Kurtosis          pgtype.Numeric `json:"kurtosis"`
	Signal            pgtype.Text    `json:"signal"`
	// Confidence level of the signal (0-1)
	SignalStrength pgtype.Numeric `json:"signal_strength"`
	// Additional user-defined or strategy-specific metrics
	CustomMetrics []byte             `json:"custom_metrics"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

// Tracks individual simulation sessions and their outcomes
type Session struct {
	ID          int64  `json:"id"`
	SessionName string `json:"session_name"`
	Symbol      string `json:"symbol"`
	Timeframe   string `json:"timeframe"`
	// Simulation strategy used (random_walk, trending, volatile, mean_reverting)
	Strategy  string             `json:"strategy"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	EndedAt   pgtype.Timestamptz `json:"ended_at"`
	// Total duration of the session in seconds
	DurationSeconds    pgtype.Int4    `json:"duration_seconds"`
	StartingPrice      pgtype.Numeric `json:"starting_price"`
	EndingPrice        pgtype.Numeric `json:"ending_price"`
	HighestPrice       pgtype.Numeric `json:"highest_price"`
	LowestPrice        pgtype.Numeric `json:"lowest_price"`
	TotalCandles       pgtype.Int4    `json:"total_candles"`
	PriceChangePercent pgtype.Numeric `json:"price_change_percent"`
	Volatility         pgtype.Numeric `json:"volatility"`
	// JSON object containing strategy-specific parameters (volatility, drift, etc.)
	Parameters []byte      `json:"parameters"`
	Status     pgtype.Text `json:"status"`
	Notes      pgtype.Text `json:"notes"`
	// Array of tags for categorizing sessions
	Tags       []string           `json:"tags"`
	IsFavorite pgtype.Bool        `json:"is_favorite"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// Quick view of unacknowledged high-priority events requiring attention
type VActiveCriticalEvent struct {
	ID                 int64              `json:"id"`
	SessionID          int64              `json:"session_id"`
	SessionName        string             `json:"session_name"`
	Symbol             string             `json:"symbol"`
	EventType          string             `json:"event_type"`
	EventCategory      pgtype.Text        `json:"event_category"`
	Title              string             `json:"title"`
	Severity           pgtype.Text        `json:"severity"`
	PriceAtEvent       pgtype.Numeric     `json:"price_at_event"`
	PriceChangePercent pgtype.Numeric     `json:"price_change_percent"`
	Timestamp          int64              `json:"timestamp"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	IsAcknowledged     pgtype.Bool        `json:"is_acknowledged"`
}

// Denormalized view of candles with common indicators for easy querying
type VCandlesWithIndicator struct {
	CandleID      int64          `json:"candle_id"`
	Symbol        string         `json:"symbol"`
	Timeframe     string         `json:"timeframe"`
	Timestamp     int64          `json:"timestamp"`
	Open          pgtype.Numeric `json:"open"`
	High          pgtype.Numeric `json:"high"`
	Low           pgtype.Numeric `json:"low"`
	Close         pgtype.Numeric `json:"close"`
	Volume        pgtype.Numeric `json:"volume"`
	Sma20         interface{}    `json:"sma_20"`
	Sma50         interface{}    `json:"sma_50"`
	Ema12         interface{}    `json:"ema_12"`
	Ema26         interface{}    `json:"ema_26"`
	Rsi14         interface{}    `json:"rsi_14"`
	Macd          interface{}    `json:"macd"`
	MacdSignal    interface{}    `json:"macd_signal"`
	MacdHistogram interface{}    `json:"macd_histogram"`
	BbUpper       interface{}    `json:"bb_upper"`
	BbMiddle      interface{}    `json:"bb_middle"`
	BbLower       interface{}    `json:"bb_lower"`
}

// Aggregated event statistics per simulation session
type VEventSummaryBySession struct {
	SessionID          int64       `json:"session_id"`
	TotalEvents        int64       `json:"total_events"`
	CriticalEvents     int64       `json:"critical_events"`
	HighEvents         int64       `json:"high_events"`
	MediumEvents       int64       `json:"medium_events"`
	LowEvents          int64       `json:"low_events"`
	MarketEvents       int64       `json:"market_events"`
	TechnicalEvents    int64       `json:"technical_events"`
	UserEvents         int64       `json:"user_events"`
	UserMarkedCount    int64       `json:"user_marked_count"`
	AvgImpactScore     float64     `json:"avg_impact_score"`
	LastEventTimestamp interface{} `json:"last_event_timestamp"`
}
