// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcknowledgeAllEvents(ctx context.Context, sessionID int64) error
	AcknowledgeEvent(ctx context.Context, id int64) error
	AddConfigTag(ctx context.Context, arg AddConfigTagParams) error
	AddEventTag(ctx context.Context, arg AddEventTagParams) error
	AddSessionTag(ctx context.Context, arg AddSessionTagParams) error
	ArchiveOldEvents(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error)
	CheckCandleExists(ctx context.Context, arg CheckCandleExistsParams) (bool, error)
	// =============================================================================
	// UTILITY Operations
	// =============================================================================
	CheckConfigExists(ctx context.Context, id int64) (bool, error)
	CheckConfigNameExists(ctx context.Context, name string) (bool, error)
	// =============================================================================
	// UTILITY Operations
	// =============================================================================
	CheckEventExists(ctx context.Context, id int64) (bool, error)
	CheckIndicatorExists(ctx context.Context, arg CheckIndicatorExistsParams) (bool, error)
	CheckMetricExists(ctx context.Context, arg CheckMetricExistsParams) (bool, error)
	// =============================================================================
	// UTILITY Operations
	// =============================================================================
	CheckSessionExists(ctx context.Context, id int64) (bool, error)
	// =============================================================================
	// AGGREGATE Operations
	// =============================================================================
	CountCandles(ctx context.Context, arg CountCandlesParams) (int64, error)
	CountCandlesInRange(ctx context.Context, arg CountCandlesInRangeParams) (int64, error)
	// =============================================================================
	// AGGREGATE Operations
	// =============================================================================
	CountConfigs(ctx context.Context) (int64, error)
	CountConfigsByStrategy(ctx context.Context, strategy string) (int64, error)
	// =============================================================================
	// AGGREGATE Operations
	// =============================================================================
	CountEvents(ctx context.Context, sessionID int64) (int64, error)
	CountEventsBySeverity(ctx context.Context, arg CountEventsBySeverityParams) (int64, error)
	CountEventsByType(ctx context.Context, arg CountEventsByTypeParams) (int64, error)
	// =============================================================================
	// AGGREGATE Operations
	// =============================================================================
	CountIndicators(ctx context.Context, candleID int64) (int64, error)
	CountIndicatorsByType(ctx context.Context, indicatorType string) (int64, error)
	// =============================================================================
	// AGGREGATE Operations
	// =============================================================================
	CountMetrics(ctx context.Context, sessionID int64) (int64, error)
	// =============================================================================
	// AGGREGATE Operations
	// =============================================================================
	CountSessions(ctx context.Context) (int64, error)
	CountSessionsByStatus(ctx context.Context, status pgtype.Text) (int64, error)
	CountUnacknowledgedEvents(ctx context.Context, sessionID int64) (int64, error)
	// Candles Queries
	// CRUD operations and queries for OHLC candlestick data
	// =============================================================================
	// CREATE Operations
	// =============================================================================
	CreateCandle(ctx context.Context, arg CreateCandleParams) (Candle, error)
	CreateCandleBatch(ctx context.Context, arg []CreateCandleBatchParams) (int64, error)
	// Configs Queries
	// CRUD operations and queries for simulation configurations
	// =============================================================================
	// CREATE Operations
	// =============================================================================
	CreateConfig(ctx context.Context, arg CreateConfigParams) (Config, error)
	// Events Queries
	// CRUD operations and queries for market events and alerts
	// =============================================================================
	// CREATE Operations
	// =============================================================================
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateEventSimple(ctx context.Context, arg CreateEventSimpleParams) (Event, error)
	// Indicators Queries
	// CRUD operations and queries for technical indicators
	// =============================================================================
	// CREATE Operations
	// =============================================================================
	CreateIndicator(ctx context.Context, arg CreateIndicatorParams) (Indicator, error)
	CreateIndicatorBatch(ctx context.Context, arg []CreateIndicatorBatchParams) (int64, error)
	// Metrics Queries
	// CRUD operations and queries for session analytics and metrics
	// =============================================================================
	// CREATE Operations
	// =============================================================================
	CreateMetric(ctx context.Context, arg CreateMetricParams) (Metric, error)
	CreateMetricBatch(ctx context.Context, arg []CreateMetricBatchParams) (int64, error)
	// Sessions Queries
	// CRUD operations and queries for simulation sessions
	// =============================================================================
	// CREATE Operations
	// =============================================================================
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteArchivedEvents(ctx context.Context, createdAt pgtype.Timestamptz) error
	// =============================================================================
	// DELETE Operations
	// =============================================================================
	DeleteCandle(ctx context.Context, id int64) error
	DeleteCandlesBySymbol(ctx context.Context, symbol string) error
	DeleteCandlesByTimeframe(ctx context.Context, arg DeleteCandlesByTimeframeParams) error
	DeleteCandlesInRange(ctx context.Context, arg DeleteCandlesInRangeParams) error
	// =============================================================================
	// DELETE Operations
	// =============================================================================
	DeleteConfig(ctx context.Context, id int64) error
	DeleteDismissedEvents(ctx context.Context, createdAt pgtype.Timestamptz) error
	// =============================================================================
	// DELETE Operations
	// =============================================================================
	DeleteEvent(ctx context.Context, id int64) error
	DeleteEventsBySession(ctx context.Context, sessionID int64) error
	// =============================================================================
	// DELETE Operations
	// =============================================================================
	DeleteIndicator(ctx context.Context, id int64) error
	DeleteIndicatorsByCandle(ctx context.Context, candleID int64) error
	DeleteIndicatorsByType(ctx context.Context, indicatorType string) error
	// =============================================================================
	// DELETE Operations
	// =============================================================================
	DeleteMetric(ctx context.Context, id int64) error
	DeleteMetricsBySession(ctx context.Context, sessionID int64) error
	DeleteOldCandles(ctx context.Context, timestamp int64) error
	DeleteOldIndicators(ctx context.Context, calculatedAt pgtype.Timestamptz) error
	DeleteOldMetrics(ctx context.Context, createdAt pgtype.Timestamptz) error
	DeleteOldSessions(ctx context.Context, endedAt pgtype.Timestamptz) error
	// =============================================================================
	// DELETE Operations
	// =============================================================================
	DeleteSession(ctx context.Context, id int64) error
	DeleteSessionsByStatus(ctx context.Context, status pgtype.Text) error
	DeleteUnusedConfigs(ctx context.Context, createdAt pgtype.Timestamptz) error
	DismissEvent(ctx context.Context, id int64) error
	DuplicateConfig(ctx context.Context, arg DuplicateConfigParams) (Config, error)
	GetActiveEvents(ctx context.Context, sessionID int64) ([]Event, error)
	GetActiveSessions(ctx context.Context) ([]Session, error)
	GetBollingerBands(ctx context.Context, arg GetBollingerBandsParams) ([]GetBollingerBandsRow, error)
	GetBollingerBreakouts(ctx context.Context, arg GetBollingerBreakoutsParams) ([]GetBollingerBreakoutsRow, error)
	GetBreakoutEvents(ctx context.Context, arg GetBreakoutEventsParams) ([]Event, error)
	// =============================================================================
	// SIGNAL Operations
	// =============================================================================
	GetBuySignals(ctx context.Context, arg GetBuySignalsParams) ([]GetBuySignalsRow, error)
	GetCandle(ctx context.Context, arg GetCandleParams) (Candle, error)
	// =============================================================================
	// READ Operations
	// =============================================================================
	GetCandleByID(ctx context.Context, id int64) (Candle, error)
	GetCandleGaps(ctx context.Context, arg GetCandleGapsParams) ([]GetCandleGapsRow, error)
	GetCandleStats(ctx context.Context, arg GetCandleStatsParams) (GetCandleStatsRow, error)
	GetCandleStatsInRange(ctx context.Context, arg GetCandleStatsInRangeParams) (GetCandleStatsInRangeRow, error)
	GetCandlesAfterTimestamp(ctx context.Context, arg GetCandlesAfterTimestampParams) ([]Candle, error)
	GetCandlesBeforeTimestamp(ctx context.Context, arg GetCandlesBeforeTimestampParams) ([]Candle, error)
	GetCandlesBySymbols(ctx context.Context, arg GetCandlesBySymbolsParams) ([]Candle, error)
	GetCandlesInRange(ctx context.Context, arg GetCandlesInRangeParams) ([]Candle, error)
	GetCompletedSessions(ctx context.Context, limit int32) ([]Session, error)
	// =============================================================================
	// READ Operations
	// =============================================================================
	GetConfigByID(ctx context.Context, id int64) (Config, error)
	GetConfigByName(ctx context.Context, name string) (Config, error)
	GetConfigByNameOrDefault(ctx context.Context, name string) (Config, error)
	GetConfigStats(ctx context.Context) (GetConfigStatsRow, error)
	GetConfigsByCreator(ctx context.Context, createdBy pgtype.Text) ([]Config, error)
	GetConfigsByMarketBehavior(ctx context.Context, marketBehavior pgtype.Text) ([]Config, error)
	GetConfigsByStrategy(ctx context.Context, strategy string) ([]Config, error)
	GetConfigsWithTags(ctx context.Context, arg GetConfigsWithTagsParams) ([]Config, error)
	GetCriticalEvents(ctx context.Context, sessionID int64) ([]Event, error)
	GetCriticalEventsNeedingAction(ctx context.Context, sessionID int64) ([]Event, error)
	GetCrossoverFrequency(ctx context.Context) ([]GetCrossoverFrequencyRow, error)
	// =============================================================================
	// CROSSOVER Operations
	// =============================================================================
	GetCrossovers(ctx context.Context, arg GetCrossoversParams) ([]GetCrossoversRow, error)
	GetDailySessionCount(ctx context.Context, startedAt pgtype.Timestamptz) ([]GetDailySessionCountRow, error)
	GetDeathCrosses(ctx context.Context, arg GetDeathCrossesParams) ([]GetDeathCrossesRow, error)
	GetDefaultConfig(ctx context.Context) (Config, error)
	GetDistinctEventCategories(ctx context.Context) ([]pgtype.Text, error)
	GetDistinctEventTypes(ctx context.Context, sessionID int64) ([]string, error)
	// =============================================================================
	// UTILITY Operations
	// =============================================================================
	GetDistinctIndicatorTypes(ctx context.Context) ([]string, error)
	// =============================================================================
	// UTILITY Operations
	// =============================================================================
	GetDistinctSymbols(ctx context.Context) ([]string, error)
	GetDistinctTimeframes(ctx context.Context, symbol string) ([]string, error)
	GetDrawdownAnalysis(ctx context.Context, sessionID int64) (GetDrawdownAnalysisRow, error)
	GetEMAIndicators(ctx context.Context, arg GetEMAIndicatorsParams) ([]GetEMAIndicatorsRow, error)
	// =============================================================================
	// READ Operations
	// =============================================================================
	GetEventByID(ctx context.Context, id int64) (Event, error)
	GetEventCategoryDistribution(ctx context.Context, sessionID int64) ([]GetEventCategoryDistributionRow, error)
	GetEventCorrelations(ctx context.Context, arg GetEventCorrelationsParams) ([]GetEventCorrelationsRow, error)
	GetEventDensity(ctx context.Context, arg GetEventDensityParams) ([]GetEventDensityRow, error)
	GetEventFrequencyByHour(ctx context.Context, sessionID int64) ([]GetEventFrequencyByHourRow, error)
	// =============================================================================
	// TIME SERIES Operations
	// =============================================================================
	GetEventTimeline(ctx context.Context, arg GetEventTimelineParams) ([]GetEventTimelineRow, error)
	GetEventTypeDistribution(ctx context.Context, sessionID int64) ([]GetEventTypeDistributionRow, error)
	GetEventsByCandle(ctx context.Context, candleID pgtype.Int8) ([]Event, error)
	GetEventsByCategory(ctx context.Context, arg GetEventsByCategoryParams) ([]Event, error)
	GetEventsBySession(ctx context.Context, sessionID int64) ([]Event, error)
	GetEventsBySessionPaginated(ctx context.Context, arg GetEventsBySessionPaginatedParams) ([]Event, error)
	GetEventsBySeverity(ctx context.Context, arg GetEventsBySeverityParams) ([]Event, error)
	GetEventsByType(ctx context.Context, arg GetEventsByTypeParams) ([]Event, error)
	GetEventsCausingDrawdown(ctx context.Context, arg GetEventsCausingDrawdownParams) ([]Event, error)
	GetEventsInRange(ctx context.Context, arg GetEventsInRangeParams) ([]Event, error)
	GetEventsNearTimestamp(ctx context.Context, arg GetEventsNearTimestampParams) ([]Event, error)
	GetEventsSummary(ctx context.Context, sessionID int64) (GetEventsSummaryRow, error)
	GetEventsWithTags(ctx context.Context, arg GetEventsWithTagsParams) ([]Event, error)
	GetFavoriteConfigs(ctx context.Context) ([]Config, error)
	GetFavoriteSessions(ctx context.Context) ([]Session, error)
	GetFirstEvent(ctx context.Context, sessionID int64) (Event, error)
	GetFirstMetric(ctx context.Context, sessionID int64) (Metric, error)
	GetGoldenCrosses(ctx context.Context, arg GetGoldenCrossesParams) ([]GetGoldenCrossesRow, error)
	// =============================================================================
	// ANALYSIS Operations
	// =============================================================================
	GetHighImpactEvents(ctx context.Context, arg GetHighImpactEventsParams) ([]Event, error)
	GetHighVolatilityPeriods(ctx context.Context, arg GetHighVolatilityPeriodsParams) ([]Metric, error)
	// =============================================================================
	// READ Operations
	// =============================================================================
	GetIndicatorByID(ctx context.Context, id int64) (Indicator, error)
	GetIndicatorByType(ctx context.Context, arg GetIndicatorByTypeParams) (Indicator, error)
	GetIndicatorHistory(ctx context.Context, arg GetIndicatorHistoryParams) ([]GetIndicatorHistoryRow, error)
	GetIndicatorPeriods(ctx context.Context, indicatorType string) ([]pgtype.Int4, error)
	GetIndicatorStats(ctx context.Context, indicatorType string) (GetIndicatorStatsRow, error)
	GetIndicatorsByCandle(ctx context.Context, candleID int64) ([]Indicator, error)
	GetIndicatorsByType(ctx context.Context, arg GetIndicatorsByTypeParams) ([]Indicator, error)
	GetIndicatorsForCandles(ctx context.Context, arg GetIndicatorsForCandlesParams) ([]GetIndicatorsForCandlesRow, error)
	GetLastMetric(ctx context.Context, sessionID int64) (Metric, error)
	GetLatestCandle(ctx context.Context, arg GetLatestCandleParams) (Candle, error)
	GetLatestEvent(ctx context.Context, sessionID int64) (Event, error)
	GetLatestIndicator(ctx context.Context, arg GetLatestIndicatorParams) (GetLatestIndicatorRow, error)
	GetLatestMetric(ctx context.Context, sessionID int64) (Metric, error)
	GetLatestSession(ctx context.Context) (Session, error)
	GetLongestSessions(ctx context.Context, limit int32) ([]Session, error)
	GetMACDIndicators(ctx context.Context, arg GetMACDIndicatorsParams) ([]GetMACDIndicatorsRow, error)
	GetMACDSeries(ctx context.Context, arg GetMACDSeriesParams) ([]GetMACDSeriesRow, error)
	GetMAConvergence(ctx context.Context, arg GetMAConvergenceParams) ([]GetMAConvergenceRow, error)
	GetMarketBehaviorDistribution(ctx context.Context) ([]GetMarketBehaviorDistributionRow, error)
	// =============================================================================
	// READ Operations
	// =============================================================================
	GetMetricByID(ctx context.Context, id int64) (Metric, error)
	GetMetricCount(ctx context.Context, sessionID int64) (int64, error)
	// =============================================================================
	// UTILITY Operations
	// =============================================================================
	GetMetricTimestamps(ctx context.Context, sessionID int64) ([]int64, error)
	GetMetricsAboveRSI(ctx context.Context, arg GetMetricsAboveRSIParams) ([]Metric, error)
	GetMetricsBelowRSI(ctx context.Context, arg GetMetricsBelowRSIParams) ([]Metric, error)
	GetMetricsBuySignals(ctx context.Context, sessionID int64) ([]Metric, error)
	GetMetricsBySession(ctx context.Context, sessionID int64) ([]Metric, error)
	GetMetricsInRange(ctx context.Context, arg GetMetricsInRangeParams) ([]Metric, error)
	GetMetricsPaginated(ctx context.Context, arg GetMetricsPaginatedParams) ([]Metric, error)
	// =============================================================================
	// ANALYSIS Operations
	// =============================================================================
	GetMetricsRSIExtremes(ctx context.Context, sessionID int64) ([]Metric, error)
	GetMetricsSellSignals(ctx context.Context, sessionID int64) ([]Metric, error)
	GetMetricsSignalDistribution(ctx context.Context, sessionID int64) ([]GetMetricsSignalDistributionRow, error)
	GetMetricsStatsInRange(ctx context.Context, arg GetMetricsStatsInRangeParams) (GetMetricsStatsInRangeRow, error)
	GetMetricsSummary(ctx context.Context, sessionID int64) (GetMetricsSummaryRow, error)
	GetMetricsWithSignal(ctx context.Context, arg GetMetricsWithSignalParams) ([]Metric, error)
	GetMostProfitableSessions(ctx context.Context, limit int32) ([]Session, error)
	GetMostVolatileSessions(ctx context.Context, limit int32) ([]Session, error)
	GetMovingAverages(ctx context.Context, arg GetMovingAveragesParams) ([]GetMovingAveragesRow, error)
	GetOldestCandle(ctx context.Context, arg GetOldestCandleParams) (Candle, error)
	GetOverboughtIndicators(ctx context.Context, arg GetOverboughtIndicatorsParams) ([]GetOverboughtIndicatorsRow, error)
	GetOversoldIndicators(ctx context.Context, arg GetOversoldIndicatorsParams) ([]GetOversoldIndicatorsRow, error)
	GetPopularConfigs(ctx context.Context, limit int32) ([]Config, error)
	GetPriceCrossovers(ctx context.Context, sessionID int64) ([]GetPriceCrossoversRow, error)
	GetPriceMovementStats(ctx context.Context, sessionID int64) (GetPriceMovementStatsRow, error)
	// =============================================================================
	// TIME SERIES Operations
	// =============================================================================
	GetPriceSeries(ctx context.Context, arg GetPriceSeriesParams) ([]GetPriceSeriesRow, error)
	GetPriceSpikes(ctx context.Context, arg GetPriceSpikesParams) ([]Event, error)
	GetPublicConfigs(ctx context.Context, limit int32) ([]Config, error)
	// =============================================================================
	// ANALYSIS Operations
	// =============================================================================
	GetRSIExtremes(ctx context.Context, arg GetRSIExtremesParams) ([]GetRSIExtremesRow, error)
	GetRSIIndicators(ctx context.Context, arg GetRSIIndicatorsParams) ([]GetRSIIndicatorsRow, error)
	GetRSISeries(ctx context.Context, arg GetRSISeriesParams) ([]GetRSISeriesRow, error)
	GetRecentCandles(ctx context.Context, arg GetRecentCandlesParams) ([]Candle, error)
	GetRecentCrossovers(ctx context.Context, arg GetRecentCrossoversParams) ([]GetRecentCrossoversRow, error)
	GetRecentEvents(ctx context.Context, arg GetRecentEventsParams) ([]Event, error)
	GetRecentMetrics(ctx context.Context, arg GetRecentMetricsParams) ([]Metric, error)
	GetRecentPerformance(ctx context.Context, arg GetRecentPerformanceParams) (GetRecentPerformanceRow, error)
	GetRecentSessions(ctx context.Context, startedAt pgtype.Timestamptz) ([]Session, error)
	GetRecentlyUsedConfigs(ctx context.Context, limit int32) ([]Config, error)
	GetSMAIndicators(ctx context.Context, arg GetSMAIndicatorsParams) ([]GetSMAIndicatorsRow, error)
	GetSellSignals(ctx context.Context, arg GetSellSignalsParams) ([]GetSellSignalsRow, error)
	// =============================================================================
	// READ Operations
	// =============================================================================
	GetSessionByID(ctx context.Context, id int64) (Session, error)
	GetSessionByName(ctx context.Context, sessionName string) (Session, error)
	GetSessionDuration(ctx context.Context, id int64) (pgtype.Int4, error)
	GetSessionStats(ctx context.Context) (GetSessionStatsRow, error)
	GetSessionsByStatus(ctx context.Context, arg GetSessionsByStatusParams) ([]Session, error)
	GetSessionsByStrategy(ctx context.Context, arg GetSessionsByStrategyParams) ([]Session, error)
	GetSessionsBySymbol(ctx context.Context, arg GetSessionsBySymbolParams) ([]Session, error)
	GetSessionsWithTags(ctx context.Context, arg GetSessionsWithTagsParams) ([]Session, error)
	GetSeverityDistribution(ctx context.Context, sessionID int64) ([]GetSeverityDistributionRow, error)
	GetSignalDistribution(ctx context.Context) ([]GetSignalDistributionRow, error)
	GetSignalsByStrength(ctx context.Context, arg GetSignalsByStrengthParams) ([]GetSignalsByStrengthRow, error)
	GetStrategyDistribution(ctx context.Context) ([]GetStrategyDistributionRow, error)
	GetStrategyPerformance(ctx context.Context) ([]GetStrategyPerformanceRow, error)
	GetSymbolStats(ctx context.Context) ([]GetSymbolStatsRow, error)
	GetSymbolTimeframePairs(ctx context.Context) ([]GetSymbolTimeframePairsRow, error)
	GetTopEventTriggers(ctx context.Context, arg GetTopEventTriggersParams) ([]GetTopEventTriggersRow, error)
	GetUnacknowledgedEvents(ctx context.Context, sessionID int64) ([]Event, error)
	GetUserMarkedEvents(ctx context.Context, sessionID int64) ([]Event, error)
	GetVolatilityStats(ctx context.Context, sessionID int64) (GetVolatilityStatsRow, error)
	GetVolumeLeaders(ctx context.Context, arg GetVolumeLeadersParams) ([]GetVolumeLeadersRow, error)
	GetVolumeSeries(ctx context.Context, arg GetVolumeSeriesParams) ([]GetVolumeSeriesRow, error)
	GetVolumeSpikes(ctx context.Context, arg GetVolumeSpikesParams) ([]Event, error)
	IncrementConfigUsage(ctx context.Context, id int64) error
	ListAllSessions(ctx context.Context) ([]Session, error)
	ListCandlesPaginated(ctx context.Context, arg ListCandlesPaginatedParams) ([]Candle, error)
	ListConfigs(ctx context.Context) ([]Config, error)
	ListConfigsPaginated(ctx context.Context, arg ListConfigsPaginatedParams) ([]Config, error)
	ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error)
	MarkCrossover(ctx context.Context, arg MarkCrossoverParams) error
	RemoveConfigTag(ctx context.Context, arg RemoveConfigTagParams) error
	RemoveEventTag(ctx context.Context, arg RemoveEventTagParams) error
	RemoveSessionTag(ctx context.Context, arg RemoveSessionTagParams) error
	ResolveEvent(ctx context.Context, id int64) error
	SearchConfigsByName(ctx context.Context, arg SearchConfigsByNameParams) ([]Config, error)
	SearchEvents(ctx context.Context, arg SearchEventsParams) ([]Event, error)
	SearchSessionsByName(ctx context.Context, arg SearchSessionsByNameParams) ([]Session, error)
	SetDefaultConfig(ctx context.Context, id int64) error
	ToggleConfigFavorite(ctx context.Context, id int64) (pgtype.Bool, error)
	ToggleConfigPublic(ctx context.Context, id int64) (pgtype.Bool, error)
	ToggleSessionFavorite(ctx context.Context, id int64) (pgtype.Bool, error)
	ToggleUserMark(ctx context.Context, id int64) (pgtype.Bool, error)
	// =============================================================================
	// UPDATE Operations
	// =============================================================================
	UpdateCandle(ctx context.Context, arg UpdateCandleParams) (Candle, error)
	// =============================================================================
	// UPDATE Operations
	// =============================================================================
	UpdateConfig(ctx context.Context, arg UpdateConfigParams) (Config, error)
	UpdateConfigPartial(ctx context.Context, arg UpdateConfigPartialParams) (Config, error)
	// =============================================================================
	// UPDATE Operations
	// =============================================================================
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdateEventNotes(ctx context.Context, arg UpdateEventNotesParams) error
	UpdateEventStatus(ctx context.Context, arg UpdateEventStatusParams) error
	// =============================================================================
	// UPDATE Operations
	// =============================================================================
	UpdateIndicator(ctx context.Context, arg UpdateIndicatorParams) (Indicator, error)
	UpdateIndicatorSignal(ctx context.Context, arg UpdateIndicatorSignalParams) error
	// =============================================================================
	// UPDATE Operations
	// =============================================================================
	UpdateMetric(ctx context.Context, arg UpdateMetricParams) (Metric, error)
	UpdateMetricSignal(ctx context.Context, arg UpdateMetricSignalParams) error
	// =============================================================================
	// UPDATE Operations
	// =============================================================================
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpdateSessionEnd(ctx context.Context, arg UpdateSessionEndParams) (Session, error)
	UpdateSessionPrices(ctx context.Context, arg UpdateSessionPricesParams) error
	UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error
}

var _ Querier = (*Queries)(nil)
