// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addSessionTag = `-- name: AddSessionTag :exec
UPDATE sessions
SET 
    tags = array_append(tags, $2),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND NOT ($2 = ANY(tags))
`

type AddSessionTagParams struct {
	ID          int64       `json:"id"`
	ArrayAppend interface{} `json:"array_append"`
}

func (q *Queries) AddSessionTag(ctx context.Context, arg AddSessionTagParams) error {
	_, err := q.db.Exec(ctx, addSessionTag, arg.ID, arg.ArrayAppend)
	return err
}

const checkSessionExists = `-- name: CheckSessionExists :one

SELECT EXISTS(
    SELECT 1 FROM sessions WHERE id = $1
) AS exists
`

// =============================================================================
// UTILITY Operations
// =============================================================================
func (q *Queries) CheckSessionExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, checkSessionExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countSessions = `-- name: CountSessions :one

SELECT COUNT(*) FROM sessions
`

// =============================================================================
// AGGREGATE Operations
// =============================================================================
func (q *Queries) CountSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSessionsByStatus = `-- name: CountSessionsByStatus :one
SELECT COUNT(*) FROM sessions
WHERE status = $1
`

func (q *Queries) CountSessionsByStatus(ctx context.Context, status pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countSessionsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one


INSERT INTO sessions (
    session_name,
    symbol,
    timeframe,
    strategy,
    starting_price,
    parameters,
    notes,
    tags
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, session_name, symbol, timeframe, strategy, started_at, ended_at, duration_seconds, starting_price, ending_price, highest_price, lowest_price, total_candles, price_change_percent, volatility, parameters, status, notes, tags, is_favorite, created_at, updated_at
`

type CreateSessionParams struct {
	SessionName   string         `json:"session_name"`
	Symbol        string         `json:"symbol"`
	Timeframe     string         `json:"timeframe"`
	Strategy      string         `json:"strategy"`
	StartingPrice pgtype.Numeric `json:"starting_price"`
	Parameters    []byte         `json:"parameters"`
	Notes         pgtype.Text    `json:"notes"`
	Tags          []string       `json:"tags"`
}

// Sessions Queries
// CRUD operations and queries for simulation sessions
// =============================================================================
// CREATE Operations
// =============================================================================
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.SessionName,
		arg.Symbol,
		arg.Timeframe,
		arg.Strategy,
		arg.StartingPrice,
		arg.Parameters,
		arg.Notes,
		arg.Tags,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.SessionName,
		&i.Symbol,
		&i.Timeframe,
		&i.Strategy,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSeconds,
		&i.StartingPrice,
		&i.EndingPrice,
		&i.HighestPrice,
		&i.LowestPrice,
		&i.TotalCandles,
		&i.PriceChangePercent,
		&i.Volatility,
		&i.Parameters,
		&i.Status,
		&i.Notes,
		&i.Tags,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOldSessions = `-- name: DeleteOldSessions :exec
DELETE FROM sessions
WHERE ended_at < $1
  AND status = 'completed'
`

func (q *Queries) DeleteOldSessions(ctx context.Context, endedAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldSessions, endedAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec

DELETE FROM sessions
WHERE id = $1
`

// =============================================================================
// DELETE Operations
// =============================================================================
func (q *Queries) DeleteSession(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteSessionsByStatus = `-- name: DeleteSessionsByStatus :exec
DELETE FROM sessions
WHERE status = $1
`

func (q *Queries) DeleteSessionsByStatus(ctx context.Context, status pgtype.Text) error {
	_, err := q.db.Exec(ctx, deleteSessionsByStatus, status)
	return err
}

const getActiveSessions = `-- name: GetActiveSessions :many
SELECT id, session_name, symbol, timeframe, strategy, started_at, ended_at, duration_seconds, starting_price, ending_price, highest_price, lowest_price, total_candles, price_change_percent, volatility, parameters, status, notes, tags, is_favorite, created_at, updated_at FROM sessions
WHERE status = 'active'
ORDER BY started_at DESC
`

func (q *Queries) GetActiveSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.Query(ctx, getActiveSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.SessionName,
			&i.Symbol,
			&i.Timeframe,
			&i.Strategy,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSeconds,
			&i.StartingPrice,
			&i.EndingPrice,
			&i.HighestPrice,
			&i.LowestPrice,
			&i.TotalCandles,
			&i.PriceChangePercent,
			&i.Volatility,
			&i.Parameters,
			&i.Status,
			&i.Notes,
			&i.Tags,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompletedSessions = `-- name: GetCompletedSessions :many
SELECT id, session_name, symbol, timeframe, strategy, started_at, ended_at, duration_seconds, starting_price, ending_price, highest_price, lowest_price, total_candles, price_change_percent, volatility, parameters, status, notes, tags, is_favorite, created_at, updated_at FROM sessions
WHERE status = 'completed'
ORDER BY ended_at DESC
LIMIT $1
`

func (q *Queries) GetCompletedSessions(ctx context.Context, limit int32) ([]Session, error) {
	rows, err := q.db.Query(ctx, getCompletedSessions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.SessionName,
			&i.Symbol,
			&i.Timeframe,
			&i.Strategy,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSeconds,
			&i.StartingPrice,
			&i.EndingPrice,
			&i.HighestPrice,
			&i.LowestPrice,
			&i.TotalCandles,
			&i.PriceChangePercent,
			&i.Volatility,
			&i.Parameters,
			&i.Status,
			&i.Notes,
			&i.Tags,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailySessionCount = `-- name: GetDailySessionCount :many
SELECT 
    DATE(started_at) as session_date,
    COUNT(*) as session_count
FROM sessions
WHERE started_at >= $1
GROUP BY DATE(started_at)
ORDER BY session_date DESC
`

type GetDailySessionCountRow struct {
	SessionDate  pgtype.Date `json:"session_date"`
	SessionCount int64       `json:"session_count"`
}

func (q *Queries) GetDailySessionCount(ctx context.Context, startedAt pgtype.Timestamptz) ([]GetDailySessionCountRow, error) {
	rows, err := q.db.Query(ctx, getDailySessionCount, startedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailySessionCountRow
	for rows.Next() {
		var i GetDailySessionCountRow
		if err := rows.Scan(&i.SessionDate, &i.SessionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFavoriteSessions = `-- name: GetFavoriteSessions :many
SELECT id, session_name, symbol, timeframe, strategy, started_at, ended_at, duration_seconds, starting_price, ending_price, highest_price, lowest_price, total_candles, price_change_percent, volatility, parameters, status, notes, tags, is_favorite, created_at, updated_at FROM sessions
WHERE is_favorite = true
ORDER BY started_at DESC
`

func (q *Queries) GetFavoriteSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.Query(ctx, getFavoriteSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.SessionName,
			&i.Symbol,
			&i.Timeframe,
			&i.Strategy,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSeconds,
			&i.StartingPrice,
			&i.EndingPrice,
			&i.HighestPrice,
			&i.LowestPrice,
			&i.TotalCandles,
			&i.PriceChangePercent,
			&i.Volatility,
			&i.Parameters,
			&i.Status,
			&i.Notes,
			&i.Tags,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestSession = `-- name: GetLatestSession :one
SELECT id, session_name, symbol, timeframe, strategy, started_at, ended_at, duration_seconds, starting_price, ending_price, highest_price, lowest_price, total_candles, price_change_percent, volatility, parameters, status, notes, tags, is_favorite, created_at, updated_at FROM sessions
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetLatestSession(ctx context.Context) (Session, error) {
	row := q.db.QueryRow(ctx, getLatestSession)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.SessionName,
		&i.Symbol,
		&i.Timeframe,
		&i.Strategy,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSeconds,
		&i.StartingPrice,
		&i.EndingPrice,
		&i.HighestPrice,
		&i.LowestPrice,
		&i.TotalCandles,
		&i.PriceChangePercent,
		&i.Volatility,
		&i.Parameters,
		&i.Status,
		&i.Notes,
		&i.Tags,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLongestSessions = `-- name: GetLongestSessions :many
SELECT id, session_name, symbol, timeframe, strategy, started_at, ended_at, duration_seconds, starting_price, ending_price, highest_price, lowest_price, total_candles, price_change_percent, volatility, parameters, status, notes, tags, is_favorite, created_at, updated_at FROM sessions
WHERE status = 'completed'
  AND duration_seconds IS NOT NULL
ORDER BY duration_seconds DESC
LIMIT $1
`

func (q *Queries) GetLongestSessions(ctx context.Context, limit int32) ([]Session, error) {
	rows, err := q.db.Query(ctx, getLongestSessions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.SessionName,
			&i.Symbol,
			&i.Timeframe,
			&i.Strategy,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSeconds,
			&i.StartingPrice,
			&i.EndingPrice,
			&i.HighestPrice,
			&i.LowestPrice,
			&i.TotalCandles,
			&i.PriceChangePercent,
			&i.Volatility,
			&i.Parameters,
			&i.Status,
			&i.Notes,
			&i.Tags,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMostProfitableSessions = `-- name: GetMostProfitableSessions :many
SELECT id, session_name, symbol, timeframe, strategy, started_at, ended_at, duration_seconds, starting_price, ending_price, highest_price, lowest_price, total_candles, price_change_percent, volatility, parameters, status, notes, tags, is_favorite, created_at, updated_at FROM sessions
WHERE status = 'completed'
  AND price_change_percent IS NOT NULL
ORDER BY price_change_percent DESC
LIMIT $1
`

func (q *Queries) GetMostProfitableSessions(ctx context.Context, limit int32) ([]Session, error) {
	rows, err := q.db.Query(ctx, getMostProfitableSessions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.SessionName,
			&i.Symbol,
			&i.Timeframe,
			&i.Strategy,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSeconds,
			&i.StartingPrice,
			&i.EndingPrice,
			&i.HighestPrice,
			&i.LowestPrice,
			&i.TotalCandles,
			&i.PriceChangePercent,
			&i.Volatility,
			&i.Parameters,
			&i.Status,
			&i.Notes,
			&i.Tags,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMostVolatileSessions = `-- name: GetMostVolatileSessions :many
SELECT id, session_name, symbol, timeframe, strategy, started_at, ended_at, duration_seconds, starting_price, ending_price, highest_price, lowest_price, total_candles, price_change_percent, volatility, parameters, status, notes, tags, is_favorite, created_at, updated_at FROM sessions
WHERE status = 'completed'
  AND volatility IS NOT NULL
ORDER BY volatility DESC
LIMIT $1
`

func (q *Queries) GetMostVolatileSessions(ctx context.Context, limit int32) ([]Session, error) {
	rows, err := q.db.Query(ctx, getMostVolatileSessions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.SessionName,
			&i.Symbol,
			&i.Timeframe,
			&i.Strategy,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSeconds,
			&i.StartingPrice,
			&i.EndingPrice,
			&i.HighestPrice,
			&i.LowestPrice,
			&i.TotalCandles,
			&i.PriceChangePercent,
			&i.Volatility,
			&i.Parameters,
			&i.Status,
			&i.Notes,
			&i.Tags,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentSessions = `-- name: GetRecentSessions :many
SELECT id, session_name, symbol, timeframe, strategy, started_at, ended_at, duration_seconds, starting_price, ending_price, highest_price, lowest_price, total_candles, price_change_percent, volatility, parameters, status, notes, tags, is_favorite, created_at, updated_at FROM sessions
WHERE started_at >= $1
ORDER BY started_at DESC
`

func (q *Queries) GetRecentSessions(ctx context.Context, startedAt pgtype.Timestamptz) ([]Session, error) {
	rows, err := q.db.Query(ctx, getRecentSessions, startedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.SessionName,
			&i.Symbol,
			&i.Timeframe,
			&i.Strategy,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSeconds,
			&i.StartingPrice,
			&i.EndingPrice,
			&i.HighestPrice,
			&i.LowestPrice,
			&i.TotalCandles,
			&i.PriceChangePercent,
			&i.Volatility,
			&i.Parameters,
			&i.Status,
			&i.Notes,
			&i.Tags,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionByID = `-- name: GetSessionByID :one

SELECT id, session_name, symbol, timeframe, strategy, started_at, ended_at, duration_seconds, starting_price, ending_price, highest_price, lowest_price, total_candles, price_change_percent, volatility, parameters, status, notes, tags, is_favorite, created_at, updated_at FROM sessions
WHERE id = $1
`

// =============================================================================
// READ Operations
// =============================================================================
func (q *Queries) GetSessionByID(ctx context.Context, id int64) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.SessionName,
		&i.Symbol,
		&i.Timeframe,
		&i.Strategy,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSeconds,
		&i.StartingPrice,
		&i.EndingPrice,
		&i.HighestPrice,
		&i.LowestPrice,
		&i.TotalCandles,
		&i.PriceChangePercent,
		&i.Volatility,
		&i.Parameters,
		&i.Status,
		&i.Notes,
		&i.Tags,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByName = `-- name: GetSessionByName :one
SELECT id, session_name, symbol, timeframe, strategy, started_at, ended_at, duration_seconds, starting_price, ending_price, highest_price, lowest_price, total_candles, price_change_percent, volatility, parameters, status, notes, tags, is_favorite, created_at, updated_at FROM sessions
WHERE session_name = $1
LIMIT 1
`

func (q *Queries) GetSessionByName(ctx context.Context, sessionName string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByName, sessionName)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.SessionName,
		&i.Symbol,
		&i.Timeframe,
		&i.Strategy,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSeconds,
		&i.StartingPrice,
		&i.EndingPrice,
		&i.HighestPrice,
		&i.LowestPrice,
		&i.TotalCandles,
		&i.PriceChangePercent,
		&i.Volatility,
		&i.Parameters,
		&i.Status,
		&i.Notes,
		&i.Tags,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionDuration = `-- name: GetSessionDuration :one
SELECT 
    COALESCE(duration_seconds, EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - started_at))::INTEGER) as duration_seconds
FROM sessions
WHERE id = $1
`

func (q *Queries) GetSessionDuration(ctx context.Context, id int64) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, getSessionDuration, id)
	var duration_seconds pgtype.Int4
	err := row.Scan(&duration_seconds)
	return duration_seconds, err
}

const getSessionStats = `-- name: GetSessionStats :one
SELECT 
    COUNT(*) as total_sessions,
    COUNT(*) FILTER (WHERE status = 'completed') as completed_sessions,
    COUNT(*) FILTER (WHERE status = 'active') as active_sessions,
    COUNT(*) FILTER (WHERE status = 'paused') as paused_sessions,
    COUNT(*) FILTER (WHERE status = 'failed') as failed_sessions,
    AVG(price_change_percent) FILTER (WHERE status = 'completed') as avg_price_change,
    AVG(volatility) FILTER (WHERE status = 'completed') as avg_volatility,
    AVG(duration_seconds) FILTER (WHERE status = 'completed') as avg_duration_seconds
FROM sessions
`

type GetSessionStatsRow struct {
	TotalSessions      int64   `json:"total_sessions"`
	CompletedSessions  int64   `json:"completed_sessions"`
	ActiveSessions     int64   `json:"active_sessions"`
	PausedSessions     int64   `json:"paused_sessions"`
	FailedSessions     int64   `json:"failed_sessions"`
	AvgPriceChange     float64 `json:"avg_price_change"`
	AvgVolatility      float64 `json:"avg_volatility"`
	AvgDurationSeconds float64 `json:"avg_duration_seconds"`
}

func (q *Queries) GetSessionStats(ctx context.Context) (GetSessionStatsRow, error) {
	row := q.db.QueryRow(ctx, getSessionStats)
	var i GetSessionStatsRow
	err := row.Scan(
		&i.TotalSessions,
		&i.CompletedSessions,
		&i.ActiveSessions,
		&i.PausedSessions,
		&i.FailedSessions,
		&i.AvgPriceChange,
		&i.AvgVolatility,
		&i.AvgDurationSeconds,
	)
	return i, err
}

const getSessionsByStatus = `-- name: GetSessionsByStatus :many
SELECT id, session_name, symbol, timeframe, strategy, started_at, ended_at, duration_seconds, starting_price, ending_price, highest_price, lowest_price, total_candles, price_change_percent, volatility, parameters, status, notes, tags, is_favorite, created_at, updated_at FROM sessions
WHERE status = $1
ORDER BY started_at DESC
LIMIT $2
`

type GetSessionsByStatusParams struct {
	Status pgtype.Text `json:"status"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) GetSessionsByStatus(ctx context.Context, arg GetSessionsByStatusParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, getSessionsByStatus, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.SessionName,
			&i.Symbol,
			&i.Timeframe,
			&i.Strategy,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSeconds,
			&i.StartingPrice,
			&i.EndingPrice,
			&i.HighestPrice,
			&i.LowestPrice,
			&i.TotalCandles,
			&i.PriceChangePercent,
			&i.Volatility,
			&i.Parameters,
			&i.Status,
			&i.Notes,
			&i.Tags,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionsByStrategy = `-- name: GetSessionsByStrategy :many
SELECT id, session_name, symbol, timeframe, strategy, started_at, ended_at, duration_seconds, starting_price, ending_price, highest_price, lowest_price, total_candles, price_change_percent, volatility, parameters, status, notes, tags, is_favorite, created_at, updated_at FROM sessions
WHERE strategy = $1
ORDER BY started_at DESC
LIMIT $2
`

type GetSessionsByStrategyParams struct {
	Strategy string `json:"strategy"`
	Limit    int32  `json:"limit"`
}

func (q *Queries) GetSessionsByStrategy(ctx context.Context, arg GetSessionsByStrategyParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, getSessionsByStrategy, arg.Strategy, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.SessionName,
			&i.Symbol,
			&i.Timeframe,
			&i.Strategy,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSeconds,
			&i.StartingPrice,
			&i.EndingPrice,
			&i.HighestPrice,
			&i.LowestPrice,
			&i.TotalCandles,
			&i.PriceChangePercent,
			&i.Volatility,
			&i.Parameters,
			&i.Status,
			&i.Notes,
			&i.Tags,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionsBySymbol = `-- name: GetSessionsBySymbol :many
SELECT id, session_name, symbol, timeframe, strategy, started_at, ended_at, duration_seconds, starting_price, ending_price, highest_price, lowest_price, total_candles, price_change_percent, volatility, parameters, status, notes, tags, is_favorite, created_at, updated_at FROM sessions
WHERE symbol = $1
ORDER BY started_at DESC
LIMIT $2
`

type GetSessionsBySymbolParams struct {
	Symbol string `json:"symbol"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) GetSessionsBySymbol(ctx context.Context, arg GetSessionsBySymbolParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, getSessionsBySymbol, arg.Symbol, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.SessionName,
			&i.Symbol,
			&i.Timeframe,
			&i.Strategy,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSeconds,
			&i.StartingPrice,
			&i.EndingPrice,
			&i.HighestPrice,
			&i.LowestPrice,
			&i.TotalCandles,
			&i.PriceChangePercent,
			&i.Volatility,
			&i.Parameters,
			&i.Status,
			&i.Notes,
			&i.Tags,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionsWithTags = `-- name: GetSessionsWithTags :many
SELECT id, session_name, symbol, timeframe, strategy, started_at, ended_at, duration_seconds, starting_price, ending_price, highest_price, lowest_price, total_candles, price_change_percent, volatility, parameters, status, notes, tags, is_favorite, created_at, updated_at FROM sessions
WHERE tags && $1::varchar[]
ORDER BY started_at DESC
LIMIT $2
`

type GetSessionsWithTagsParams struct {
	Column1 []string `json:"column_1"`
	Limit   int32    `json:"limit"`
}

func (q *Queries) GetSessionsWithTags(ctx context.Context, arg GetSessionsWithTagsParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, getSessionsWithTags, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.SessionName,
			&i.Symbol,
			&i.Timeframe,
			&i.Strategy,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSeconds,
			&i.StartingPrice,
			&i.EndingPrice,
			&i.HighestPrice,
			&i.LowestPrice,
			&i.TotalCandles,
			&i.PriceChangePercent,
			&i.Volatility,
			&i.Parameters,
			&i.Status,
			&i.Notes,
			&i.Tags,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStrategyPerformance = `-- name: GetStrategyPerformance :many
SELECT 
    strategy,
    COUNT(*) as total_runs,
    COUNT(*) FILTER (WHERE status = 'completed') as completed_runs,
    AVG(price_change_percent) FILTER (WHERE status = 'completed') as avg_return,
    AVG(volatility) FILTER (WHERE status = 'completed') as avg_volatility,
    MAX(price_change_percent) FILTER (WHERE status = 'completed') as max_return,
    MIN(price_change_percent) FILTER (WHERE status = 'completed') as min_return
FROM sessions
GROUP BY strategy
ORDER BY avg_return DESC
`

type GetStrategyPerformanceRow struct {
	Strategy      string      `json:"strategy"`
	TotalRuns     int64       `json:"total_runs"`
	CompletedRuns int64       `json:"completed_runs"`
	AvgReturn     float64     `json:"avg_return"`
	AvgVolatility float64     `json:"avg_volatility"`
	MaxReturn     interface{} `json:"max_return"`
	MinReturn     interface{} `json:"min_return"`
}

func (q *Queries) GetStrategyPerformance(ctx context.Context) ([]GetStrategyPerformanceRow, error) {
	rows, err := q.db.Query(ctx, getStrategyPerformance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStrategyPerformanceRow
	for rows.Next() {
		var i GetStrategyPerformanceRow
		if err := rows.Scan(
			&i.Strategy,
			&i.TotalRuns,
			&i.CompletedRuns,
			&i.AvgReturn,
			&i.AvgVolatility,
			&i.MaxReturn,
			&i.MinReturn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSymbolStats = `-- name: GetSymbolStats :many
SELECT 
    symbol,
    COUNT(*) as session_count,
    AVG(price_change_percent) FILTER (WHERE status = 'completed') as avg_price_change,
    MAX(ending_price) as max_ending_price,
    MIN(ending_price) as min_ending_price
FROM sessions
GROUP BY symbol
ORDER BY session_count DESC
`

type GetSymbolStatsRow struct {
	Symbol         string      `json:"symbol"`
	SessionCount   int64       `json:"session_count"`
	AvgPriceChange float64     `json:"avg_price_change"`
	MaxEndingPrice interface{} `json:"max_ending_price"`
	MinEndingPrice interface{} `json:"min_ending_price"`
}

func (q *Queries) GetSymbolStats(ctx context.Context) ([]GetSymbolStatsRow, error) {
	rows, err := q.db.Query(ctx, getSymbolStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSymbolStatsRow
	for rows.Next() {
		var i GetSymbolStatsRow
		if err := rows.Scan(
			&i.Symbol,
			&i.SessionCount,
			&i.AvgPriceChange,
			&i.MaxEndingPrice,
			&i.MinEndingPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSessions = `-- name: ListAllSessions :many
SELECT id, session_name, symbol, timeframe, strategy, started_at, ended_at, duration_seconds, starting_price, ending_price, highest_price, lowest_price, total_candles, price_change_percent, volatility, parameters, status, notes, tags, is_favorite, created_at, updated_at FROM sessions
ORDER BY started_at DESC
`

func (q *Queries) ListAllSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.Query(ctx, listAllSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.SessionName,
			&i.Symbol,
			&i.Timeframe,
			&i.Strategy,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSeconds,
			&i.StartingPrice,
			&i.EndingPrice,
			&i.HighestPrice,
			&i.LowestPrice,
			&i.TotalCandles,
			&i.PriceChangePercent,
			&i.Volatility,
			&i.Parameters,
			&i.Status,
			&i.Notes,
			&i.Tags,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, session_name, symbol, timeframe, strategy, started_at, ended_at, duration_seconds, starting_price, ending_price, highest_price, lowest_price, total_candles, price_change_percent, volatility, parameters, status, notes, tags, is_favorite, created_at, updated_at FROM sessions
ORDER BY started_at DESC
LIMIT $1
OFFSET $2
`

type ListSessionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.SessionName,
			&i.Symbol,
			&i.Timeframe,
			&i.Strategy,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSeconds,
			&i.StartingPrice,
			&i.EndingPrice,
			&i.HighestPrice,
			&i.LowestPrice,
			&i.TotalCandles,
			&i.PriceChangePercent,
			&i.Volatility,
			&i.Parameters,
			&i.Status,
			&i.Notes,
			&i.Tags,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSessionTag = `-- name: RemoveSessionTag :exec
UPDATE sessions
SET 
    tags = array_remove(tags, $2),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type RemoveSessionTagParams struct {
	ID          int64       `json:"id"`
	ArrayRemove interface{} `json:"array_remove"`
}

func (q *Queries) RemoveSessionTag(ctx context.Context, arg RemoveSessionTagParams) error {
	_, err := q.db.Exec(ctx, removeSessionTag, arg.ID, arg.ArrayRemove)
	return err
}

const searchSessionsByName = `-- name: SearchSessionsByName :many
SELECT id, session_name, symbol, timeframe, strategy, started_at, ended_at, duration_seconds, starting_price, ending_price, highest_price, lowest_price, total_candles, price_change_percent, volatility, parameters, status, notes, tags, is_favorite, created_at, updated_at FROM sessions
WHERE session_name ILIKE '%' || $1 || '%'
ORDER BY started_at DESC
LIMIT $2
`

type SearchSessionsByNameParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) SearchSessionsByName(ctx context.Context, arg SearchSessionsByNameParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, searchSessionsByName, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.SessionName,
			&i.Symbol,
			&i.Timeframe,
			&i.Strategy,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSeconds,
			&i.StartingPrice,
			&i.EndingPrice,
			&i.HighestPrice,
			&i.LowestPrice,
			&i.TotalCandles,
			&i.PriceChangePercent,
			&i.Volatility,
			&i.Parameters,
			&i.Status,
			&i.Notes,
			&i.Tags,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleSessionFavorite = `-- name: ToggleSessionFavorite :one
UPDATE sessions
SET 
    is_favorite = NOT is_favorite,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING is_favorite
`

func (q *Queries) ToggleSessionFavorite(ctx context.Context, id int64) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, toggleSessionFavorite, id)
	var is_favorite pgtype.Bool
	err := row.Scan(&is_favorite)
	return is_favorite, err
}

const updateSession = `-- name: UpdateSession :one

UPDATE sessions
SET 
    session_name = $2,
    notes = $3,
    tags = $4,
    is_favorite = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, session_name, symbol, timeframe, strategy, started_at, ended_at, duration_seconds, starting_price, ending_price, highest_price, lowest_price, total_candles, price_change_percent, volatility, parameters, status, notes, tags, is_favorite, created_at, updated_at
`

type UpdateSessionParams struct {
	ID          int64       `json:"id"`
	SessionName string      `json:"session_name"`
	Notes       pgtype.Text `json:"notes"`
	Tags        []string    `json:"tags"`
	IsFavorite  pgtype.Bool `json:"is_favorite"`
}

// =============================================================================
// UPDATE Operations
// =============================================================================
func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSession,
		arg.ID,
		arg.SessionName,
		arg.Notes,
		arg.Tags,
		arg.IsFavorite,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.SessionName,
		&i.Symbol,
		&i.Timeframe,
		&i.Strategy,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSeconds,
		&i.StartingPrice,
		&i.EndingPrice,
		&i.HighestPrice,
		&i.LowestPrice,
		&i.TotalCandles,
		&i.PriceChangePercent,
		&i.Volatility,
		&i.Parameters,
		&i.Status,
		&i.Notes,
		&i.Tags,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSessionEnd = `-- name: UpdateSessionEnd :one
UPDATE sessions
SET 
    ended_at = $2,
    ending_price = $3,
    highest_price = $4,
    lowest_price = $5,
    total_candles = $6,
    price_change_percent = $7,
    volatility = $8,
    status = $9,
    duration_seconds = EXTRACT(EPOCH FROM ($2 - started_at))::INTEGER,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, session_name, symbol, timeframe, strategy, started_at, ended_at, duration_seconds, starting_price, ending_price, highest_price, lowest_price, total_candles, price_change_percent, volatility, parameters, status, notes, tags, is_favorite, created_at, updated_at
`

type UpdateSessionEndParams struct {
	ID                 int64              `json:"id"`
	EndedAt            pgtype.Timestamptz `json:"ended_at"`
	EndingPrice        pgtype.Numeric     `json:"ending_price"`
	HighestPrice       pgtype.Numeric     `json:"highest_price"`
	LowestPrice        pgtype.Numeric     `json:"lowest_price"`
	TotalCandles       pgtype.Int4        `json:"total_candles"`
	PriceChangePercent pgtype.Numeric     `json:"price_change_percent"`
	Volatility         pgtype.Numeric     `json:"volatility"`
	Status             pgtype.Text        `json:"status"`
}

func (q *Queries) UpdateSessionEnd(ctx context.Context, arg UpdateSessionEndParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionEnd,
		arg.ID,
		arg.EndedAt,
		arg.EndingPrice,
		arg.HighestPrice,
		arg.LowestPrice,
		arg.TotalCandles,
		arg.PriceChangePercent,
		arg.Volatility,
		arg.Status,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.SessionName,
		&i.Symbol,
		&i.Timeframe,
		&i.Strategy,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSeconds,
		&i.StartingPrice,
		&i.EndingPrice,
		&i.HighestPrice,
		&i.LowestPrice,
		&i.TotalCandles,
		&i.PriceChangePercent,
		&i.Volatility,
		&i.Parameters,
		&i.Status,
		&i.Notes,
		&i.Tags,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSessionPrices = `-- name: UpdateSessionPrices :exec
UPDATE sessions
SET 
    highest_price = GREATEST(highest_price, $2),
    lowest_price = LEAST(COALESCE(lowest_price, $3), $3),
    total_candles = total_candles + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateSessionPricesParams struct {
	ID           int64          `json:"id"`
	HighestPrice pgtype.Numeric `json:"highest_price"`
	LowestPrice  pgtype.Numeric `json:"lowest_price"`
}

func (q *Queries) UpdateSessionPrices(ctx context.Context, arg UpdateSessionPricesParams) error {
	_, err := q.db.Exec(ctx, updateSessionPrices, arg.ID, arg.HighestPrice, arg.LowestPrice)
	return err
}

const updateSessionStatus = `-- name: UpdateSessionStatus :exec
UPDATE sessions
SET 
    status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateSessionStatusParams struct {
	ID     int64       `json:"id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSessionStatus, arg.ID, arg.Status)
	return err
}
